### PR TITLE
Change new order button text on users edit page

### PR DESCRIPTION
**Pull request by kennyadsl**
It wasn't immediately clear (to me) that this "Create Order" actually means "Create a new order for this user". Please feel free to close this PR if you guys think it's ok as is. 😄

### CODE REVIEW

**Comment by mamhoff** [comment]
If we're changing the key, I would rather change it to a properly namespaced key. There is the convention with `t(".create_use_order")` which will expand into a partial-specific path, also namespaced under `spree`: `spree.admin.users.user_page_actions.create_user_order`.

@jhawthorn What do you think? I would love to get rid of the `Spree.t` helper, as it really does not provide a lot of value over the standard Rails helper.

**Comment by kennyadsl** [comment]
@mamhoff I can't find any reference about this convention in the codebase. Can you point me to something more specific please?

**Comment by mamhoff** [comment]
It's not a solidus convention, it's a rails thing (not super-well-known, but 💯 ) From http://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate: 
> Second, if the key starts with a period translate will scope the key by the current partial. Calling translate(".foo") from the people/index.html.erb template is equivalent to calling translate("people.index.foo"). This makes it less repetitive to translate many keys within the same partial and provides a convention to scope keys consistently.

**Comment by kennyadsl** [comment]
@mamhoff ah cool! I like this convention. IMHO scoping the key will also make it easier to understand the context to who will do the translation. I've made changes you proposed.

**Comment by frankie-loves-jesus** [comment]
Can't you just provide context by making comments and properly sectioning your translation files? And like the guys mentioned, being more specific. Personally I gave up on scopes a long time ago. Didn't like the extra weight.

**Comment by kennyadsl** [comment]
Thinking again, a downside of this approach could be that if that string is moved into another partial, we'll also need to change the translation keys, here and on solidus_i18n. Can this be acceptable?

**Comment by mamhoff** [comment]
I think as long as the key is only used in that particular partial, we can just take that. If we need to reuse it somewhere else, we have two options: New key, or explicitly referring to the previous partial's name (`t(:new_user_order, 'spree.admin.user.user_page_actions.create_user_page_order'). Not a big deal. 

Regarding "Giving up on scopes": Do not do that. It's frequently misses subtleties in other languages, and we end up with terrible, terrible keys like "state" meaning BOTH "region" and "status", which e.g. in German are different things. Do not give up scopes.

**Comment by jhawthorn** [comment]
Thanks everyone. I like us transitioning to the magic-scoped translation keys when we have a translation for a specific location.

**Pull request merged**
