### PR TITLE
Remove ContentController#show

### PR DESCRIPTION
**Pull request by jhawthorn**
Another not-a-vulnerability-but-looks-like-one. The `render_404` `before_filter` guard was sufficient for preventing rendering of files outside of `views/content`, `views/store`, `views/base`, and `views/application`. The guard matches recommendations from the rails team for preventing directory
traversal in this situation.

However, this code is unused in every frontend store I've come across. The behaviour this provides would be better done by a custom content controller in the app itself, which would be trivial to do.

### CODE REVIEW

**Comment by adammathys** [comment]
:+1:

**Comment by BenMorganIO** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by athal7** [comment]
is ContentController#cvv used?

**Comment by athal7** [comment]
:+1:

**Comment by jhawthorn** [comment]
@athal7 

> is ContentController#cvv used?

It's oddly used by both the frontend and backend for the "what the hell is a cvv" popup (the "what's this" link below)



I'd love to remove that in the backend in favour of something independent of frontend, but that's outside the scope of this PR.

**Pull request merged**
