### PR TITLE
[Admin] Batch Action confirmation modal (instead of alert)

### PR DESCRIPTION
**Pull request by MadelineCollier**
This would up being tougher than I originally thought it would be, and it's not quite there yet. Any insight is appreciated.

wip - confirmation works, but no way to continue the form submission without errors

Not sure if i should abandon the current stimulus triggers in favour of swapping out this:
`params["data-action"] = "click->#{stimulus_id}#handleConfirmation"` for something that renders a turbo_frame modal, which would actually have all the form submission info? maybe the batch action button should only cause the modal to open and the modal submission should contain the form info? 

Screenshot 2024-08-09 at 8 31 57 PM

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by MadelineCollier** [comment]
@forkata I'd love if you could have a look and weigh in on whether I should continue down the stimulus path you got us started on, or whether you think a turbo_frames powered modal would make more sense here. I have the feeling I am making things a bit harder than they need to be with what i've got currently. Anything is appreciated :) !

**Comment by MadelineCollier** [comment]
After some discussions, it's looking like this PR will be closed in favour of relying on the current `window.confirm()` method of prompting for user input as it perfectly suits our needs, and the only drawback being that the modal is default browser styled rather than our custom styled modal. This tradeoff is not large enough to (currently) justify the time needed to get this PR to a mergeable state and the modal behaving as we'd like so for now we will keep it as is, and this issue can be closed. We can always revisit the `window.confirm()` in the future once the larger priority admin features have been tackled!

**Comment by kennyadsl** [comment]
My only concerns is for when/if we have a match modal that also needs some input from the user (eg. batch updating the price of products, or similar scenarios), but until we get there, I'm ok with the proposed approach.

**Comment by MadelineCollier** [comment]
> My only concerns is for when/if we have a match modal that also needs some input from the user (eg. batch updating the price of products, or similar scenarios), but until we get there, I'm ok with the proposed approach.

Yes, totally. I think in the future, the rewrite will mean moving the form away from the batch_action button component and directly into the batch_action confirmation modal. That way the button click does not attempt to submit the form, it will simply trigger the modal. The modal can then wait for user confirmation, and if it receives it, can submit the form (which is currently being submitted by the button click, making the modal flow difficult to implement without a decent amount of rewriting).

**Pull request closed without merging**
