### PR TITLE
[Adim] Fix parameter name in the select component

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Summary

https://github.com/solidusio/solidus/pull/5363 was merged just before https://github.com/solidusio/solidus/pull/5360, so it didn't pick up the rename.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by rainerdema — APPROVED** [review]
👍

**Comment by rainerdema** [comment]
@waiting-for-dev We're experiencing a [404 error in the CI/CD pipeline while trying to fetch ChromeDriver](https://app.circleci.com/pipelines/github/nebulab/solidus/1344/workflows/bfec2a57-52b5-4d71-a947-9d935dc2273a/jobs/16617) 🤔

**Comment by waiting-for-dev** [comment]
The CI failure is related to https://github.com/CircleCI-Public/browser-tools-orb/pull/72 I tried the recommended workarounds with no luck

**Review by elia — APPROVED** [review]
I think we can merge, the CI brake is clearly unrelated 👍

**Pull request merged**
