### PR TITLE
Add brand from config

### PR DESCRIPTION
**Pull request by shahmayur001**
## Summary

This implementation introduces a **brand** concept to Spree products by adding a `brand` method to the `Spree::Product` model. This method delegates brand selection to a configurable class, enabling modularity and customization.

The new `Spree::TaxonBrandSelector` class fetches brands based on the **Brands** taxonomy. Developers can customize this functionality through the `brand_selector_class` attribute in `Spree::AppConfiguration`.

---

### Model Method Implementation

A `brand` method has been added to the `Spree::Product` model to retrieve the associated brand.

#### Changes in `Spree::Product`

The new `brand` method is implemented as follows:

```
def brand
  Spree::Config.brand_selector_class.new(self).call
end 
```

**Class Implementation**

The 'Spree::TaxonBrandSelector' class encapsulates the logic for identifying the brand:

```
module Spree
  class TaxonBrandSelector
	BRANDS_TAXONOMY_NAME = "Brands"

	def initialize(product)
  	@product = product
	end

	def call
  	product.taxons
         	.joins(:taxonomy)
         	.where(spree_taxonomies: { name: BRANDS_TAXONOMY_NAME })
         	.first
	end

	private

	attr_reader :product
  end
end
```

This class queries the database for taxons associated with the product and matches the 'Brands' taxonomy.

**Configuration Implementation**
A new configuration attribute was added to 'Spree::AppConfiguration' to specify the class responsible for selecting the brand for a product:

`class_name_attribute :brand_selector_class, default: 'Spree::TaxonBrandSelector'`

This configuration allows developers to override the default behavior by providing a custom class. By default, it uses 'Spree::TaxonBrandSelector'.

**Testing**
Unit tests were added to verify that the selector correctly identifies the first 'Brands' taxon.

**RSpec Example**

```
require 'rails_helper'

RSpec.describe Spree::TaxonBrandSelector, type: :model do
  let(:taxonomy) { create(:taxonomy, name: "Brands") }
  let(:taxon) { create(:taxon, taxonomy: taxonomy, name: "Brand A") }
  let(:product) { create(:product, taxons: [taxon]) }

  subject { described_class.new(product) }

  describe "#call" do
	context "when the product has a taxon under the 'Brands' taxonomy" do
  	it "returns the first taxon under 'Brands'" do
    	expect(subject.call).to eq(taxon)
  	end
	end
  end
end
```

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by kennyadsl — CHANGES_REQUESTED** [review]
Thanks for the contribution @shahmayur001! 

Please, squash all commits into a single one with a meaningful title and description. Please, read all our contributing guidelines, in particular [here](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages). 

It would also be great to:

- update our seeds/samples to include a brand on the products, now that we have this, to make it more real. 
- document what a brand is on the [guides](https://github.com/solidusio/edgeguides), including how to customize the brand class with your own logic.

**Comment by fthobe** [comment]
@kennyadsl There's no content about products or taxonomies what so every in the documentation. Where do you want the section for brands to be added?

**Comment by fthobe** [comment]
@jarednorman We are also integrating the taxons for brands inside the starter-frontend, at that point it makes sense to remove solidus from the product name in the sample data. Is that ok for you?

**Comment by shahmayur001** [comment]
Closing this PR as a clean version has been created: [#5989](https://github.com/solidusio/solidus/pull/5989).

**Pull request closed without merging**
