### PR TITLE
Use empty AR model for store migrations

### PR DESCRIPTION
**Pull request by jhawthorn**
Fixes an issue the solidus_globalize port is having because of the globalize table not existing at the time the migration is run.

Fixes issue #485

cc @dangerdogz @athal7

### CODE REVIEW

**Comment by dangerdogz** [comment]
I confirm it fixes my issue in Solidus Globalize :+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by jordan-brough** [comment]
Nice! :+1:

**Comment by jhawthorn** [comment]
@dangerdogz this is merged. Thank you for confirming.

**Pull request merged**
