### PR TITLE
Update gemspecs and README

### PR DESCRIPTION
**Pull request by jhawthorn**
Updated the summaries for all gems and simplified the README

Formatted README can be seen here: https://github.com/jhawthorn/solidus/blob/gemspec_and_readme/README.md

### CODE REVIEW

**Comment by Senjai** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by athal7** [comment]
do we want to still point people at the stable build? it looks like maybe that was removed?

**Comment by athal7** [comment]
Never mind it's higher up. :+1:

**Pull request merged**
