### PR TITLE
Deprecate the `Spree::Adjustment.return_authorization` scope

### PR DESCRIPTION
**Pull request by mamhoff**
## Summary

There is no code path that creates adjustments from return authorizations (since a long time).

This line was introduced without a lot of context in 2013, and there is nothing in the current codebase that warrants this scope.

I don't think adding a deprecation notice will do anything for anyone. If anyone tells me this scope currently returns a record in their stores, I'll add one. :)

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 ~I have updated the README to account for my changes.~
- 📑 ~I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).~
- 🛣️ ~I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).~
- ✅ ~I have added automated tests to cover my changes.~
- 📸 ~I have attached screenshots to demo visual changes.~

### CODE REVIEW

**Review by tvdeyen — APPROVED** [review]
✂️

**Review by jarednorman — COMMENTED** [review]
How long has this been unused in Solidus?

**Comment by mamhoff** [comment]
I have not found a single usage in Solidus since v1.0. I've checked in the Spree repo as well, where I could not find usages of this either.

**Comment by waiting-for-dev** [comment]
Thanks! Given the minimal effort, it won't hurt to add a deprecation message. It wouldn't be unexpected to find something unexpected in some stores :slightly_smiling_face:

**Pull request merged**
