### PR TITLE
[Guides] Add Algolia Docsearch

### PR DESCRIPTION
**Pull request by tvdeyen**
**Description**

Adds [Algolia Docsearch](https://community.algolia.com/docsearch/) to our guides. Providing a much better search for our guides.

- [x] Fix mobile portrait viewport
- [x] Prevent hitting enter from submitting form

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message

Screen Shot 2019-09-03 at 11 33 05

### CODE REVIEW

**Comment by kennyadsl** [comment]
I'm too happy and I look forward to merging this, thanks @tvdeyen! 🙂

**Comment by dhonig** [comment]
Would love to see an alogia extension for solidus, does one exist?

**Comment by tvdeyen** [comment]
Thanks. I found two things I need to address before merge. Updated the description.

**Comment by tvdeyen** [comment]
Fixed the autocomplete on small viewports and prevent the form from submitting and navigate to selected search result on enter instead 

mobile viewport

**Pull request merged**
