### PR TITLE
[v3.2] Require mail >= 2.8.0.rc1 for Ruby 3.1 support

### PR DESCRIPTION
**Pull request by tvdeyen**
Same as #4734 but for v3.2

### CODE REVIEW

**Comment by kennyadsl** [comment]
@tvdeyen you don't need to create this PR, when #4734 will be merged with the `needs-backport-3.2` label, this same PR will be created on the v3.2 branch.

**Comment by tvdeyen** [comment]
> @tvdeyen you don't need to create this PR, when #4734 will be merged with the `needs-backport-3.2` label, this same PR will be created on the v3.2 branch.

@kennyadsl wow! nice. Should I close this PR now?

**Comment by kennyadsl** [comment]
Yep, please see https://github.com/solidusio/solidus/pull/4678.

**Comment by tvdeyen** [comment]
This is very helpful for contributors! ❤️

**Comment by kennyadsl** [comment]
Maybe we should be more clear somehow that it's not required anymore (most of the times) to create these backport PRs.

**Pull request closed without merging**
