### PR TITLE
Place Carton class in Spree module.

### PR DESCRIPTION
**Pull request by bbuchalter**
For consistent code style and class-lookup behavior, classes should be
defined inside a module explicitly.

### CODE REVIEW

**Comment by jordan-brough** [comment]
I prefer the non-nested style but I don't know if we need to mandate it one way or another. @bbuchalter do you know of anything that might break if we do this one way or the other?

**Comment by bbuchalter** [comment]
@jordan-brough sadly, I don't have a way to demonstrate that the style of declaration will impact behavior. However, I do have a _memory_ that consistently is important for Ruby and Rails' code loading conventions. I'd understand if we want to close this.

**Comment by jordan-brough** [comment]
@bbuchalter I think I have the same sort of haunting memory about Rails autoloading and class declarations. :)  I can't think of what exactly might break though either.  How about we close for now and see if we get someone reporting a failure?

**Comment by bbuchalter** [comment]
Fine by me.

**Pull request closed without merging**
