### PR TITLE
Update jquery payment js library

### PR DESCRIPTION
**Pull request by mtomov**
* Update old version from 3 Sep 2013 to the latest release.

  * includes lots of bug & browser compatibility fixes

  * Specify type="tel" for numerical input fields, which fixes
    non-working card expiry field on [Samsung android phones](http://github.com/stripe/jquery.payment/issues/112)

    Follows library [recommendations](https://github.com/stripe/jquery.payment#mobile-recommendations)

---

Second commit is a bit controversial, so you might consider excluding it.

    Autocomplete name on the card and card number, but forbid CVV autocomplete.

      * As per the autocomplete recommendations at:
        https://github.com/stripe/jquery.payment#autocomplete-recommendations

---

This _gateway is anyhow overridden by the gateways, so the autocomplete might not matter; 

On the other hand, the addition of the `type=tel` attribute is indeed important to fix annoying bugs on Samsung android phones, which occur without it (even with the latest version of the jquery.payment library).

### CODE REVIEW

**Comment by cbrunsdon** [comment]
This looks good and reasonable to me, I'm :+1:

Someone else might want to complain about the switch to coffee though? I usually include .min's on my vendored assets but don't have strong opinions either way.

**Comment by jhawthorn** [comment]
I don't feel strongly about the `.min.js`. It's nice to have the `.js` to have our development slightly faster since we don't have to transpile, but the coffee is nice and readable. I'm fine either way.

A short comment in `_gateway.html.erb` linking to the jquery.payment docs to explain `type=tel` would be nice, but maybe the commit message is sufficient.

Either way :+1:

**Comment by jhawthorn** [comment]
For when I later compile release notes: This was originally introduced here c3917631156b14c2df44686e0d9d0302d0c83900 so the existing stripe.js version would have been `v1.0` and this upgrades us to `v1.3.0`

**Comment by athal7** [comment]
I also find it a bit odd to have a vendored asset in coffeescript, usually use the minified version.

**Comment by tvdeyen** [comment]
I also don't like to have vendored assets as Coffescript file. I would add the unminified JS version. AFAIK sprockets does not skip already minified files and it is great to have the readable version for debugging.

**Comment by athal7** [comment]
@tvdeyen that sounds great to me

**Comment by mtomov** [comment]
That is the case now.

I could certainly change it to whichever one you prefer. The coffee script
version came when I downloaded the latest Released, thereby. Other versions
are here <https://github.com/stripe/jquery.payment/tree/master/lib>.

**Comment by mtomov** [comment]
Should be good now.

**Comment by tvdeyen** [comment]
Ah. A proper diff 🤗 Thanks @mtomov

**Comment by athal7** [comment]
:+1:

**Comment by jhawthorn** [comment]
Thanks Martin

**Comment by mtomov** [comment]
:+1:

**Pull request merged**
