### PR TITLE
Add some hooks to admin reimbursements views

### PR DESCRIPTION
**Pull request by exsuzme**
Added some hooks to the admin reimbursements views for overriding

### CODE REVIEW

**Comment by magnusvk** [comment]
:+1:

**Comment by jhawthorn** [comment]
I'd prefer losing the `-table` suffix.

**Comment by cbrunsdon** [comment]
Also paging @graygilmore.

**Comment by graygilmore** [comment]
Agree with @jhawthorn. Other than that all good.

**Comment by exsuzme** [comment]
@graygilmore @jhawthorn @cbrunsdon done!

**Comment by exsuzme** [comment]
Whoops, got them all now.

**Comment by magnusvk** [comment]
Still :+1: :)

**Comment by jhawthorn** [comment]
:+1:

**Comment by jhawthorn** [comment]
@exsuzme Sorry. This is failing due to the totally unrelated new sprockets-rails 3.0 release (which I've addressed as #597). Once that is in I am sure this will pass and be good to merge.

**Comment by magnusvk** [comment]
@exsuzme If you rebase on the latest master this should go green.

**Pull request merged**
