### PR TITLE
Change no_resource_found implementation

### PR DESCRIPTION
**Pull request by Murph33**
Take punctuation into translations and use model name translations.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
As this commit pulls in the punctuation to the "create_one" link, I'm aware we're changing what is currently being rendered, from the exclamation mark outside the link to inside the link (and switching it to a period).

I think what we should do instead is change the entire thing to be:
no_resource_create_one that takes a param for the model name and link to the create_one, giving a tighter and more clear control to the locale file. 

I also think we should remove the duplication and render the thing as a partial (or a helper) for no_objects_found

**Comment by tvdeyen** [comment]
I support Clarke's idea. Both of them. This needs to be partial.

**Comment by jhawthorn** [comment]
Looking good

I think we need a more descriptive name than `provided_link`. Maybe "new_resource_url" or similar

**Comment by Murph33** [comment]
What would be nicest would be if we could get new_object_url to work with orders and then we wouldn't need to pass a URL at all but I don't know if that's feasible at all without either bad monkey patching or completely rewriting the world since most of the logic for that function exists on the `ResourceController` that most other things seem to inherit from instead of `BaseController`

**Comment by jhawthorn** [comment]
I actually prefer the partial not use `new_object_url`, it's best that partials don't know too much about the controller they're being used from. Explicitness is nice.

This looks good :+1:

**Comment by tvdeyen** [comment]
:+1: far better

**Pull request merged**
