### PR TITLE
Add Rails 6.1 support

### LINKED ISSUE #3784: Rails 6.1 compatibility
The latest rails-master introduced some changes that broke the CI for any PR. Solidus should be upgraded in order to take those changes into account. ~Additionally rails@master can be allowed to fail without blocking merges.~ _It's already the case, although the red mark can't be removed._

In this context we should prep for the upcoming release of Rails 6.1.

**Solidus Version**:
master

**To Reproduce**

Just look at any recent CI run, the typical error looks like this:

```
ArgumentError:
  wrong number of arguments (given 3, expected 2)
./lib/spree/testing_support/factories/variant_factory.rb:25:in `block (4 levels) in <top (required)>'
./lib/spree/testing_support/factories/stock_package_factory.rb:25:in `block (5 levels) in <top (required)>'
./lib/spree/testing_support/factories/stock_package_factory.rb:19:in `block (3 levels) in <top (required)>'
./spec/models/spree/calculator/shipping/flat_rate_spec.rb:14:in `block (2 levels) in <module:Shipping>'
```

https://app.circleci.com/pipelines/github/solidusio/solidus/1517/workflows/7e34a2fa-bf02-46bc-953c-b9f8d9eedcd7/jobs/20534

(the affected factory may vary, and the issue may well may be in `factory_girl`, but that needs to be verified)

### PR DESCRIPTION
**Pull request by filippoliverani**
**Description**
Fixes #3784 

This PR fixes some incompatibilities with Rails 6.1:
- default values of ActiveRecord serialized hash attributes have changed
- the current version of `rspec-activemodel-mocks`s mock_model is not compatible with some ActiveRecord associations
- current controller is not available anymore in `helper`s specs
- `select` in joins now always works correctly
- ActionController's error messages now provide `DidYouMean` suggestions

**TODO**:
- [x] waiting for [this PR](https://github.com/CanCanCommunity/cancancan/pull/657) to be merged to fix CanCanCan errors
- [x] waiting for https://github.com/jumph4x/canonical-rails/pull/63 and https://github.com/jumph4x/canonical-rails/pull/65  to be merged to fix solidus_frontend dependencies
- [x] waiting for [a new version of font-awesome-rails to be released](https://github.com/bokmann/font-awesome-rails/issues/206) to fix solidus_frontend dependencies

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- ~~[ ] I have updated Guides and README accordingly to this change (if needed)~~
- ~~[ ] I have added tests to cover this change (if needed)~~
- ~~[ ] I have attached screenshots to this PR for visual changes (if needed)~~

### CODE REVIEW

**Comment by kennyadsl** [comment]
@filippoliverani they both seem merged now. I'd wait for https://github.com/solidusio/solidus/pull/3865 to be merged since at the moment that's the only way to have the CanonicalRails gem working with Rails 6.1.

**Comment by peterberkenbosch** [comment]
Looking good!!

**Review by kennyadsl — APPROVED** [review]
👍

**Comment by peterberkenbosch** [comment]
Awesome work! 👍

**Review by jarednorman — APPROVED** [review]

**Pull request merged**
