### PR TITLE
fix spelling of locale logged_in_successfully

### PR DESCRIPTION
**Pull request by nspinazz89**
**Description**
Fix for #3345 

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)

### CODE REVIEW

**Comment by jacobherrington** [comment]
So this is a bit more complicated than I'd like it to be.

I think we are okay to merge this, but we will need to make a similar change in [solidus_auth_devise](https://github.com/solidusio/solidus_auth_devise/search?q=logged_in_succesfully&unscoped_q=logged_in_succesfully).

It seems like this is something people have used for some time ([based on a GitHub search](https://github.com/search?q=logged_in_succesfully&type=Code)). Hopefully the changelog will be enough to help people find this...

**Comment by jacobherrington** [comment]
Here are all of the places where we have used the misspelling: https://github.com/search?q=org%3Asolidusio+logged_in_succesfully&type=Code

**Comment by kennyadsl** [comment]
Here's another extension to be fixed: https://github.com/solidusio/solidus_i18n/search?q=logged_in_succesfully&unscoped_q=logged_in_succesfully

**Comment by kennyadsl** [comment]
Just commented on https://github.com/solidusio/solidus_auth_devise/pull/173, and now I have other concerns (sorry): if a user updates `solidus` without updating `solidus_auth_devise` they'll end up having no translation for the old wrong string which is still used into `solidus_auth_devise`. The worst thing is that in this scenario the i18n fallback will auto-generate a wrong `"Logged in succesfully"`string. 

That said, I'm tempted to ask you to leave both strings, but the [solution proposed here](https://github.com/solidusio/solidus_auth_devise/pull/173#issuecomment-534534274) won't have any effect at that point. 

Maybe the safest thing for users is to keep both things (double keys here (and `solidus_i18n`) and the fallback default in https://github.com/solidusio/solidus_auth_devise/pull/173). This way, users that update solidus will have an extra string in the i18n and in the future (maybe solidus 3.0), we will be able to safely remove the duplicated (wrong) string. What do you think?

**Comment by spaghetticode** [comment]
I agree with @kennyadsl, in order to play nice with every scenario we need to keep also the old key, and only later with a major release remove the misspelled one.

**Comment by kennyadsl** [comment]
@nspinazz89 can you please rebase this one?

**Comment by spaghetticode** [comment]
@nspinazz89 In order to improve git history readability, can you squash the commits into a single one? 🙏

**Pull request merged**
