### PR TITLE
Automatic rubocop conversion

### PR DESCRIPTION
**Pull request by jhawthorn**
As we've discussed in slack a little, we'd like to perform a mass update to fix some coding conventions.

Noteably we'd like:
* 1.9 hash syntax
* Fix indentation (lots of inconsistency surrounding `private`)
* Better erb formatting (newlines) _not covered by this_
* Consistent spacing for hashes/blocks/arrays/procs

When we decide we are happy with the results, we'll need to coordinate a little to avoid unnecessary pain and conflicts in other PRs.

This PR is the result of running `rubocop -a` starting with http://relaxed.ruby.style/ as a base. We probably want to be more or less strict than this in some ways, but I thought this would be a good starting point for discussion and exploration.

Because it would be very easy to argue forever about the [colour of this bikeshed](http://bikeshed.com/). I'd love if we could keep discussions of which rules we want to enforce to slack (where I wholeheartedly welcome discussion), at least until this is in a more complete state.

### CODE REVIEW

**Comment by tvdeyen** [comment]
This is awesome You're fast @jhawthorn 

Yes, we should disable all checks we currently not care about (like variable assignment indentation). Good catch @jarednorman

**Comment by jhawthorn** [comment]
Just a quick update

The output of rubocop after the automatic conversion is largely useful
https://gist.github.com/jhawthorn/de55a6894ca49e9c3d67

There are a few manual fixes I did here so that the AutoCorrect didn't mangle our source code, and a few others which fixed some of the warnings that occurred. It might make sense to extract those to their own PRs so that we can review just the automated changes for correctness here.

Still WIP, but I am liking the initial results.

**Comment by cbrunsdon** [comment]
This all looks reasonable to me. At the end of this, would your rubocop still give any warnings or are we now good?

**Comment by jhawthorn** [comment]
At the end of this rubocop gives (IMO very useful) warnings

**Comment by jhawthorn** [comment]
I think we are fairly happy with this conversion now, though we may relax some rules later.

**Comment by tvdeyen** [comment]
:+1: :shipit:

**Comment by cbrunsdon** [comment]
Yea, for anyone that missed some of the conversations on slack:

We're trying to achieve a balance here. We want to be able to use rubocop to alert of us potential problems and be good about alerting us on things that are universally cared about (hash syntax), but are not sure where we'll end up with enforcement of many of these.

However we wanted the giant-rewrite to have as many rules enabled as possible to get as many cleanups into the code base as possible in a global change.

**Pull request merged**
