### PR TITLE
Fix incorrect validation message for missing store credit category

### PR DESCRIPTION
**Pull request by johnpitchko**
## Summary

Fix for #4468. Corrected text in `en.yml`. Note this is branched off PR #4481, but can rebase of `master` if you want to merge this one before that one.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] I have used clear, explanatory commit messages.

The following are not always needed (~cross them out~ if they are not):

- [ ] I have added automated tests to cover my changes.
- [ ] I have attached screenshots to demo visual changes.
- [ ] I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- [ ] I have updated the readme to account for my changes.

### CODE REVIEW

**Review by jarednorman — COMMENTED** [review]
Looks good, if you don't mind rebasing out the extra commit from your other PR.

**Comment by gsmendoza** [comment]
I was able to confirm that the fix works in https://github.com/gsmendoza/solidus-4468/tree/johnpitchko/fix-incorrect-validation-message-for-missing-store-credit-category-id.

**Comment by gsmendoza** [comment]
Hi @johnpitchko ! @waiting-for-dev and I weren't able to reproduce https://github.com/solidusio/solidus/issues/4479. Like what @jarednorman said, can you remove the [Fix bad MySQL package in Dockerfile](https://github.com/solidusio/solidus/pull/4481/commits/2adc8297e4ec5f867ec58010b2b992a64ab291ba) commit from this PR? We'll need to investigate that separately. Thanks!

**Comment by waiting-for-dev** [comment]
Thanks, @johnpitchko. Yeah, we should merge it once the extra commit is removed.

**Comment by johnpitchko** [comment]
Thanks for your patient - was out of town for a few days. I dropped the commit so this should be ready now.

**Review by jarednorman — APPROVED** [review]

**Review by waiting-for-dev — APPROVED** [review]

**Comment by waiting-for-dev** [comment]
Thanks, @johnpitchko!

**Pull request merged**
