### PR TITLE
add foreign keys for shipping method zones

### PR DESCRIPTION
**Pull request by BenMorganIO**
Noticed that in #317 I didn't add foreign keys (or a dependent destroy).

### CODE REVIEW

**Comment by jhawthorn** [comment]
Looks good to me :+1:

**Comment by jhawthorn** [comment]
One thought: these `dependent: :destroys` are going to be run on "soft destroys" (this is a paranoia model). Is that what we want?

**Comment by jhawthorn** [comment]
This has a failing test

**Comment by BenMorganIO** [comment]
@jhawthorn I believe that's referential integrity doing its work :D. Kinda getting a bit giggly reading that failure.

**Comment by jhawthorn** [comment]
Closing due to age.

I don't think we want to be destroying the associated records so long as this is a "paranoia" model.

**Pull request closed without merging**
