### PR TITLE
Add acts_as_list to Spree::StockLocation

### PR DESCRIPTION
**Pull request by rymai**
Fixes https://github.com/solidusio/solidus/issues/2952.

/cc @octave

### CODE REVIEW

**Comment by rymai** [comment]
Actually I realized that it doesn't look so... I bumped into this issue when trying to reorder the stock locations in the Admin (the UI still allows to do that, so maybe we should just remove that...).

That also triggers a more interesting discussion: my original thought was that the stock locations ordering would be used in the simple shipment coordinator, but it's not. At least I think we should change `@stock_locations = Spree::StockLocation.active` to `@stock_locations = Spree::StockLocation.order_default.active` there... but that's another discussion. :D

**Comment by kennyadsl** [comment]
I think you want to look at this recently merged PR #2783 that would allow to use the `position` if needed creating and using a new StockLocation sorter class. I think we need to merge this PR anyway since there's a bug in the UI. Thanks again!

**Comment by rymai** [comment]
> I think you want to look at this recently merged PR #2783 that would allow to use the `position` if needed creating and using a new StockLocation sorter class.

@kennyadsl Thanks for the pointer! That will fulfill my need perfectly! Looking forward for the next version! :)

**Comment by rymai** [comment]
@tvdeyen Done, thanks! 🎉

**Comment by tvdeyen** [comment]
Thank you for your contribution

**Pull request merged**
