### PR TITLE
Remove HABTMs from property prototypes

### PR DESCRIPTION
**Pull request by cbrunsdon**
We're working to remove HABTM relationships from the codebase for a
variety of reasons, please see #289

This is one PR in a series of me pulling apart and splitting up @BenMorganIO's work from #289

### CODE REVIEW

**Comment by Senjai** [comment]
:shipit: :+1:, we almost always have to create models for these shadow tables at some point in time.

**Comment by tvdeyen** [comment]
I added a comment to #289 about a fix for a bug that was introduced with https://github.com/spree/spree/pull/6654

**Comment by cbrunsdon** [comment]
@tvdeyen Hmm, thanks for the link, we'd only care about that where associations need to have their class's dynamically determined, right? 

I don't need to pay attention to that for this specific commit as neither specify the class nor is it dynamically determined, correct?

**Comment by tvdeyen** [comment]
Yes,

I just wanted to be sure, that this is payed attention to ;)

**Comment by BenMorganIO** [comment]
Don't forget those foreign keys :)

@cbrunsdon thank you for taking over :+1:

**Comment by cbrunsdon** [comment]
@BenMorganIO did I need the FK's to make this legit? I was trying to get the smallest possible improvement. Tests pass on this, after all...

**Comment by BenMorganIO** [comment]
@cbrunsdon :+1: then.

**Comment by magnusvk** [comment]
:+1:

**Comment by jhawthorn** [comment]
:+1:

**Pull request merged**
