### PR TITLE
Fix deleted tracking numbers on stock transfers

### PR DESCRIPTION
**Pull request by richardnuno**
When a stock transfer already has a tracking number, the value was being overridden by the default value of the ship method.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Looks reasonable to me.

Would it instead make more sense to make this change in `StockTransfer#ship`?

**Comment by richardnuno** [comment]
@jhawthorn were you thinking something along the lines of this?

```ruby
def ship(tracking_number: nil, shipped_at: nil)
  attributes = { tracking_number: tracking_number, shipped_at: shipped_at }
  attributes[:tracking_number] = self.tracking_number if tracking_number.nil?
  update_attributes!(attributes)
end
```

I don't really like that since it seems like an unexpected side effect. If I were to call `stock_transfer.ship` or `stock_transfer.ship(tracking_number: nil)` on a stock transfer that already has a tracking number, the tracking number wouldn't be updated to nil.

**Comment by jhawthorn** [comment]
@richardnuno if that is desirable, we can have that behaviour

``` ruby
def ship(args={})
  args.assert_valid_keys(:tracking_number, :shipped_at) # raise argument error on any other keys
  args = merge(tracking_number: self.tracking, shipped_at: Time.current).merge(args)
  update_attributes!(args)
end
```

(I took the liberty of also adding a `shipped_at` default here, as IMO that should also be a default if ship is called with no arguments, we could obviously make the default nil to provide that existing behaviour)

**Comment by jordan-brough** [comment]
Why not just make the default value be the current tracking number?
```ruby
def ship(tracking_number: self.tracking_number, shipped_at: Time.current)
  update!(tracking_number: tracking_number, shipped_at: shipped_at)
end
```
(and shipped_at could stay nil, just as John said)

**Comment by richardnuno** [comment]
That, @jordan-brough, is an excellent idea. Updated with your suggestion.

**Comment by jordan-brough** [comment]
:+1:

**Comment by jordan-brough** [comment]
We should probably add a model spec for this right?

**Comment by richardnuno** [comment]
Seems like an unnecessary test to me, wouldn't the test just ensure that the default value for the parameter is applied? Feels like we're testing Ruby at that point but let me know if you were thinking of something else.

**Comment by jordan-brough** [comment]
Given the multiple ways that we thought about solving this issue, it seems very possible that someone could refactor this at some point and break this aspect of things.  But I don't feel super strongly about it if you and @jhawthorn are :+1: without it.

**Comment by jhawthorn** [comment]
I agree with @jordan-brough. This needs a test.

**Comment by richardnuno** [comment]
@jhawthorn @jordan-brough tests added

**Comment by jordan-brough** [comment]
:+1: thanks

**Comment by jhawthorn** [comment]
Excellent. Thank you. :+1:

**Pull request merged**
