### PR TITLE
Upgrade powerTip from v1.1.0 to v1.2.0

### PR DESCRIPTION
**Pull request by scottcrawford03**
* version 1.2.0 brings with it a few nice upgrades. One in particular
  that's nice is $.powerTip.destroy('element') which allows you to
  remove the powertip functionality from an element.

### CODE REVIEW

**Comment by athal7** [comment]
:+1:

**Comment by jhawthorn** [comment]
Do you know why the change to .trigger was needed when it wasn't before?

**Comment by scottcrawford03** [comment]
yeah it was overlapping. I'm not sure why it changed, but I wasn't seeing that behavior locally when I clicked around on it.

**Comment by jhawthorn** [comment]
I added a `sleep 1` before the click on powertip v1.1.0 and this issue showed up. Old powertip may have had this same quirk but didn't show up fast enough to break tests.

@scottcrawford03 I did want to note that I've toyed with the idea of totally removing powertip in favour of a pure css tooltip. Won't happen soon (requires #384) but would this affect whatever reason you want to use `$.powerTip.destroy`?

**Comment by jhawthorn** [comment]
@scottcrawford03 also just noticed the `jquery.powertip.js` file has the wrong permisisons: the execute bit is set.

**Comment by scottcrawford03** [comment]
@jhawthorn 

nope it would help actually if it was removed completely in my case as I just don't want powerTip.

I updated the permissions as well.

**Comment by jhawthorn** [comment]
@scottcrawford03 excellent. Thank you.

**Pull request merged**
