### PR TITLE
HTML class hooks for return authorization form

### PR DESCRIPTION
**Pull request by exsuzme**
We need to change some behavior in the return authorization form so these hooks are necessary.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
This went through a bit of an in-person nerdfight but the long story short is I'm :+1:. I pushed for <colgroup>'s but apparently they're not sufficient to style everything. 

You might want to ping @graygilmore to see if he wants to bikeshed the naming, or maybe has an opinion here. Lets even say my :+1: is pending a :graynodofapproval:

**Comment by exsuzme** [comment]
Thanks Clarke. @graygilmore what say you? Can my HTML classes pass through the pearly gates of Solidusio and find peace in the rolling hills of the return authorization table?

**Comment by magnusvk** [comment]
I'm :+1: here. Let's wait what the great @graygilmore has to say.

**Comment by graygilmore** [comment]
Talked to @exsuzme about it. We're just going to slightly tweak the names of the classes and then we're good to go. For those outside of the conversation, two major things:

1. Prefer explicit naming (`column` instead of `col`)
2. Name spacing where appropriate. This can be super tricky but in this case we landed on names like `return-item-product`. We want to protect against using something like `product-column` where that could conceivably be used elsewhere in the admin and we don't want to accidentally modify those as well.

**Comment by graygilmore** [comment]
:boat: :+1:

**Pull request merged**
