### PR TITLE
Connect shipping rates to shipments earlier in Stock::Coordinator

### PR DESCRIPTION
**Pull request by jordan-brough**
This will give the estimator the information it needs to calculate
taxes correctly in the pending tax work.

See comments in https://github.com/solidusio/solidus/pull/904#discussion-diff-54887938

### CODE REVIEW

**Comment by mamhoff** [comment]
:heart: Can you look at the last failing test, and then I'll rebase #904.

**Comment by jhawthorn** [comment]
> This will give the estimator the information it needs to calculate taxes correctly in the pending tax work.

If this is the case we need a spec for that

**Comment by jordan-brough** [comment]
@mamhoff & @jhawthorn updated. Look good?  I don't love the spec I added but lmk what you think. Any ideas are definitely welcome.

**Comment by mamhoff** [comment]
I tried rebasing this onto #904. My work then breaks a gazillion other things, and I think the ugly spec and this failure are related somehow: https://circleci.com/gh/solidusio/solidus/2473. I'm not so sure how to remedy this, but essentially our spec setup/our factories are set up in such a way that with this change AND my changes in, 700 specs break because apparently lots of shipping rates have no shipment when they're created. :crying_cat_face:

**Comment by jordan-brough** [comment]
@mamhoff it's [this commit](https://github.com/magiclabs/solidus/commit/e0e9b58e43fc1281610b4da5fb7fccb7fb218637) where things fall apart right? I'm happy to try to help take a look when I have a few minutes.  I think it'd be very good to avoid the `attr_accessor :order` on the shipping rate if possible in PR 904 and I think it'd be good to understand what's breaking here.

Re the spec I added in 86e4dd8:  I think it's a not-great spec because really it's testing internal implementation rather than the public API of the class.  There's probably a better way to approach a spec but I'm not sure if there's a pragmatic one.  I'll think about that some more when I have a minute (open to ideas!).

**Comment by jordan-brough** [comment]
FYI I chatted briefly with @mamhoff on this and I'm going to take some time tomorrow morning to code up a fix and improve the specs.

**Comment by jordan-brough** [comment]
@mamhoff @jhawthorn I've added a couple of commits which broaden the scope of this PR a bit but I think it's worth it.  Thoughts?

These changes fix the errors that @mamhoff's [commit](https://github.com/magiclabs/solidus/commit/e0e9b58e43fc1281610b4da5fb7fccb7fb218637) was seeing.

There is some change to the public API so I've added a changelog for that.

@mamhoff you'll want to omit [this change](https://github.com/magiclabs/solidus/commit/e0e9b58e43fc1281610b4da5fb7fccb7fb218637#diff-503e05312113225cc0cdc3b8de8515c2) to `core/spec/models/spree/stock/estimator_spec.rb` if you rebase on top of this.

**Comment by jhawthorn** [comment]
:+1:

**Comment by mamhoff** [comment]
I said so before in real life, but this is a change that will make my life a lot easier. Thank you @jordan-brough!

**Comment by gmacdougall** [comment]
Great work @jordan-brough 

:+1:

**Comment by jordan-brough** [comment]
Thanks everyone!

**Pull request merged**
