### PR TITLE
Add English variants to select2_local directory

### LINKED ISSUE #3877: The asset "solidus_admin/select2_locales/select2_locale_en-GB.js" is not present in the asset pipeline
select2_locale_en-GB.js is missing in the select2_locales folder, selecting English (UK) on the admin backend breaks the app.

**Solidus Version**:
2.11.3

**To Reproduce**
1. Open the admin backend
2. Select English (UK) in the language selection menu at the bottom right

**Current behavior**
It returns an error with the following message:
``
The asset "solidus_admin/select2_locales/select2_locale_en-GB.js" is not present in the asset pipeline
``

**Expected behavior**
It should change the language of the admin backend.

**Additional context**
Copying select2_locale_en-US.js to select2_locale_en-GB.js should fix it.

### PR DESCRIPTION
**Pull request by michaelmichael**
**Description**
Fixes #3877  
This PR adds dummy en-[XX].js files to the select2 locales directory in the admin to fix an issue where Rails returns an asset pipeline error when the user selects English (GB), English (New Zealand), English (Australia), or English (IN).

One note: This PR seems to cause [this spec](https://github.com/solidusio/solidus/blob/ed88ebc464d1373dc28f4d69cc9fd12c943ddfbe/backend/spec/features/admin/products/edit/taxons_spec.rb#L21) to fail intermittently. Apparently Capybara can't find the `.flash` element sometimes. Other times it works fine.

However, I noticed a comment in the spec that [line 35](https://github.com/solidusio/solidus/blob/ed88ebc464d1373dc28f4d69cc9fd12c943ddfbe/backend/spec/features/admin/products/edit/taxons_spec.rb#L35) is only present to prevent the spec from failing due to an issue with `select2`. What's odd is that if I comment out line 35, the spec (with my changes introduced), _always_ passes. 

I can remove that line from the spec since it doesn't appear to serve any purpose other than to act as a talisman against failure, but I wanted to present it here first.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)
- [x] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks @michaelmichael! ❤️ 

I'm fine removing that line, it was probably related to some bug with selenium that has been now fixed. If it will cause the flaky to happen again, we can easily revert the commit and reintroduce it. Let me link https://github.com/solidusio/solidus/pull/3278 for reference. 
Thanks for spotting it!

**Review by aldesantis — APPROVED** [review]

**Comment by michaelmichael** [comment]
@kennyadsl Ok, I'll remove it. Cleaner to do it in this PR or another?

**Comment by kennyadsl** [comment]
I'd say let's try to remove that code in this PR and re-run the CI a couple of times to see if the flaky goes away. If it's related to this PR somehow, it's better if we merge them together.

**Comment by michaelmichael** [comment]
Ok, I squashed those commits.

**Comment by kennyadsl** [comment]
@michaelmichael [the Rails 5.2 failure seems real](https://app.circleci.com/pipelines/github/solidusio/solidus/1961/workflows/b7d91957-2635-4848-bcd7-2a3da0964fee), I tried to re-run the CI and it happened again. Re-running it again to see what happens.

**Comment by kennyadsl** [comment]
@michaelmichael apparently, removing that line is reintroducing the flaky spec we were having before adding it. Can you please remove the commit that removes that line? I'd like to see the intermittent specs you were talking about failing in the CI.

**Comment by kennyadsl** [comment]
@michaelmichael Thanks, I'm going to run specs on the CI several times to see if we have that flaky spec yet and will let you know, thanks!

**Comment by michaelmichael** [comment]
Sounds good. FWIW, since I merged in the upstream changes I stopped getting the flaky spec in my local environment. Maybe it was something in my dev environment all along 🤷🏽

**Pull request merged**
