### PR TITLE
Allow bad payloads to be saved in payment log entries

### PR DESCRIPTION
**Pull request by elia**
## Summary

A followup to https://github.com/solidusio/solidus/pull/4950 after @gsmendoza and @kennyadsl pointed out that if a payment integration was feeding content that couldn't be deserialized the payment processing could have been disrupted vs. just breaking the payment details page in the admin console.

<del>So we're now falling back to the old and very generous `response.to_yaml`, but not before showing a proper warning asking it to be fixed. The wording of the warning is intentionally avoiding a promise that we'll reject bad payloads but instead just says that we might skip them, so we ensure to never interrupt payment processing for a secondary issue in the payment logs.</del>

So we're wrapping the bad response into a serializable one that will also report that a problem occurred.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by kennyadsl** [comment]
@elia can you please mark [this spec](https://app.circleci.com/pipelines/github/nebulab/solidus/856/workflows/3c649524-f660-4738-916b-4a9cbbade2a2/jobs/11953) as flaky in this PR?

**Comment by elia** [comment]
@kennyadsl looks like it's already marked as such on master https://github.com/solidusio/solidus/blob/master/core/spec/models/spree/order_inventory_spec.rb#L174

**Review by kennyadsl — COMMENTED** [review]
Thanks for jumping on this Elia, I left one comment for the deprecation message. Also, I'm curious about what's happening on the admin for those items. If we are just raising an error, maybe we can intercept the Error and show some information to the admin?

**Review by waiting-for-dev — APPROVED** [review]
Thanks, @elia!!!

**Review by kennyadsl — APPROVED** [review]
👏👏

**Pull request merged**
