### PR TITLE
WIP Use Spree::Zone.for_address to speed up tax rate matching

### PR DESCRIPTION
**Pull request by mamhoff**

### CODE REVIEW

**Comment by mamhoff** [comment]
In this PR, only the last two commits are relevant (the rest is rebased off other PR's that are in the process of being merged). As soon as merges happen, I'll rebase. The good news: This actually speeds up the taxation process by some 10% (46/44s before HEAD, 42/38s after HEAD). 

More good news - this can relieve us of the following methods: 

* `Spree::TaxRate.for_zone(zone)`
* `Spree::Zone.match`
* `Spree::Zone#contains?`
* `Spree::Zone.with_shared_members`
* `Spree::Zone.default_tax`
* `Spree::Order#tax_zone`
* `Spree::Order.reload`
* `Spree::DefaultTaxZoneValidator` (entire class) 

What do we do with all of these? They're exclusively used in tax calculation. Delete or deprecate?

**Comment by tvdeyen** [comment]
Although I would love to see them go immediately, everybody would hate us if we don't deprecate them properly. We're good open source citizens, right?

Do you think you could find an easy way to deprecate them or will this complicate your work dramatically?

**Comment by tvdeyen** [comment]
And with `s` in your query times you mean `ms`, right?

**Comment by mamhoff** [comment]
It's not query times, it's the time the entire taxation test suite needs on my machine. So Seconds. I know each of those queries takes ~1-2ms, but the interesting question is how much time is needed for *all* the queries when calculating taxes. That measure, of course, is less than ideal. 

As for the deprecations: No, it doesn't slow down my work. I've already started.

**Comment by mamhoff** [comment]
Closing in favour of https://github.com/solidusio/solidus/pull/862. 

Deprecations later.

**Pull request closed without merging**
