### PR TITLE
use each with object for reasons

### PR DESCRIPTION
**Pull request by BenMorganIO**

### CODE REVIEW

**Comment by jordan-brough** [comment]
Could this whole method just be rewritten as
```ruby
def self.reasons_for_return_items(return_items)
  active | return_items.map(&:return_reason).compact
end
```
?

**Comment by jhawthorn** [comment]
I don't think this is an improvement. I like @jordan-brough's version, though.

**Comment by BenMorganIO** [comment]
lol I just saw a chance to use `#each_with_object` and I was like: why not just remove two lines.

@jordan-brough good thought.

**Comment by jhawthorn** [comment]
@BenMorganIO thanks. this looks good to me. Do you mind squashing these into one commit with a better message.

**Comment by jordan-brough** [comment]
:+1:

**Comment by jhawthorn** [comment]
:+1:

**Pull request merged**
