### PR TITLE
Allow a new spree api key to be generated/cleared without persisting immediately.

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by magnusvk** [comment]
This feels like the sort of thing where you'd have a bang method that saves and a non-bang method that doesn't, rather than using a parameter? Not a strong preference but that's what I would have done given the existing method name.

**Comment by athal7** [comment]
i like that suggestion better, updated and also gave clear the same treatment

**Comment by jhawthorn** [comment]
:+1: good call Magnus

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
