### PR TITLE
use backbone for admin taxon product sorting UI

### PR DESCRIPTION
**Pull request by aaronlifton**
- Moved taxon js into a folder
- converted product sorting coffeescript to js and made it use a backbone view

extracted out of PR  #2435 

**Before**
image

**After**
image

### CODE REVIEW

**Comment by aldesantis** [comment]
@aaronlifton I know this is 2 years old 😅 but I'm triaging old PRs and this seems great! Would you be up for rebasing it? It shouldn't be terribly hard.

**Comment by aaronlifton** [comment]
@aldesantis lol, sure why not. i'll give it a go this weekend

**Comment by kennyadsl** [comment]
@aaronlifton Hey there! I'm also in favor of merging this good work. Did you have some time to rebase this one? 🙏

**Comment by aaronlifton** [comment]
@kennyadsl finally! Didn't get a chance last month, let me handle tonight. 👍

**Comment by kennyadsl** [comment]
@aaronlifton Hey there! Did you have any chance to work on this? If no, don't worry, just let us know if we can keep working on this.

**Comment by cedum** [comment]
👋 while trying to rebase this PR I've just realized the changes made here have already been implemented and merged in a different PR (Jan 2018): https://github.com/solidusio/solidus/pull/2523
If you agree, I think we can safely close this.

**Comment by aaronlifton** [comment]
@cedum Sure, let's close.

**Pull request closed without merging**
