### PR TITLE
Changed latest_payment to call reorder so default scope …

### PR DESCRIPTION
**Pull request by skukx**
…order is overriden

### CODE REVIEW

**Comment by skukx** [comment]
Issue #1525

**Comment by cbrunsdon** [comment]
Looks good to me, thanks. Can you change the commit title to remove the reference to the issue though, please? You can add it to the comment body and that would preserve the link.

**Comment by skukx** [comment]
@jhawthorn @cbrunsdon https://github.com/solidusio/solidus/pull/1526/commits/44f0e6ea4c530137aab12cf42c56a130200dabee

**Comment by skukx** [comment]
Hold off on merging until I can apply to this file as well
https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/orders/edit.html.erb#L17

**Comment by skukx** [comment]
Whats the status on this?

**Comment by jhawthorn** [comment]
Squashed and merged as fb5aa37a7e3ccae30cbb30ef372c102b413e4119. Thanks

**Pull request closed without merging**
