### PR TITLE
Remove execute permissions from README.md

### PR DESCRIPTION
**Pull request by jhawthorn**
I have no idea why it ever had `+x`

### CODE REVIEW

**Comment by magnusvk** [comment]
:+1: I love that this makes the specs fail. But that seems (thankfully) unrelated.

**Comment by jhawthorn** [comment]
Failed because I needed to rebase onto 80956281c9322abf3c1c36a038e602f0572f4194 (thanks @gvaughn)

**Comment by alexblackie** [comment]
:+1:

**Comment by Senjai** [comment]
:-1: Readme files should be executable. /s

**Comment by jhawthorn** [comment]
> Readme files should be executable. /s

```
$ ./README.md
./README.md: 2: ./README.md: Syntax error: word unexpected (expecting ")")
```

:shipit:

**Comment by jordan-brough** [comment]
:+1:

**Pull request merged**
