### PR TITLE
Restrict sqlite3 gem to '~> 1.3', like ActiveRecord

### PR DESCRIPTION
**Pull request by mamhoff**
They just released sqlite3 2.0.0, but ActiveRecord's sqlite3 adapter doesn't know about this yet, leading to conflicting sqlite3 gems in specs.

This is probably a temporary fix until ActiveRecord learns the news.

See https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L14
and https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md

### CODE REVIEW

**Review by adammathys — APPROVED** [review]

**Review by tvdeyen — COMMENTED** [review]
installer specs are failing. can't see why right now. mind looking into it?

**Comment by tvdeyen** [comment]
@mamhoff installer seems to need the same restriction

> Generating dummy Rails application...
      create  config/master.key
FRONTEND=none bin/rails generate solidus:install /tmp/dummy_extension/spec/dummy --auto-accept --admin-preview\=false --authentication\=none --payment-method\=none --migrate\=false --seed\=false --sample\=false --user-class\=Spree::LegacyUser --quiet
rake aborted!
**LoadError: Error loading the 'sqlite3' Active Record adapter**. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.0-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.

**Review by kennyadsl — APPROVED** [review]
👍

**Comment by tvdeyen** [comment]
need to backport or all backport prs will fail

**Comment by tvdeyen** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v4.0|[](https://github.com/solidusio/solidus/pull/5968)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by tvdeyen** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v4.1|[](https://github.com/solidusio/solidus/pull/5969)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
