### PR TITLE
Add `inverse_of` to order.payments

### PR DESCRIPTION
**Pull request by jordan-brough**
This doesn't seem to happen automatically and is more important now
that we're using cached association objects in OrderUpdater (see
#1389).  Solidus 1.4 broke some functionality in our app without it.  [This](https://github.com/solidusio/solidus/blob/v1.4.0.beta1/core/app/models/spree/payment.rb#L27-L28)
`after_save` in Payment triggers `order.update!` if the Order or the
Payment is complete.  That update needs to operate on the in-memory order
object or things can get out of sync.

It seems like this would be worth getting into Solidus 1.4.

In a Solidus sandbox without this patch:

    >> o = Spree::Order.create!
    >> p = o.payments.create!
    >> puts p.order.object_id, o.object_id
    70240633410460
    70240634674300

With this patch:

    >> o = Spree::Order.create!
    >> p = o.payments.create!
    >> puts p.order.object_id, o.object_id
    70145793491740
    70145793491740

There is some important history around this particular `inverse_of` --
see #407 and spree/spree_gateway#132.

Commit d7b8c73 removed part of the specs around this,
assuming that the `inverse_of` was automatically added, but it doesn't
actually seem to be (see above). The remaining tests around the issue
still pass.

I think I need to look further into the details of the prior issues to ensure
that we won't bring back bugs with this.  Any extra eyes or thoughts are
appreciated.  Any ideas on specs to add with this are also welcome.

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1: it's time to do this.

We probably can also drop the `order.reload` added in #407, as I believe that was required due to rails 4.2's awkward behaviour for `changed?` when `update_columns` was being used.

**Comment by cbrunsdon** [comment]
I'm good on this too, thanks jordan :+1:

**Comment by jordan-brough** [comment]
I've gone ahead and removed the reload mentioned by @jhawthorn and added some more comments on the specs for that.  Assuming specs go green I'll merge this next week.

Shall we backport this to 1.4 as well?

**Comment by bbuchalter** [comment]
For those who are investigating this issue be sure to also look at what impact this PR had by reviewing https://github.com/solidusio/solidus/pull/1416

**Pull request merged**
