### PR TITLE
Fix detecting exec js version by adding minimal requirement for autoprefixer-rails

### LINKED ISSUE #4055: TypeError: Cannot read property 'version' of undefined
Unable to complete installation steps.

**Solidus Version**:

3.0.1

**To Reproduce**

1. Follow installation steps
2. Start rails server
3. Go to localhost:3000

**Current behavior**

The following error can be seen on the page

Showing /usr/local/bundle/gems/solidus_frontend-3.0.1/app/views/spree/shared/_head.html.erb where line #7 raised:

TypeError: Cannot read property 'version' of undefined
Trace of template inclusion: /usr/local/bundle/gems/solidus_frontend-3.0.1views/spree/layouts/spree_application.html.erb

Rails.root: /app

**Expected behavior**

The app works properly

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows using WSL and Docker
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] V1.24.82

**Additional context**

- Tried my own custom docker version
- Tried using plain ruby and rails
- Tried with rails 5 and 6
- Tried using the docker version from master

In all scenarios, I get the same error.

### PR DESCRIPTION
**Pull request by waiting-for-dev**
Fixes #4055

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by kennyadsl** [comment]
How does this play with #4072? Are they supposed to be alternative PRs or do we need both?

**Comment by waiting-for-dev** [comment]
> How does this play with #4072? Are they supposed to be alternative PRs or do we need both?

They are independent and only tangentially related:

- `execjs` released a new version compatible with ruby 3
- The new version broke `autoprefixer-rails`
- `autoprefixer-rails` released a new version locking to the old `execjs` version (remember, not compatible with ruby 3)
- `autoprefixer-rails` released another new version fixing the issue for both 3 >= ruby < 3
- This issue makes the last `autoprefixer-rails` release the minimal version to use
- #4072 makes solidus compatible with ruby 3

**Review by kennyadsl — APPROVED** [review]
Makes sense, thanks for the detailed clarification!

**Review by spaghetticode — APPROVED** [review]
@waiting-for-dev thanks!

**Pull request merged**
