### PR TITLE
Improve I18n in users views

### PR DESCRIPTION
**Pull request by Murph33**
Use model attribute and model name translations.

This is part of an ongoing effort to improve I18n usage as discussed in #735.

### CODE REVIEW

**Comment by jhawthorn** [comment]
I'm giving this some extra thought because the user class is pluggable. Not sure if we need to provide translations for `en.activerecord.attributes.spree/legacy_user` as well as `en.activerecord.attributes.spree/user`.

**Comment by mamhoff** [comment]
My feeling is that `solidus_auth_devise` defines `Spree::User, and thus should have the translations for that class attached there. `solidus` itself defines `Spree::LegacyUser`, thus we do need to provide translations here.

**Comment by tvdeyen** [comment]
I'm with Martin. Separation of concerns. `Spree::User` related stuff is `solidus_auth_devise` responsiblity

**Comment by mamhoff** [comment]
@Murph33 can you provide attribute translations for the `Spree::LegacyUser` class, please? Once that's in, we can merge this.

**Comment by mamhoff** [comment]
:+1: Thank you!

**Pull request merged**
