### PR TITLE
Remove protected from controllers

### PR DESCRIPTION
**Pull request by jarednorman**
We shouldn't need any of these.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
:+1:

**Comment by athal7** [comment]
i would vote for keeping these as protected, no harm and leaves a bit more flexibility for extension. https://github.com/solidusio/solidus/pull/338/files#diff-65b40bbcedba89897613ce6d5becb581R12 in particular I would expect to be used by subclasses

**Comment by jordan-brough** [comment]
@athal7 subclasses should be able to still use them just fine if they're private.  It's just a question of whether controller instances can call those methods on other controller instances of the same class/superclass type.  And I can't think of when we'd have one controller instance operating on another controller instance.

**Comment by jordan-brough** [comment]
iow as long as we only need to call the method with an implicit receiver (which I believe is the case unless I'm forgetting something?) it seems like we should be ok?  https://gist.github.com/jordan-brough/87405488cc89d355d86a

**Comment by athal7** [comment]
derp :+1:

**Comment by jarednorman** [comment]
Perhaps a better explanation in the commit body is warranted, as lots of people tend to assume Ruby's protected works like other languages' protected.

**Pull request merged**
