### PR TITLE
Add Armenian language translations for `Select2` plugin

### PR DESCRIPTION
**Pull request by arman-h**
## Summary

Adding Armenian language translations for `Select2` plugin.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
With the help of ChatGPT, this looks correct. Thanks!

**Comment by kennyadsl** [comment]
@arman-h may I also ask you to squash all commits into a single one?

**Review by jarednorman — APPROVED** [review]

**Comment by waiting-for-dev** [comment]
Thanks, @arman-h! As suggested, could you please squash all commits before we merge it? :pray:

**Comment by Julian-Dumitrascu** [comment]
The discussion is more complex than this; we require more than one thing. I mention this one: We're choosing software for building a marketplace in the Romanian language. With whom would you like me to communicate about this?

**Comment by kennyadsl** [comment]
Hey @Julian-Dumitrascu, if you want, I'm available for guidance in exploring Solidus. You can find me in our [Slack](https://solidusio.slack.com/join/shared_invite/zt-219q2msja-eVbYnBRKG0ItxzwtLkJu_w#/shared-invite/email).

**Pull request merged**
