### PR TITLE
Improvements to delegate_belongs_to

### PR DESCRIPTION
**Pull request by jhawthorn**
Started with a cherry pick of @eric1234's spree/spree#6667 :+1:. Went on to add deprecations for the worst parts of `delegate_belongs_to`, remove some broken bahaviour, and do a little cleanup.

### CODE REVIEW

**Comment by gmacdougall** [comment]
:+1: so far.

Should we consider going all the way and removing `delegate_belongs_to` and just use the standard rails delegate?

**Comment by athal7** [comment]
I'd be in favor of not using our own variant of delegate as well.

**Comment by jhawthorn** [comment]
We should absolutely use `delegate` when it does everything we need. `delegate_belongs_to` has an extra feature: it will build the `belongs_to` or `has_one` association if it does not exist. We need this in order to do things like `Variant.new(price: 5.50)`

Consider the following:
```
variant = Spree::Variant.new

variant.default_price  # => nil
variant.price          # => nil
variant.default_price  # => #<Spree::Price id: nil, variant_id: nil, amount: nil, currency: "USD", deleted_at: nil, is_default: true>

variant.price = 2      # => 2
variant.default_price  # => #<Spree::Price id: nil, variant_id: nil, amount: #<BigDecimal:7fdaef600be0,'0.2E1',9(27)>, currency: "USD", deleted_at: nil, is_default: true>

variant = Spree::Variant.new(price: 2)
variant.default_price  # => #<Spree::Price id: nil, variant_id: nil, amount: #<BigDecimal:7fdaef5982e8,'0.2E1',9(27)>, currency: "USD", deleted_at: nil, is_default: true>
variant.price          # => 2.0
```

**Comment by athal7** [comment]
@jhawthorn are there a lot of cases where that is necessary? if not I think I'd rather do a find or build in explicit code.

**Comment by jhawthorn** [comment]
One thing we could do instead is:

```
def find_or_build_default_price
  default_price || build_default_price
end

delegates :price, :price=, ..., to: :find_or_build_default_price
```

**Comment by athal7** [comment]
I do like that proposed approach better

**Comment by gmacdougall** [comment]
It's certainly clearer to see what's going on. The delegate_belong_to code is a bit scary...

**Comment by jhawthorn** [comment]
I think I agree. Opened #320

**Comment by jhawthorn** [comment]
Closed in favour of #320

**Pull request closed without merging**
