### PR TITLE
Remove some unnecessary admin JS

### PR DESCRIPTION
**Pull request by jhawthorn**
Remove jquery.valign, which we used to vertically align checkbox fields. We can use flexbox for this instead (IE10+).

Remove `equalize.js`, this was a ham fisted way to increase the height of sidebar `<dl>` items and fix an issue with floating. Replaced this with a min height for list items in the sidebar and a working `clear:` for all `<dl>`.

Removed Modernizr, which we were using as an html5shiv (needed for IE<9). We only support IE10+ and don't need this.

Removed responsive tables because it looked like:

cc @graygilmore

### CODE REVIEW

**Comment by graygilmore** [comment]
:+1: The more of these things we can remove now, the easier cleaning up the whole admin will become.

**Comment by Senjai** [comment]
:+1: :shipit: :tada: :100:

**Comment by cbrunsdon** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1: thanks for the cleanup @jhawthorn

**Pull request merged**
