### PR TITLE
Use admin api path for product search in promo

### PR DESCRIPTION
**Pull request by exsuzme**
Spree was pointing to the admin/products search endpoint and somehow with the Solidus upgrade we started using the api/products endpoint instead, which was timing out. This just reverts back to the admin/products api for faster performance on product search.

### CODE REVIEW

**Comment by magnusvk** [comment]
:+1: though... We could think about making `api/products` less terribly slow at some point, as that does seem like a sensible endpoint to use.

**Comment by jhawthorn** [comment]
`api/products` is slow because it displays taxons, variants, images, **stock levels**.

:+1: for now this is a good performance fix. I've created #244 to revisit this.

**Comment by BenMorganIO** [comment]
Does anyone know how hard it would be to let the Spree Backend take advantage of say elasticsearch instead of rabl? Since ES already indexes all the data, I'm crossing my fingers and hoping it might be a faster solution.

**Comment by BenMorganIO** [comment]
Of course, we'd have to give a user a choice between rabl and es.

**Comment by gmacdougall** [comment]
We don't really have a well supported elasticsearch integration right now, so I think that would have to be our first step.

**Comment by BenMorganIO** [comment]
@gmacdougall I know. I might be interested in helping build it out.

**Pull request merged**
