### PR TITLE
Add `covered_by_store_credit` translation in en.yml

### PR DESCRIPTION
**Pull request by rainerdema**
## Summary

This PR adds a new translation key 'covered_by_store_credit' in en.yml.
The new key provides a specific message to inform users when their order is fully covered by store credits and no additional payment method is required.
This change is connected to an update made in Solidus Starter Frontend: https://github.com/solidusio/solidus_starter_frontend/pull/348

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by kennyadsl** [comment]
@rainerdema did you consider adding this key to the starter fronted instead?

**Comment by elia** [comment]
> @rainerdema did you consider adding this key to the starter fronted instead?

This! I too think we should push translations out of core unless they're not strictly related to it.

**Comment by rainerdema** [comment]
> @rainerdema did you consider adding this key to the starter fronted instead?

Sure @kennyadsl, but the starter frontend doesn't have a translations file and mainly uses those from the core at the moment.
Even though I'm not fond of this, since I only have to add one key, I've preferred to simply do it here with this small PR.
Let me know if there is another way to do this for the frontend starter.

**Review by elia — CHANGES_REQUESTED** [review]
This translation can open the way for having them in the starter https://github.com/solidusio/solidus_starter_frontend/pull/348#pullrequestreview-1510624691

**Comment by rainerdema** [comment]
Closing, it will be addressed with https://github.com/solidusio/solidus/issues/5212

**Pull request closed without merging**
