### PR TITLE
Correct misspelling in API Documentation for Create Product

### PR DESCRIPTION
**Pull request by octoxan**
"Creates" in the header was misspelled as "Creaets". This is just a quick fix.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)

### CODE REVIEW

**Comment by spaghetticode** [comment]
@octoxan can you please rebase with master, so we get a green CI? Thank you 🙏 💚

**Comment by octoxan** [comment]
@spaghetticode done

**Comment by spaghetticode** [comment]
@octoxan something went wrong with the rebase, your PR has now 23 commits from other people

**Comment by octoxan** [comment]
Ah dang. My bad. I'll try to fix it in the morning. I did a `git checkout
master` then a `git pull` followed by a `git rebase master`. Will try to
fix it somehow. Sorry about that!

**Comment by octoxan** [comment]
There we go.

**Pull request merged**
