### PR TITLE
it's Rails 5.0 on master now.

### PR DESCRIPTION
**Pull request by peterberkenbosch**
Update the README to use a Rails 5 app instead.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
Good by me, thanks peter :+1:.

**Comment by jhawthorn** [comment]
:+1:

**Comment by jhawthorn** [comment]
Although the instructions are a little awkward right now, adding `gem 'solidus'` will still get you solidus 1.3, which runs rails 4.2. Maybe we want to merge this only after releasing 2.0

**Comment by peterberkenbosch** [comment]
@jhawthorn ah yeah, sounds like the best plan indeed.

**Comment by jhawthorn** [comment]
:tada: Thanks @peterberkenbosch

**Pull request merged**
