### PR TITLE
Fix ability to perform refunds after a first failed attempt

### PR DESCRIPTION
**Pull request by kennyadsl**
**Description**

With #1415 we introduced a bug in the Admin:

When attempting to create a refund for a payment that fails with a gateway error, it's no more possible to create refunds for that payment. 

To reproduce:

1. Click the refund link on any payment

Screenshot 2020-11-05 at 15 41 27

2. Refund credit allowed is correct, let's proceed with the refund **using a gateway that will fail**

Screenshot 2020-11-05 at 15 41 38

At this point, we have the flash message correctly printed with the error:

Screenshot 2020-11-05 at 15 42 02

3. A refund is actually created and we can't create new refunds:

Screenshot 2020-11-05 at 15 42 16

This is due to the split of record creation and calling `perform!` in `Spree::Admin::RefundsController#create`. In fact, when we create a refund in the first place, it is added to the database but when we call `perform!` right after the creation, and it fails, the record created is not marked as failed anyhow. The system assumes all refunds are successful and consider them done if when they failed, disabling us to create new ones for those payments.

In fact, the refundable amount is calculated with 

```
payment.credit_allowed = payment total - refunds amount
```

and this formula is true also when the refund has not been successful.

This comes from our past behavior of creating and calling perform! on refunds at the same time. Records weren't created if the refund failed to perform.

A more clean solution would be considering in that formula only refunds that are completed but at the moment there's no way to do that. This way we can also keep track of the failed attempts to perform refunds, saving all the information we get back from the gateway. But this is way more invasive and we can't do this in a patch level fix. 

This change is supposed to be merged in master (for 3.0) and backported to v2.11, which is the version that introduces the bug.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] ~I have updated Guides and README accordingly to this change (if needed)~
- [x] I have added tests to cover this change (if needed)
- [x] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Review by jarednorman — CHANGES_REQUESTED** [review]
What if we initialize but don't save the refund before calling `perform!` and have `perform!` save the record (if it doesn't already)?

This would avoid this weird code that recreates the refund.

Regardless, I agree that tracing the success/fail state would be a better solution in the long run. Would probably be worth having three states: pending (default state), complete and failed.

**Comment by aldesantis** [comment]
I would also prefer not to save the refund at all unless it's been successfully performed. Would that be possible?

**Comment by kennyadsl** [comment]
I think it's a great idea, working on that and will let you know, thanks!

**Comment by kennyadsl** [comment]
@aldesantis @jarednorman please review again when you have time, and thanks again for pointing in the right direction. The first attempt was so bad!

**Review by spaghetticode — APPROVED** [review]
@kennyadsl makes sense to me, thanks 👍

**Review by aldesantis — APPROVED** [review]
Looking good, thanks @kennyadsl!

**Comment by kennyadsl** [comment]
@jarednorman will wait for your review before merging if you have some time. Please let me know!

**Review by jarednorman — APPROVED** [review]

**Pull request merged**
