### PR TITLE
Use normal get/post/put/delete spec helpers instead of spree_*

### PR DESCRIPTION
**Pull request by jhawthorn**
The spree_get and similar helpers no longer do anything. The `ControllerRequests` module now [just sets the `routes`](https://github.com/solidusio/solidus/blob/master/core/lib/spree/testing_support/controller_requests.rb#L45-L47) and the `spree_*` helpers don't do anything other than call the standard helpers.

### CODE REVIEW

**Comment by gmacdougall** [comment]
Yay! I always disliked those.

Could you also flag the existing `spree_*` helpers as deprecated?

**Comment by tvdeyen** [comment]
:+1: and deprecation is great.

**Comment by mamhoff** [comment]
👍

**Comment by cbrunsdon** [comment]
Fantastic, big :+1:  from me too.

**Comment by mtomov** [comment]
wow, brilliant, thanks a lot!

**Pull request merged**
