### PR TITLE
Move "thinking cat" fixture to lib folder

### PR DESCRIPTION
**Pull request by mamhoff**
## Description

With the exclusion of the spec folder from the packaged solidus_core gem
in 80bea87, all factories that use an image can now not access that
image when loaded from the lib folder of a packaged gem.

The reason for that is that the image referenced in those factories
lives under spec/fixtures - in the spec folder.

This commit does the simplest thing that could possibly work: Move the
image to the lib/fixtures folder instead and adapt the factories so that
they work even if loaded from the packaged gem.

One could imagine a single-pixel image file instead of an actual JPEG of a thinking cat to conserve space on the many machines this gem runs on. Would that still be in scope? 

I would very much like a new version of Solidus to be cut with this change, as 2.11.0 has broken factories because of this.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by aldesantis** [comment]
Thanks @mamhoff! 🙏 Do you think it would make more sense to move the image to `lib/spree/testing_support/fixtures`, since that's where all test-related files live (including the factories)?

**Comment by mamhoff** [comment]
Sure! but you know what: When I do that, I might as well also do the 1-pixel-image thing? I mean I don't think it's worth distributing those 20kB that I have not looked at in the however many years I've spent with this software.

**Comment by aldesantis** [comment]
Go for it! 👍

**Comment by kennyadsl** [comment]
@mamhoff thanks for this PR! For some reason, CircleCI did not receive the hook for running the CI after the last push. Can you please push again to retrigger it?

**Review by kennyadsl — APPROVED** [review]
Thanks, Martin!

**Review by aldesantis — APPROVED** [review]

**Comment by kennyadsl** [comment]
I'm going to backport and release Solidus 2.11.1 tomorrow, thanks again!

**Pull request merged**
