### PR TITLE
be more forgiving in receiving a ready event in a shipment

### PR DESCRIPTION
**Pull request by gvaughn**
this allows partial failures and corners cases to retry with
less manual intervention

### CODE REVIEW

**Comment by jhawthorn** [comment]
Can you be more specific about why this change is desirable? I preferred the previous code.

Also this needs a test.

**Comment by gvaughn** [comment]
OK. I'll add a test.

We had an order in which one shipment was already in a shipped state. Now we can't progress the rest of the items to a shipped state. This allows that one shipment to just be a no-op and not raise and abort the whole order.

**Comment by magnusvk** [comment]
Some discussion that's pertinent to this on https://github.com/solidusio/solidus_signifyd/pull/9

**Comment by gvaughn** [comment]
New commit added which refactors the name of the `ready` event to `ready_to_test` to help avoid confusion with the `ready` state. I added an issue to further discuss this portion of the state transitions.

More discussions have happened on the https://github.com/solidusio/solidus_signifyd/pull/9 PR that really is more general about the state machine and more logically belongs here.

**Comment by jordan-brough** [comment]
:+1: It seems like the shipment states and state machine could use some more thought, but given our current code I think this makes sense and I really like the event rename.

@gvaughn if other people like this then there are some more places in solidus where we should replace the now-deprecated methods as part of this PR right?

**Comment by gvaughn** [comment]
@jordan-brough Yes, great point. On a quick grep and scan (`ready` has a lot of false positives) the main place seems to be [ShipmentsController](https://github.com/bonobos/solidus/blob/more_forgiving_ready_events/api/app/controllers/spree/api/shipments_controller.rb#L45-L55) which also has that check for `can_ready?` instead of letting the state machine centralize what's allowed when.

I'll run the whole test suite to find any other deprecated calls and add to this PR.

**Comment by gvaughn** [comment]
Bump. @jhawthorn I'm curious to get your current opinion on this from a stembolt perspective.

**Comment by jhawthorn** [comment]
Seems okay, but this changes the behaviour of `ready`, `ready!`, `can_ready?`. It seems odd to deprecate them and at the same time change behaviour.

**Comment by jhawthorn** [comment]
Actually :bomb: this seems really, really broken. I think this allows you to ready_to_ship twice, which will cause `after_ship` more than once, which is very bad.

Instead, let's keep the previous state machine and introduce a new plain method which has this behaviour

**Comment by gvaughn** [comment]
Since the state is not changing, the state_machine gem is smart enough not to re-call the callback

**Comment by jhawthorn** [comment]
Excuse my lazy debugging

```
> shipment = Spree::Shipment.create!(state: 'shipped')
> def shipment.after_ship
    puts "after ship"
  end
> shipment.ready_to_ship
after ship
> shipment.ready_to_ship
after ship
```

**Comment by gvaughn** [comment]
@jordan-brough just caught the bug in my test. I take it all back.

**Comment by gvaughn** [comment]
Idealistically I'd still love to see this sort of no-op behavior defined within the state machine, but this gem doesn't seem to have a way to specify no-op for certain events in certain states. Even though we could protect within the after_ship method, other stores may also have hooks added to the state machine. Closing this in favor of a more tactical workaround in the solidus-signifyd project.

**Pull request closed without merging**
