### PR TITLE
Change around SKUS appearance on product page

### PR DESCRIPTION
**Pull request by Murph33**
We wanted to remove the bullets, italics, and the indent.  Did this through minor adjustments to a class we only use in one place and a tweak to the info class so it doesn't italicize in this location. As requested by @Mandily 

## Before
with_bullets

## After
final_changes

### CODE REVIEW

**Comment by mtomov** [comment]
Probably not part of your PR, but linking those to the edit screen on the variant would help a lot. Thanks!

**Comment by Murph33** [comment]
That's definitely a good idea @mtomov and I think it's within scope for this.  After all we're just improving that little part of the page and them being links is much nicer.

**Comment by mtomov** [comment]
It is! Thanks!

**Comment by mamhoff** [comment]
:+1: This is good!

**Comment by cbrunsdon** [comment]
I'm okay with this too, thanks for the change :+1: 

Though I imagine long term we'll want both those styles dead...

**Pull request merged**
