### PR TITLE
[Admin][Product] fix properties edit action in admin panel part of the issue #5857

### PR DESCRIPTION
**Pull request by Astr0surf3r**
## Summary

I have just downloaded the gem to fix the issue [#5857](https://github.com/solidusio/solidus/issues/5857) and I found in admin panel an error in Property Types (in your [demo](https://demo.solidus.io/admin/login) the error appear as well)

After I added a new one property and no issue came up clicking in the `+ Add new` button of the `/admin/properties` page 

new-properties

but after I saved it 

properties-list

I couldn't edit it because an error appear

error-issue-solidus

so to fix this I add the **show action** in the `Spree::Admin::PropertiesController` and create an rspec file I hope this can help your great work

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by tvdeyen — COMMENTED** [review]
Thanks. Would you mind to update the link instead. We do not have show actions anywhere. We only ever have edit actions. By updating the link to the edit route it should be fixed

**Comment by Astr0surf3r** [comment]
> Thanks. Would you mind to update the link instead. We do not have show actions anywhere. We only ever have edit actions. By updating the link to the edit route it should be fixed

@tvdeyen  done

**Comment by tvdeyen** [comment]
@Astr0surf3r please use rebase to update your branch as mentioned in the [contribution guidelines](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md)

**Comment by Astr0surf3r** [comment]
> c05d55a



> @Astr0surf3r please use rebase to update your branch as mentioned in the [contribution guidelines](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md)

@tvdeyen I hope now the PR is cleaner than before ... if need something else to do (I have read the guidelines) let me know please I really appreciate all your tips and messages to give a hand to your great project [c05d55a](https://github.com/solidusio/solidus/pull/5885/commits/c05d55a3ee5643ec8a212fa9de5ccf352474ef4e)

**Comment by tvdeyen** [comment]
@Astr0surf3r please rebase with latest main branch and make one commit containing only your changes. Thanks

**Comment by MadelineCollier** [comment]
The work started here has been pulled into https://github.com/solidusio/solidus/pull/6011. Thanks for your contribution @Astr0surf3r !

**Pull request closed without merging**
