### PR TITLE
Move all developer guides to guides/developers/

### PR DESCRIPTION
**Pull request by benjaminwil**
Now that we are expanding the Solidus guides to include guides that are not aimed at a only at a developer audience, we should make a clear distinction of audience when we create new articles. 

Developer documentation should go in a `developers/` subdirectory. This PR simply moves everything that's currently in the `guides/` directory to the `guides/developers/` directory.

### CODE REVIEW

**Review by tvdeyen — COMMENTED** [review]
If we begin adding more guide categories we should think about moving them into their own repository. Especially if we start to add assets, screenshots, maybe videos.

**Comment by tvdeyen** [comment]
@benjaminwil this needs a rebase.

**Review by tvdeyen — APPROVED** [review]
Looks good 👍

**Comment by benjaminwil** [comment]
This pull request is no longer necessary because #2740 was merged.

**Pull request closed without merging**
