### PR TITLE
Refactor zones

### PR DESCRIPTION
**Pull request by mamhoff**
Adds a method to find all zones with shared members (which will really help in finding out which tax rates apply for a particular zone, even if those rates' zone encompasses more territory than the zone in question). 

This method includes a complex SQL query that `Spree::Zone#match` also does. Moved to a scope. 

Furthermore, improve the documentation so it's somewhat easier to find out what all these things do.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
The first commit here is covered by #529, maybe shoot this PR at that branch instead?

**Comment by mamhoff** [comment]
I'd like to, but Github doesn't let me. Would it be an option to create a branch for the VAT refactoring, and I just point all my PRs to that?

**Comment by mamhoff** [comment]
Rebased.

**Comment by cbrunsdon** [comment]
:+1:, good by me.

**Comment by mamhoff** [comment]
Sped up `Spree::Zone.with_shared_members` a little, and rebase on current master.

**Comment by jhawthorn** [comment]
:+1:

**Pull request merged**
