### PR TITLE
Port Order#merge! fix from Spree

### PR DESCRIPTION
**Pull request by mtomov**
This commit on Spree https://github.com/spree/spree/commit/d923c10761922801dd2c31b7317877ae0917de6f fixes an often occurring bug when carts are merged together, but their line items contain validation errors (usually not enough stock). 

Before, calling `save!` on the line item was raising an uncaught error, leaving an unpleasant user experience, and inability to even log in.

This commit extracts the full Order#merge! logic into an own class, and most importantly - does away with the bang on the saves!

This is just a port of the commit to Solidus.

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1: Seems reasonable to me. We should document that the `OrderMerger` only makes a *best effort* two merge the two orders together.

In the future I'd love if there was a separate commit to extract into a class and a separate commit to make the change. But I understand that this is a commit from spree which had probably been squashed there.

**Comment by gmacdougall** [comment]
It's also looking good to me. One thing I might consider doing is adding some YARD docs for the OrderMerger.

@mtomov thanks for the PR! One of us can take up the task of adding the docs to this PR if you'd prefer.

**Comment by mtomov** [comment]
Yes, agree with both of you. Separate commits for the fix and the refactor would've indeed been preferable if I had written the code.

If you prefer, you can also squash the 2 commits, as the first on obviously does not have all tests passing. Haven't done Yard docs before, so I would just observe you.

Thanks a lot for being active & improving the framework.

**Comment by gmacdougall** [comment]
I have added documentation in https://github.com/gmacdougall/solidus/commit/8112b719e422980b995e8df8533430698cb1343a

@mtomov Could you cherry-pick that change in? I can also submit a PR to your branch if you'd prefer.

As part of that change, I also made a number of these methods private, as they're not used outside of the class.

**Comment by mtomov** [comment]
Wow, great explanations. Thanks a lot! 

Let me know if I need to do anything else.

**Comment by jhawthorn** [comment]
:+1:

**Comment by BenMorganIO** [comment]
@gmacdougall :+1:

**Comment by jordan-brough** [comment]
I opened a PR with a couple tweaks here: https://github.com/mtomov/solidus/pull/1. Thoughts?

**Comment by jordan-brough** [comment]
:+1: 

@gmacdougall or @jhawthorn does this still look OK to you?

**Comment by jhawthorn** [comment]
Still looks great.

**Pull request merged**
