### PR TITLE
Preparations for Rails 5.2 (part 2)

### PR DESCRIPTION
**Pull request by jhawthorn**
There were some changes in 5.2.0.rc1, since the betas, which we needed to adjust for.

### CODE REVIEW

**Comment by damienlethiec** [comment]
Hello @jhawthorn . Thanks for the great work. I am beginning a new solidus app with Rails 5.2 soon. Should I use the Github version of the gem for the moment? When with the 5.2 compatible version of Solidus released? Thank you :)

**Comment by jhawthorn** [comment]
@damienlethiec Unfortunately there isn't yet a Rails 5.2 compatible version of Solidus yet. Biggest blocker right now is `cancancan`, which does not work on Rails 5.2 (see #2460).

**Comment by damienlethiec** [comment]
Thanks a ton for the answer!! Any idea of when a compatible version could be ready (even if I understand you don't have any control over CanCanCan)

**Comment by jhawthorn** [comment]
> Thanks a ton for the answer!! Any idea of when a compatible version could be ready (even if I understand you don't have any control over CanCanCan)

With this change it's just the gems we depend on (barring any changes between rc and final release). cancancan doesn't want to merge any changes before final release, so some time after that.

Solidus 2.5 will likely ship without Rails 5.2 support, but I would like to cut a Solidus 2.6 within a few weeks of the final release.

**Comment by damienlethiec** [comment]
Great, thank you!

**Pull request merged**
