### PR TITLE
Allow migrating from spree 3.0

### PR DESCRIPTION
**Pull request by jhawthorn**
This is an alternative to #229 and builds on #248

This should probably be merged after #248

### CODE REVIEW

**Comment by BenMorganIO** [comment]
:+1:

What I did was I just made that existing migration empty.

**Comment by athal7** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Comment by jhawthorn** [comment]
> What I did was I just made that existing remove payment method environment column migration empty.

Just to clarify, we do need the environment to be specified here. Otherwise the migration which removes the payment method may remove this as the environment won't match.

**Pull request merged**
