### PR TITLE
Adjust after rubocop changes

### PR DESCRIPTION
**Pull request by elia**
## Summary

Rubocop 1.56 was released introducing some changes around `Rails/FindEach`.

Most changes are in specs and not-critical code, the few changes in core models seem innocuous or even improvements for some edge cases (e.g. a store with thousands of stock locations, which is admittedly unlikely anyway).

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by rainerdema — APPROVED** [review]
👍

**Comment by AdnanTheExcellent** [comment]
@elia I am upgrading to solidus 4.2 and was looking at this PR in the patch notes. I see that `all.find_each` is being called a few times, which I believe is an incorrect usage of `find_each`. The purpose of `find_each` is to avoid loading everything at once and do batches. Putting an `all` in front of it defeats the purpose of the method and is unnecessary. 

see https://edgeguides.rubyonrails.org/active_record_querying.html#retrieving-multiple-objects-in-batches

**Comment by tvdeyen** [comment]
@elia we have the same Rubocop warnings in v4.1 as well. Do you think it is ok to backport this PR to v4.1 as well? There shouldn't be any breaking changes in here, right?

**Comment by tvdeyen** [comment]
https://github.com/solidusio/solidus/pull/5484

**Comment by elia** [comment]
> you shouldn't need the `all` anymore.

@AdnanTheExcellent fully agree, can you please send a PR to fix that? I'd be happy to help merge it 🙏

**Pull request merged**
