### PR TITLE
Issue 2868: Products at multiple Stock Locations appear as unique variants

### PR DESCRIPTION
**Pull request by mayanktap**
# Description
This PR deals with the fix for the following issue:
https://github.com/solidusio/solidus/issues/2868

Ref # (issue)

# Checklist:

- [ ] [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines) are respected
- [ ] Documentation/Readme have been updated accordingly
- [ ] Changes are covered by tests (if possible)
- [ ] Each commit has a meaningful message attached that described WHAT changed, and WHY

### CODE REVIEW

**Comment by mayanktap** [comment]
Hi @spaghetticode ,

This is the new PR(replacement for https://github.com/solidusio/solidus/pull/2898) that consist the resolution for issue: https://github.com/solidusio/solidus/issues/2868
Please have a look and let me know in case of any discrepancy.

**Comment by spaghetticode** [comment]
@mayanktap I see there are three commits, two of them seems to me to be merge commits. Can you remove them? 

[This gist](https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa) may help if you have problems updating the code on your local fork.

**Comment by mayanktap** [comment]
@spaghetticode ,
Can we also proceed with making it a single commit by marking the two other commit as fixup? 
Otherwise I will proceed with this.

**Comment by spaghetticode** [comment]
@mayanktap I'm not sure I understand your last comment. the ideal situation for this PR is to have only one commit, [this one](https://github.com/solidusio/solidus/pull/3063/commits/f240b8ed90c9c55b8cc12ade801f658fd0c55ff0) which includes both the code and the spec. I think both code and spec can live in a single commit as they're minimal. 

The other 2 commits should be removed, as they are merge commits that don't belong to this PR.

I hope this helps :)

**Comment by mayanktap** [comment]
@spaghetticode ,

Done. Please check.

**Comment by mayanktap** [comment]
@jacobherrington ,
Can you please review the changes?

**Pull request merged**
