### PR TITLE
add a code of conduct

### PR DESCRIPTION
**Pull request by BenMorganIO**
Adds the contributor covenant.

http://contributor-covenant.org/

### CODE REVIEW

**Comment by tvdeyen** [comment]
:+1: 

Although I would replace all occurrences of "this project" with "Solidus", but it could also be like it's right now.

**Comment by CoralineAda** [comment]
:+1:

**Comment by BenMorganIO** [comment]
What we should put for `INSERT EMAIL ADDRESS`?

**Comment by gmacdougall** [comment]
I am not a fan of this for three main reasons.

1. I do not wish to use this open source project to make political statements
2. I don't believe this is solving a problem which currently exists on this project
3. I feel the responsibility for dealing with harassment should be left to more appropriate authorities, such as Github, or law enforcement

**Comment by mamhoff** [comment]
I'm :+1: on this one. I don't see any harm in a statement that commits us to be nice to people.

**Comment by cbrunsdon** [comment]
I agree with @gmacdougall and am :-1:

**Comment by moholtzberg** [comment]
:-1:

**Comment by CoralineAda** [comment]
@gmacdougall 

1) Since when is a diversity and inclusivity statement political?
2) Codes of conduct need to be in place *before* an incident arises.
3) Not all harassment is illegal or against ToS.

**Comment by stewart** [comment]
I am :+1: for reasons expressed by @mamhoff & @CoralineAda - adding a CoC can let people know that there is a baseline for how people are expected to treat each other in project discussions, and outlines a process for dealing with unwelcome/harassing behaviour when it arises.

**Comment by Dkendal** [comment]
:-1: for the same reasons as @gmacdougall.

**Comment by elia** [comment]
:-1: 

@gmacdougall is right, even many pro-CoC people agrees with him that's political:

screen shot 2016-01-04 at 19 14 41
screen shot 2016-01-04 at 19 15 01
screen shot 2016-01-04 at 19 18 53

**Comment by krainboltgreene** [comment]
I won't contribute without a COC.

**Comment by meh** [comment]
I won't contribute with a COC.

**Comment by CoralineAda** [comment]
@BenMorganIO I suggest closing this issue to all but project maintainers now that Elia and meh are here. They're bad players from the opal gate nonsense.

**Comment by meh** [comment]
@CoralineAda hey, so are you :panda_face:

**Comment by jeremyw** [comment]
A COC harms no one. :+1: to welcoming a diverse community.

**Comment by BenMorganIO** [comment]
@gmacdougall

1. I don't see how wanting a "harassment-free experience for everyone, regardless of level of experience, gender, gender, identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality." is a political statement. Its more of an invitation to contribute to our project and not fear to be subjected to any not so pleasant comments. Its a statement that we're a project that is :+1: for not only diversity, but in experiencing a positive and welcoming experience.

2. I think is a problem that occurs once in a while. As @CoralineAda has noted, there's @meh and @elia who are already creating problems in this PR. There's also the Slack channel where I'm sure one or two users have been booted for their comments. So, yes, I think this is needed. Instead of booting users, we can remove or hide their comments and forward them to the Code of Conduct. In essence: here's the rules, please behave. We want people to be a part of our community and we should work towards that.

3. I'm going to agree with @CoralineAda on what is and isn't against the terms of service and whether or harassing comments are or are not illegal.

---

@CoralineAda I'm not a maintainer nor apart of the Solidus core team, just an evangelist. If I was I would lock this PR to owners or, if it was possible, just ban @meh and @elia. I would also delete their comments as well. I think we'll need to wait on the core team to do that for us.

**Comment by CoralineAda** [comment]
@BenMorganIO It's disappointing to see that some Stembolt employees don't feel the same way. We'll see how this turns out.

**Comment by wstucco** [comment]
@krainboltgreene 
> I won't contribute without a COC.

honestly: why?

@CoralineAda 

Have you ever considered that there is someone on this planet that won't consider having or not having a COC an issue? (pun not intended! I swear!)   

I'm not a member of solidus community, but I'm an Opal user, and I think we should respect the decision of those that don't want to discuss this stuff as issues, they probably see issues as a way to signal a bug, a missing feature, a way to do things better, not for this.   
They made a decision and probably they know someone won't contribute because of that, and they accept the risk.  
Every decision they take will make someone in the community happy, piss off someone else but most of the users won't even notice the difference.

**Comment by mowings** [comment]
I won't contribute unless someone buys me waffles.

**Comment by krainboltgreene** [comment]
@wstucco Because I can't trust a contributor list that doesn't have the same level of standards for their community as rubygems.

> this stuff as issues

It's not an Issue, this is a Pull Request. For a file. Into the repository.

**Comment by wstucco** [comment]
@krainboltgreene

I understand that, but why?    
aren't they trustworthy already?   

> It's not an Issue, this is a Pull Request. For a file. Into the repository.

same reasoning applies.   

I'll stop here, didn't want to intrude, I'm just curious about this Coc thing, it can polarize the discussion in a way I don't see very productive, but that's just my opinion.

**Comment by krainboltgreene** [comment]
@wstucco Would you be OK with a library that didn't have tests? A project with no roadmap?

**Comment by BenMorganIO** [comment]
I'm going to agree with @krainboltgreene. A set of professional standards are set by rubygems and Bundler in OSS. If you create a new gem today, you'll get a Code of Conduct in your list of newly created files.

That's what really drove me to add this. Bundler adds one for you now. Spree has one. Solidus doesn't. I saw a tweet for @CoralineAda on the projects that were now using the Contributor Covenant. It reminded me how Solidus' OSS community can improve with staying up to date with what the ruby community was doing.

I think the ruby community takes a lot of value in being inviting and open. There's several projects before the days of the contributor covenant that had some form of a code of conduct such as Bundler. I think the Contributor Covenant was a step forward in building the community.

**Comment by wstucco** [comment]
@krainboltgreene

I could…   
it depends   
But that's not my point, my point is that people need a framework of trust when trust is not to be expected, if we already trust each other, why do we need a framework of trust?   

@BenMorganIO 
> I think the ruby community takes a lot of value in being inviting and open

In my experience, it already did before Cocs where implemented   
In my opinion it's because people in the community are welcoming, not because of rules

**Comment by krainboltgreene** [comment]
Then there's no problem having them written down...unless you think there
have been zero issues in the Ruby community?

**Comment by BenMorganIO** [comment]
@wstucco I would recommend reading the __Thanks__ portion to Bundler area. They build their's from JSConf and Fedora. The Contributor Covenant is merely supplying a standardized text file.

> Thanks to the JSConf Code of Conduct and Fedora Code of Conduct for inspiration and ideas.  Additional thanks to Contributor Covenant for the default code of conduct included in generated gems.

How would you feel if you had to hand write all your MIT License files? A lot of projects are adopting them. Its that instead of hand writing all of them, you have a simple file to work off of.

**Comment by wstucco** [comment]
@krainboltgreene 

exactly!
I have no reason to oppose, it's not my project   
I just don't think that projects that don't have "them written down" are less trustworthy, until proven otherwise    

@BenMorganIO 

licensing is a very different topic   
licenses are enforced by law, Cocs are not

**Comment by BenMorganIO** [comment]
@wstucco we appreciate your thoughts and will take them into consideration.

**Comment by j1696788** [comment]
I think that a lot of people or supportive of the code of conduct in itself but are very wary of the methods and the resulting atmosphere.

https://twitter.com/CoralineAda/status/684143225519472640

It's been 2 days, the discussion is ongoing and the the process is very civil, people are expressing opinions and arguing in a respectful manner and @CoralineAda is calling out Solidus publicly and associating it with Opal/Opalgate.

How is this not bullying? How is this professional? Why do need to publicly people who politely disagrees with you?

You know very well that this will leads to the usual mobbing of both supporters and detractors. It's always the same accounts who jump unto those kind of threads and extinguish any hopes of a productive discussion. You're as much responsible for this as a project leader is responsible for the comments of the core members.

People would be a lot more supportive of those issues is it was possible to discuss them without being browbeaten into submission.

**Comment by j1696788** [comment]
I think that a lot of people or supportive of the code of conduct in itself but are very wary of the methods and the resulting atmosphere.

https://twitter.com/CoralineAda/status/684143225519472640

It's been 2 days, the discussion is ongoing and the the process is very civil, people are expressing opinions and arguing in a respectful manner and @CoralineAda is calling out Solidus publicly and associating it with Opal/Opalgate.

How is this not bullying? How is this professional? Why do need to publicly people who politely disagrees with you?

You know very well that this will leads to the usual mobbing of both supporters and detractors. It's always the same accounts who jump unto those kind of threads and extinguish any hopes of a productive discussion. You're as much responsible for this as a project leader is responsible for the comments of the core members.

People would be a lot more supportive of those issues is it was possible to discuss them without being browbeaten into submission.

**Comment by BenMorganIO** [comment]
Hey everyone,

I don't think this was meant to be a discussion for the internet at large and we'll talk about it as a community. Closing until future notice.

**Pull request closed without merging**
