### PR TITLE
Use friendly_id ~> 5.1.0

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by gmacdougall** [comment]
Thanks for the PR! Is there a particular feature in 5.1 that you desired or is this a bump to stay current?

**Comment by bricesanchez** [comment]
I'm working to plug Refinery CMS 3.0 with Solidus 1.2.x, i need this version to be able to going forward and this is a bump to stay current. Are you ok use this version?

**Comment by magnusvk** [comment]
Rather than requiring 5.1.x, would it make more sense to relax to constraint to support both?

**Comment by bricesanchez** [comment]
I'm ok with that and you @gmacdougall ?

**Comment by jhawthorn** [comment]
We should probably be supporting `"~> 5.0"` and assuming that `friendly_id` supports semver correctly.

**Comment by gmacdougall** [comment]
Fine by me.

**Comment by jhawthorn** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
