### PR TITLE
Fixed Code Quality Issues

### PR DESCRIPTION
**Pull request by HarshCasper**
**Description**

Summary:

- Fix parameters being passed to expand_path
- Remove unnecessary boolean casts
- Fix operand order in the binary expression
- Add .deepsource.toml

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/solidus/).

DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

**Checklist:**
- [X] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [X] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
@HarshCasper You might want to double check what is being auto generated here, there is a lot of errors and not really making any sense to be honest.

**Review by jarednorman — CHANGES_REQUESTED** [review]
This PR contains autogenerated, clearly invalid Ruby and seems to do very little of value. It's primarily reordering arithmetic. I'm not interested in merging this or adding this tool based on this demonstration.

**Comment by aldesantis** [comment]
This doesn't seem to add value or make any sense at all. I'm closing the PR.

**Comment by jai-deepsource** [comment]
@peterberkenbosch @jarednorman @aldesantis On behalf of the team, my sincere apologies.

Our only motive with the developer outreach efforts is to fix code quality and security issues in open-source repositories and enable continuous analysis on the repository to keep the code quality in check as contributions to the repository grows. In this specific case, we made a mistake by suggesting incorrect improvements. We will make sure these issues won’t happen again in the future.

Jai
Co-founder, DeepSource.

**Pull request closed without merging**
