### PR TITLE
Deprecate and remove dashboard code

### LINKED ISSUE #4860: Deprecate and remove "dashboards" code
None of this provides any real value. Adding a custom dashboard is trivial and I really don't think we need a custom permission set and empty controller/view. 

- https://github.com/solidusio/solidus/blob/master/backend/app/controllers/spree/admin/dashboards_controller.rb
- https://github.com/solidusio/solidus/blob/master/backend/app/views/spree/admin/dashboards/home.html.erb
- https://github.com/solidusio/solidus/blob/master/core/lib/spree/permission_sets/dashboard_display.rb
- https://github.com/solidusio/solidus/blob/master/core/spec/models/spree/permission_sets/dashboard_display_spec.rb

### PR DESCRIPTION
**Pull request by nvandoorn**
As stated by jarednorman (in #4860):
> None of this provides any real value. Adding a custom dashboard is
> trivial and I really don't think we need a custom permission set and
> empty controller/view.

This is a rework of #5448 and fixes #4860.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by MadelineCollier — APPROVED** [review]
LGTM :)

**Comment by nvandoorn** [comment]
Pushed a new revision to remove a spec we don't need anymore.

**Comment by tvdeyen** [comment]
@nvandoorn I needed to update the required checks for Rails 7.2 support that now has been merged into `main`. Do you mind rebasing again?

**Comment by nvandoorn** [comment]
@tvdeyen Of course! Just pushed another revision.

**Review by tvdeyen — APPROVED** [review]

**Comment by tvdeyen** [comment]
Thanks 🎉

**Pull request merged**
