### PR TITLE
fix user picker when initializing ... #1352

### PR DESCRIPTION
**Pull request by simo163**
fix user picker when initializing rules users select in the edit protion page

### CODE REVIEW

**Comment by gmacdougall** [comment]
`Spree.ajax` is supposed to pass the api_key in the headers of the request. If that's not working, we should fix things on that side rather than forcing this method of authentication.

Can you please provide a more detailed description of what problem you're seeing?

**Comment by simo163** [comment]
It's strange, you're right Spree.ajax supposes to do it.

Doing this must reach the problem:
- create promotion
- add a rule of type User
- select some users and save
- reload the edit page
- can't load the users selected

I pass a [screeshot](http://img15.hostingpics.net/pics/585776promotionsuserrules.png)

**Comment by jeremyw** [comment]
I think I fixed the root cause of this issue here: https://github.com/solidusio/solidus/pull/1349

**Comment by gmacdougall** [comment]
I believe that does indeed fix the issue. Closing this PR.

**Pull request closed without merging**
