### PR TITLE
Introduce customization hook for create_proposed_shipments

### PR DESCRIPTION
**Pull request by richardnuno**
The change introduces a customization hook that allows stores to manipulate the shipments generated by Spree::Stock::Coordinator.

The particular use case for us here is to ensure a selected shipping method (selected by an admin or a user) is preserved even if create_proposed_shipments is called multiple times.

### CODE REVIEW

**Comment by magnusvk** [comment]
I think this looks cool. Interested to get some more eyes on it. Also the question on whether we want to centralize all the customization hooks ore leave them scattered around different places like this

**Comment by richardnuno** [comment]
@magnusvk had forgotten about the attempt to centralize the hooks, moved it over to Spree::Config

**Comment by jhawthorn** [comment]
I'm not sure about this as an extension point.

Is there a reason not to implement this as our default behaviour? `Shipment#refresh_rates` already has logic to keep the same shipping rate selected, it seems like we should do that same here.

**Comment by magnusvk** [comment]
We just chatted about this in the Solidus sync and we agreed that preserving selected shipping rates is what we'd want as default behavior, so rather than providing an extension hook for this let's just fix Solidus master to work that way. Is that good, Richard?

**Comment by richardnuno** [comment]
We also have validation in place to ensure that there is only one shipping method across all of the shipments, would that be something we want to bring over as well?

**Comment by richardnuno** [comment]
@jhawthorn talking to @magnusvk we realized that preserving the selected shipping rates would be a little more complex and time consuming than we'd hope. I filed issue https://github.com/solidusio/solidus/issues/347 so we can eventually work on supporting this but I do agree this extension point is awkward. Happy to jump on a hangout or something to talk through the challenges of preserving the shipping methods if you'd like but closing this PR for now in favor of the issue.

**Pull request closed without merging**
