### PR TITLE
Add initial shipments documentation for end users

### PR DESCRIPTION
**Pull request by kennyadsl**
**Description**
This PR reopens https://github.com/solidusio/solidus/pull/2784 which has been abandoned. 🙁

These are good, and already approved changes so I think we can resume that work.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message

### CODE REVIEW

**Comment by kennyadsl** [comment]
This is currently not linked anywhere in public guides pages. To try this out, this is visible into https://deploy-preview-3092--solidus-guides.netlify.com/users/settings/overview/ 

I think some paths have to be adjusted so I added WIP label.

**Comment by benjaminwil** [comment]
> This is currently not linked anywhere in public guides pages.

I have a PR open to address the need for multiple tables of contents in the guides: #2770.

I am happy to pick it up again and rebase it if y'all would consider merging it.

**Comment by kennyadsl** [comment]
@benjaminwil I’ve just started resuming exactly that PR! 😃

I’ve already rebased and added something, I’ll submit a PR soon and maybe you could help reviewing that one?

**Comment by kennyadsl** [comment]
@solidusio/core-team @benjaminwil Can I have a review here, please? 🙏

**Comment by kennyadsl** [comment]
@solidusio/core-team can I have another review here, please? 🙏

**Pull request merged**
