### PR TITLE
fix name for gateways from solidus_gateway

### PR DESCRIPTION
**Pull request by ccarruitero**

### CODE REVIEW

**Comment by kennyadsl** [comment]
@ccarruitero thanks for your contribution. What exactly this PR is fixing? Can you please post a more accurate description?

**Comment by ccarruitero** [comment]
@kennyadsl sorry for not provide a description.

Well, the reason of this PR is because after add `solidus_gateway` all new gateways are shown like `Payment Method` that is not very useful.

@tvdeyen yes, `human` method use I18n. But not sure if is the best way in this case.

**Comment by ccarruitero** [comment]
Seems to still returning `Payment Method` after add a locale
```
Running via Spring preloader in process 7273
Loading development environment (Rails 5.1.2)
2.4.1 :001 > payments = Rails.application.config.spree.payment_methods.sort_by(&:name)
 => [Spree::BillingIntegration::Skrill::QuickCheckout (call 'Spree::BillingIntegration::Skrill::QuickCheckout.connection' to establish a connection), Spree::Gateway::AuthorizeNet (call 'Spree::Gateway::AuthorizeNet.connection' to establish a connection), Spree::Gateway::AuthorizeNetCim (call 'Spree::Gateway::AuthorizeNetCim.connection' to establish a connection), Spree::Gateway::BalancedGateway (call 'Spree::Gateway::BalancedGateway.connection' to establish a connection), Spree::Gateway::Banwire (call 'Spree::Gateway::Banwire.connection' to establish a connection), Spree::Gateway::Beanstream (call 'Spree::Gateway::Beanstream.connection' to establish a connection), Spree::Gateway::BraintreeGateway (call 'Spree::Gateway::BraintreeGateway.connection' to establish a connection), Spree::Gateway::CardSave (call 'Spree::Gateway::CardSave.connection' to establish a connection), Spree::Gateway::CulqiGateway (call 'Spree::Gateway::CulqiGateway.connection' to establish a connection), Spree::Gateway::DataCash (call 'Spree::Gateway::DataCash.connection' to establish a connection), Spree::Gateway::Eway (call 'Spree::Gateway::Eway.connection' to establish a connection), Spree::Gateway::Linkpoint (call 'Spree::Gateway::Linkpoint.connection' to establish a connection), Spree::Gateway::Maxipago (call 'Spree::Gateway::Maxipago.connection' to establish a connection), Spree::Gateway::Migs (call 'Spree::Gateway::Migs.connection' to establish a connection), Spree::Gateway::Moneris (call 'Spree::Gateway::Moneris.connection' to establish a connection), Spree::Gateway::PayJunction (call 'Spree::Gateway::PayJunction.connection' to establish a connection), Spree::Gateway::PayPalGateway (call 'Spree::Gateway::PayPalGateway.connection' to establish a connection), Spree::Gateway::PayflowPro (call 'Spree::Gateway::PayflowPro.connection' to establish a connection), Spree::Gateway::Paymill (call 'Spree::Gateway::Paymill.connection' to establish a connection), Spree::Gateway::PinGateway (call 'Spree::Gateway::PinGateway.connection' to establish a connection), Spree::Gateway::SagePay (call 'Spree::Gateway::SagePay.connection' to establish a connection), Spree::Gateway::SecurePayAU (call 'Spree::Gateway::SecurePayAU.connection' to establish a connection), Spree::Gateway::SpreedlyCoreGateway (call 'Spree::Gateway::SpreedlyCoreGateway.connection' to establish a connection), Spree::Gateway::StripeGateway (call 'Spree::Gateway::StripeGateway.connection' to establish a connection), Spree::Gateway::UsaEpay (call 'Spree::Gateway::UsaEpay.connection' to establish a connection), Spree::Gateway::Worldpay (call 'Spree::Gateway::Worldpay.connection' to establish a connection), Spree::PaymentMethod::BogusCreditCard (call 'Spree::PaymentMethod::BogusCreditCard.connection' to establish a connection), Spree::PaymentMethod::Check (call 'Spree::PaymentMethod::Check.connection' to establish a connection), Spree::PaymentMethod::SimpleBogusCreditCard (call 'Spree::PaymentMethod::SimpleBogusCreditCard.connection' to establish a connection), Spree::PaymentMethod::StoreCredit (call 'Spree::PaymentMethod::StoreCredit.connection' to establish a connection)] 
2.4.1 :002 > payments.first.model_name.i18n_key
 => :"spree/billing_integration/skrill/quick_checkout" 
2.4.1 :003 > I18n.t('spree.billing_integration.skrill.quick_checkout')
 => "Quick Checkout" 
2.4.1 :004 > payments.first.model_name.human
 => "Payment Method"
```

**Comment by tvdeyen** [comment]
A fix is coming with #2107

We still need to add I18n translations if we want to display something else then humanized class names. But it know does not just show “Payment Method” anymore. 

Thanks for reporting! This is how release candidates and betas should work 👌🏻

**Pull request closed without merging**
