### PR TITLE
Don't show multiple active navigation items

### PR DESCRIPTION
**Pull request by graygilmore**
Closes https://github.com/solidusio/solidus/issues/1074

For details check out the [commit message](https://github.com/solidusio/solidus/commit/57bf4ab5b8bd52b428db07ea7cf1df09403c9c97).

### CODE REVIEW

**Comment by cbrunsdon** [comment]
Yea, this isn't amazing but I'm okay with it for now. We need to figure out how to do this better later.

**Comment by graygilmore** [comment]
I agree. I don't think this is the nicest change but it fixes a pretty bad visual bug. I've create [an issue](https://github.com/solidusio/solidus/issues/1120) for discussing making this area better.

**Comment by cbrunsdon** [comment]
(in case I wasn't clear before I was :+1: on this).

Kevin is also doing similar(ish) things right now with the breadcrumbs, might be a good idea to sit down tomorrow and talk some of this through IRL.

**Comment by tvdeyen** [comment]
Solves the problem, even if it's not perfect. :thumbsup:

**Comment by jhawthorn** [comment]
Thank you

**Pull request merged**
