### PR TITLE
Replace rubocop with standard

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes https://github.com/solidusio/solidus/issues/3872

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by jarednorman** [comment]
While I don't want to be the one pushing for a ton of formatting churn, I'm also concerned we're not going to get a huge amount of value from using the tool if it's configured such that so much of its functionality is disabled. Might need further consideration with @solidusio/core-team.

**Comment by tejasbubane** [comment]
>  I'm also concerned we're not going to get a huge amount of value from using the tool if it's configured such that so much of its functionality is disabled.

I agree and I realized this after completing the task. The whole point of using standard is to not have to configure anything. This more or less defeats the purpose.

**Comment by aldesantis** [comment]
I agree. If we move to Standard, we should probably just fix all the offenses. We're basically going to touch every single file in the codebase, but at least we'll only have to do it once.

What does the rest of @solidusio/core-team think?

**Comment by tvdeyen** [comment]
I like the idea of opinionated, non-config code formatters like rufo or standard. The thing is that every contributor would need to use it and we would still need to lint the code with rubocop, otherwise the rules wouldnt be enforced. Its a tricky situation. Unfortunately the code formatting is not build into the language.

**Comment by tejasbubane** [comment]
@tvdeyen 

>  we would still need to lint the code with rubocop, otherwise the rules wouldnt be enforced

you mean lint with `standard`?

> Its a tricky situation. Unfortunately the code formatting is not build into the language.

`standard` or `rubocop` is almost same as built-in formatters like `gofmt` or `rustfmt` right? Users need to install it, here they do it with `bundle install`. CI needs to run them to check for formatting. Or am I missing something?

**Comment by tvdeyen** [comment]
> @tvdeyen
> 
> > we would still need to lint the code with rubocop, otherwise the rules wouldnt be enforced
> 
> you mean lint with `standard`?

Standard uses rubocop, so yes. If we go with the default rubocop rules of standard (what I encourage us to do, otherwise it would not make sense to use it at all), we would use standard to lint as well. 👍🏻 

> 
> > Its a tricky situation. Unfortunately the code formatting is not build into the language.
> 
> `standard` or `rubocop` is almost same as built-in formatters like `gofmt` or `rustfmt` right? Users need to install it, here they do it with `bundle install`. CI needs to run them to check for formatting. Or am I missing something?

Unfortuantely its not. The people would still need to install it and configure their editor to "format on safe" with the tool that we force on them. They might have it disabled or even worse configured differently.

The idea of automatic code formatters is great, but unless build into the language from the beginning, you are screwed.

Standards

**Comment by tvdeyen** [comment]
Take the double-quotes rule as example. Prettierrb has it changed from the Prettierjs default to `false` (to enforce single quotes), just because it is more common in Ruby code to use single quotes. This violates the whole idea of prettier.

The idea was to not fight over code formatting rules anymore, and use a tool for that. Now people fight over the rules. Its ridiculous.

Imagine the following situation:

A dev has configured its editor to use `prettierrb` to format `.rb` files on safe, now wants to contribute to solidus and is enforced to use double-quotes. Giving them a bad time fighting its own editor just to fulfill our rules. Not very welcoming.

The only unobtrusive thing I could imagine is to automatically run `standard` on the CI as an after commit hook or something.

**Comment by jarednorman** [comment]
On our projects we usually use our autoformatters with a tool like `lint-staged` and `husky` to provide automatic and `git add -p`-friendly commit hooks that autoformat everything seemlessly. That's the ideal, I think.

**Comment by bogdanvlviv** [comment]
It is lovely to see how we use rubocop in rails.

- We disable all default cops https://github.com/rails/rails/blob/main/.rubocop.yml#L10 and only enable those ones that reflect our style guide in the project.
- The rubocop.yml file read great https://github.com/rails/rails/blob/main/.rubocop.yml#L10. By reading it we can learn about the style Rails repo uses.

One example of how rubocop gives a hand while improving the codebase:

We noticed that we dropped support for < Ruby 2.7 so that we could use `filter_map` gem to speed up some lines of the codebase. https://github.com/rails/rails/pull/42053.  With rubocop, we were able to catch all the places we could improve by `filter_map` and make sure that we would use this method where possible instead of  `map+compact`, or something in the future, and never return to this topic again.
https://github.com/rails/rails/commit/bbbc861f717689a0a28f031fe2176d0f8a6b07c7.
We might use rubocop in a similar way in solidusio/solidus. WDYT?

P. S.There are more interesting samples https://github.com/rails/rails/pulls?q=is%3Apr+rubocop+is%3Aclosed+author%3Akamipo

**Comment by kennyadsl** [comment]
@bogdanvlviv I really like the approach proposed. We can gradually introduce rules based on the feedback we provide in PR reviews and use Rubocop as a tool to refactor code over time. 👍

**Comment by jarednorman** [comment]
I more in favour of the set it and forget approach of Standard. Continuing to maintain a rubocop configuration, especially across the extension ecosystem (though I know we could rely on solidus_dev_support) doesn't seem like a good use of maintenance effort to me. That said, if there were some rules we wanted to enable on top of the Standard defaults, like ones that deter people from doing insecure things, I'm open it.

**Comment by spaghetticode** [comment]
I'm not really in favor of basically touching every single file in the codebase for cosmetic reasons (or at least debatable reasons). 

While I personally like standard more than rubocop (but in general I'm not a fan of code linters, at least in the ruby ecosystem), I think the change would be pretty invasive and pollute the git history. And there's no guarantee it would be final, in a few years we may be still here evaluating the new best linter and debating if we should change all the files again.

**Comment by jarednorman** [comment]
The concern about touching every file is fair; it's not ideal, but I don't consider it a dealbreaker if what we get in exchange for a one-off formatting commit is to stop worrying about this style formatting stuff.

I don't agree with your concern about further churn down the road. The problem with maintaining a Rubocop config (across the whole Solidus ecosystem) is that Rubocop continues to add, remove and change rules, which requires us to evaluate them and decide whether to integrate with (and at least keep up with changes to rules we use.) Using Rubocop is like agreeing to debate style forever.

The whole point of Standard (especially now that it has hit v1.0) is that they've done the work to debate the preferences of the Ruby community and have adopted a reasonably conservative set of sensible defaults. If we adopt it, we agree to basically never do this again barring some kind of catastrophe, otherwise I agree it's not worth changing.

While I don't like formatting churn standard'll cause, only one of these tools purports to offer the opportunity to just use the tool's default settings and never worry about this again.

**Comment by jarednorman** [comment]
And to be clear, I'm still not 100% sure we should do this, I just really don't want to maintain a Rubocop config. It just seems like a waste of time when there's a "set it and forget it" alternative.

**Comment by tvdeyen** [comment]
@jarednorman 💯 agree. Well said.

**Comment by aldesantis** [comment]
I also agree with @jarednorman. Going with Standard is not just another coding style change - it means not having to worry about coding style ever again, which is a very alluring idea.

**Comment by jarednorman** [comment]
@tejasbubane Thanks for your patience with our back and forth on this issue.

After a Core Team discussion we've decided that _for now_ this change would be a bit too disruptive. It would mean everyone would have to rebase all their open PRs, we'd have to update the whole extension ecosystem to match, and it would generate a lot of noise in the history of all the files in the project.

I think we'd all prefer to be using Standard (and without a bunch of rules disabled), but the benefits don't outweigh the disruption. We think there might be a moment down the road where some other large, disruptive change gets made where we'd sneak this one in too just to get it all over with, so we'll cross that bridge when we come to it.

**Pull request closed without merging**
