### PR TITLE
Checkout email input field should use email_field

### PR DESCRIPTION
**Pull request by notapatch**
- on frontend checkout/edit
 - mobile users will have a virtual keyboard that now includes
   an @ symbol.
 - fallback for none HTML 5 browsers is to text type

### CODE REVIEW

**Comment by graygilmore** [comment]
Makes sense to me! 👍

**Comment by jhawthorn** [comment]
I'm not sure why CircleCI refuses to build this, I have sent them a support request.

**Comment by swcraig** [comment]
I [rebased this and opened a new PR](https://github.com/solidusio/solidus/pull/2166) in which CircleCI passed.

**Comment by cbrunsdon** [comment]
I think we can write this up to a circleci blip, I don't care if we merge this one or #2166

**Comment by notapatch** [comment]
Rebased and updated the commit message improvements from @swcraig, thanks. 

I am hoping this will be my first Solidus contribution. I won't lie anything else will result in [disappointed cockatoo](https://www.youtube.com/watch?v=6OQ_i0ecIyU) reaction and you don't want to go into a weekend with that on your conscious.

**Pull request merged**
