### PR TITLE
Add store credit to available payment methods.

### PR DESCRIPTION
**Pull request by adammathys**
Otherwise, attempting to edit it in the admin won't work. Since it'll try to switch the provider to something else that won't have the same preferences.

### CODE REVIEW

**Comment by athal7** [comment]
is this for editing the payment method itself or for adding payments? usually it is not preferred to add store credit payments manually since they are auto-added, but if it is for configuration then :+1:

**Comment by adammathys** [comment]
It's for configuration. Otherwise when you try to update it in the admin it'll mess everything up. It will set the type to the first provider in the list but not clear any of the preferences. (Resulting in 5XXs on all subsequent attempts to view or edit the payment method.)

**Comment by Senjai** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
