### PR TITLE
Fix payment#payment_method for deleted records

### PR DESCRIPTION
**Pull request by jhawthorn**
Take two of #1190, which was reverted due to a broken test

### CODE REVIEW

**Comment by bbuchalter** [comment]
I don't see any difference between this and #1190 - what changed?

**Comment by jhawthorn** [comment]
Change was `payment.number` vs `payment.amount` :disappointed_relieved:

**Comment by jordan-brough** [comment]
👍 

@jhawthorn just curious - you're saying the old spec was flaky?  If so, what made `number` flaky and `amount` reliable?

**Comment by jhawthorn** [comment]
@jordan-brough `number` isn't displayed on the final page at all. So it was less "flaky" and more "entirely broken" I didn't notice because CircleCI decided not to test pull requests authored by me, so it actually wasn't being tested.

Hound made it look like it passed

**Pull request merged**
