### PR TITLE
Revert "State lock version on orders"

### PR DESCRIPTION
**Pull request by adammathys**
This reverts commit 3b2fc619ced8424289f24faf878c0c708e40ce3d and subsequent changes related to it.

### CODE REVIEW

**Comment by jordan-brough** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Comment by jhawthorn** [comment]
:+1:

**Comment by mtomov** [comment]
btw, why was this change necessary? Just curious about the reason.

**Comment by magnusvk** [comment]
Solidus has a different order locking system; this duplicated that, and in an incomplete way IIRC.

**Comment by mtomov** [comment]
👍 I saw an OrderMutex class, which must be it.

**Comment by magnusvk** [comment]
Yup, that's exactly right.

**Pull request merged**
