### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by tanmay3011**
1.) Use #blank? which provides the  same functionality provided by the combination of #nil? and #empty?.

2.) Added missing translation of back_to_return_authorizations_list.

3.) Use Time.current/Time.zone.now instead of Time.now in order to use application time zone.

4.) Removed deprecation of passing a nested array to ActiveRecord finder methods by flattening the array

5.) Remove #number= writer method provided by attr_accessor since it's already being overridden on line 66

### CODE REVIEW

**Comment by tvdeyen** [comment]
Thanks for your contribution.

It would really help the reviewers, if you could tell them what exactly do you refactor and why. 

Please see [the contribution guidelines](https://github.com/solidusio/solidus/tree/master/CONTRIBUTING.md) in order to write good commit messages and pull requests. 

Thanks again.

**Comment by tanmay3011** [comment]
@tvdeyen Added a comment so that you can get what exactly I have done and why

**Comment by BenMorganIO** [comment]
:+1:

**Comment by jhawthorn** [comment]
Other than tiny request this looks great :+1:

**Comment by cbrunsdon** [comment]
Okay! Looks good to me, other than hawth's request in #a272fee.

Also, when you have a minute, you'll likely want to read though: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Thanks for the cleanups though.

**Comment by athal7** [comment]
:+1:

**Comment by tanmay3011** [comment]
@jhawthorn Added comment!

**Comment by jhawthorn** [comment]
Great! Thank you @tanmay3011.

**Pull request merged**
