### PR TITLE
Fix ActionMailer preview loading

### LINKED ISSUE #3898: Deprecation Warning pertaining to Mailer Previews being loaded from an app which loads the Solidus engine
It appears that the way in which Solidus loads ActionMailer previews from a containing app during initialization is today causing a deprecation warning, but in a future version of Rails will be a hard error.

**Solidus Version**:
2.11.3

**To Reproduce**
Create an app which loads Solidus. Ensure that the app has its own ActionMailer previews and then attempt to run the app server/console. Tail the development log to see the following:

DEPRECATION WARNING: Initialization autoloaded the constants ...

Included in this list are MailerPreviews from the containing application 

**Current behavior**
A deprecation warning is presented during boot

**Expected behavior**
No such deprecation warning

**Desktop (please complete the following information):**
 - OS: OSX 11.1
 - Browser N/A
 - Version N/A

### PR DESCRIPTION
**Pull request by aldesantis**
**Description**

This fixes #3898, by moving the loading of the app's previews (and our own) to an `after_initialize` block, which gets rid of the deprecation warning about constant loading during app initialization.

I also managed to write a test that verifies that both the engine's and the app's previews are properly loaded. I had to enable preview loading in `Rails.env.test?` as well in order for the test to pass, but I think that won't be a problem.

Btw, it seems like we'll be able to get rid of this hack if/when https://github.com/rails/rails/pull/31595 gets merged.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)
- [x] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by jarednorman** [comment]
Is this seeking to resolve #3898?

**Comment by PeteTheSadPanda** [comment]
I believe it would as it would push load_previews' descendants call into runtime and out of intializer time which results in autoloading of the Preview classes.

**Comment by aldesantis** [comment]
@jarednorman @PeteTheSadPanda yep, this solves #3898. It needs some more love — mostly, I want to implement some kind of caching/memoization and give that anonymous module its own place — but I've tested it in a real Solidus store and both Solidus' and the store's previews are loaded correctly.

**Comment by PeteTheSadPanda** [comment]
Given how frequently this gets called, I'm not sure caching/memorization is really needed. This call primarily gets called when rendering /rails/previews which itself does some level of caching by short circuiting is descendants are populated, so really you might only be requiring Solidus previews.

I'm not advocating against your proposal which is fine, I'm just stating that if it proves too much a pain it wouldn't be a blocker (to me). I believe (but am not certain) that any subsequent calls to the same file via require_dependency would be cached assuming the constant is still in memory and hasn't been unloaded due to it being changed.

**Comment by aldesantis** [comment]
This should be ready for a review!

**Review by kennyadsl — APPROVED** [review]
👍 Thanks Ale!

**Review by spaghetticode — APPROVED** [review]
@aldesantis thanks!

**Comment by kennyadsl** [comment]
Failing specs already addressed, merging anyway!

**Pull request merged**
