### PR TITLE
Remove extraneous code

### PR DESCRIPTION
**Pull request by jordan-brough**
This should be equivalent afaik.  Except for that fact that it's not modifying `params` (which seems like a good thing)

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1:

**Comment by Senjai** [comment]
:+1:

**Comment by athal7** [comment]
is this now going to ignore params entirely?

**Comment by jordan-brough** [comment]
@athal7 yeah, unless I'm reading this wrong it was only permitting `extra_order_params.keys` anyway, so that's all that would be let through anyway

**Comment by athal7** [comment]
Yea I think you're right. 👍. Just be careful with this, I think it might be an extension point that at least we use.

**Comment by athal7** [comment]
A poor extension point, but an extension point nonetheless

**Pull request merged**
