### PR TITLE
Add some admin hint tooltips

### PR DESCRIPTION
**Pull request by mtylty**
As requested in #1266, I've added the hint tooltips commented by @mamhoff.

### CODE REVIEW

**Comment by Mandily** [comment]
Can we be consistent with the use of capitalization and use a capital letter after the colons in the 'default' messaging? I could be swayed to use all lowercase if someone thinks that's better. What I'm after here is consistency.

**Comment by jhawthorn** [comment]
Thank you. Other than Amanda's suggestions this looks great :+1:

**Comment by mtylty** [comment]
@Mandily I've asked myself the same question about capitalization.

I've ended up with a mixed solution because I've used capitalization whenever the default was the exact string (i.e. `Any Country` appears in the select dropdown) and lowercase to follow the example of the `checked` default provided in aaef78d835444dd669c83ba0a49e88508892e150.

I'm concerned with consistency as well. Should I change the lowercase defaults to uppercase? It makes more sense to me to display the exact string when the default is part of the available choices.

**Comment by Mandily** [comment]
@mtylty Instead of being consistent with the inconsistency, how about we clean up the original strings if they need it too? Capitalization is related more to 1. whether the word is a proper noun and 2. the placement of the word in a sentence, title etc. I realize there's some less than desirable things in the admin right now, but I don't think we need to continue those bad habits in the meantime of cleaning them up.

**Comment by gmacdougall** [comment]
:+1:

**Comment by mamhoff** [comment]
👍

**Comment by jhawthorn** [comment]
Thanks @mtylty

**Pull request merged**
