### PR TITLE
fix_display_orders for taxon

### PR DESCRIPTION
**Pull request by Perkir**
Althought i use  gem solidus_i18n, Display Order not work.
I think this commit fix it.

### CODE REVIEW

**Comment by kennyadsl** [comment]
@Perkir Hello, what do you mean with "Display Order not work"? Can you please post steps to reproduce this issue or at least a screenshot. 
Also, in the code you are linking to the admin products page but with the "Orders" label, maybe you want to use `Spree::Product` instead?

**Comment by Perkir** [comment]
Hello! 
I mean options in admin panel. 
Products -> Display Order

You're right i need to use Spree::Product.

**Comment by Perkir** [comment]
nomethoderror at ru admin taxons 2017-04-02 22-06-20

This screen demonstration this bug

**Comment by kennyadsl** [comment]
Can you please share which language (with `solidus_i18n`) and which solidus version are you using?

**Comment by Perkir** [comment]
1.Language from  solidus_i18n its "ru"
2.Solidus version its 2.1.0

**Pull request merged**
