### PR TITLE
[Admin] Introduce RMA reasons creation capability

### PR DESCRIPTION
**Pull request by forkata**
## Summary

This PR completes the first part of https://github.com/solidusio/solidus/issues/5808, which is to add a new UI component for creating RMA reasons.
In a future PR we will build on this to allow updating RMA reasons through the same UI component.

### How

* Add new UI component for creating RMA (return) reasons
* Added create action for return reasons admin controller

| Create UI |
|--------|
| Screenshot 2024-07-17 at 10 31 28 AM | 

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by spaghetticode — APPROVED** [review]
@forkata thanks!

**Comment by forkata** [comment]
@spaghetticode I have a question re: the code coverage here, I don't see any controller specs in this project, should we be trying to get code coverage through feature specs for this change? I don't mind adding a test for the failure scenario as well, just not sure what conventions we're trying to establish?

**Comment by spaghetticode** [comment]
> @spaghetticode I have a question re: the code coverage here, I don't see any controller specs in this project, should we be trying to get code coverage through feature specs for this change? I don't mind adding a test for the failure scenario as well, just not sure what conventions we're trying to establish?

We don't have much documentation on this topic yet, something has been written [here ](https://github.com/solidusio/solidus/blob/main/admin/docs/components.md#testing). So far, I see most of the feature files have only happy paths, with some exceptions - but maybe that's because failure paths don't apply to many of them. I personally think we should cover failure scenarios as well, which I tried to add to some of my PRs.  But of course we can discuss and re-evaluate on how we'd like to proceed anytime, so if you have any suggestion, feel free to

**Comment by forkata** [comment]
@spaghetticode That makes sense on the testing side, I will be working on the update ability here so I can add to the feature test coverage.

On a separate note, did you intend to close this PR without merging it 😅

**Comment by spaghetticode** [comment]
@forkata I'm sorry, I don't know what happened it seems I clicked the wrong button... it's probably time I start wearing some glasses 😅 . I've restored the PR.

**Comment by kennyadsl** [comment]
Hey @forkata, first of all thanks for this PR! Are you still working on this? If you don't have time to continue the PR, I think we can merge it as is, it's still a great addition, and you can take your time to add the rest of the specs later. Please, let me know!

**Comment by MadelineCollier** [comment]
@kennyadsl @forkata I'm also happy to take this one over the finish line if need be! I can put up another PR with this existing creation capability, and add another PR for the modification.

**Comment by MadelineCollier** [comment]
I have ported the creation logic over to a new branch, added some request specs to fix the Codecov complaints, and also finished off the modification logic, so I'm closing this in favour of https://github.com/solidusio/solidus/pull/5829 but thank you @forkata @kjriga for your work so far and for making it easy for me to finish this one off! :)

**Pull request closed without merging**
