### PR TITLE
Improve CHANGELOG for 1.3 release

### PR DESCRIPTION
**Pull request by jhawthorn**

### CODE REVIEW

**Comment by jrochkind** [comment]
> Made Spree::Order validate :store_id

Is this being removed from 1.3 then?

Is `master` the place where I get the latest will-become 1.3, it doesn't have it's own branch or anything (and does this mean we have no way to merge PR's that are _not_ intended for 1.3, since it's already been feature-frozen, but are good to merge for a future release?)

I have an app that began on spree 2.4, and I'm working on updating it to solidus -- i want to go all the way to 1.3 before deploy, since 1.3 is so imminent. Obviously won't deploy until 1.3 is actually released in such a case. But for my upgrade work, should I be updating to master and targetting that?  (Already did a bunch of work to deal with required store on order, heh). 

Thanks!

**Comment by jhawthorn** [comment]
> Is this being removed from 1.3 then?

I believe that validation should stay.

I think this was clarified in slack. The [1.3 branch](https://github.com/solidusio/solidus/tree/v1.3) will be the 1.3.0 release. To make changes to it we make PRs against master and cherry-pick them back.

Since there is already a release candidate out, the changes to that branch before release should be minimal.

**Comment by jrochkind** [comment]
Thanks!  I just mis-read the diff and thought the CHANGELOG was removing notice of this. I see the notice is somewhere else, although doesn't specifically talk about validations, just more broadly that orders need a store. 

The validation is one of the largest things I'm dealing with updating an old legacy app from solidus 1.2 to 1.3, largely but not exclusively just issues of test setup. Def good to be in the changelog.

**Comment by mamhoff** [comment]
👍

**Pull request merged**
