### PR TITLE
Restrict store credit updating (v2)

### PR DESCRIPTION
**Pull request by magnusvk**
This supersedes #148 as I don't have push access to Richard's fork and he's out on vacation. Boo Github permissions.

### CODE REVIEW

**Comment by magnusvk** [comment]
@jhawthorn 73fcf04 addresses your comment re: using JSON rather than evaluating server-generated Javascript. Can you take another look over this to see if this is ready to get a thumbs-up? Also already got a thumb from @gmacdougall in the original PR at https://github.com/bonobos/spree_store_credit_payment_method/pull/67, though there's been more changes since.

Also @athal7 want to take another look? This is a blocker for us before we can go live on Solidus, so trying to get it merged. :)

**Comment by athal7** [comment]
i trust that this works since it's good for us from the original extension PR

**Comment by magnusvk** [comment]
@athal7 @jhawthorn Good points. Updated.

**Comment by jhawthorn** [comment]
:+1:

**Comment by athal7** [comment]
:+1:

**Pull request merged**
