### PR TITLE
[Admin] Add filter feature for stock movements

### PR DESCRIPTION
**Pull request by jacquesporveau**
**Description**

#3666 

Screen Shot 2020-06-23 at 10 45 01 AM

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)
- [x] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by jacquesporveau** [comment]
@seand7565 @kennyadsl 

This one has been sitting for a bit now. Pinging for reviews. ❤️

**Comment by aldesantis** [comment]
Running the CI again since the failure seems unrelated to the changes.

**Comment by spaghetticode** [comment]
@jacquesporveau can you please rebase with master? This build is failing due to an annoying flaky spec that was fixed recently.  After the rebase your build should become green 💚 ... thanks 🙏

**Comment by jacquesporveau** [comment]
@spaghetticode I've rebased and there is still a failing check. I think this one has been failing on all PR's for some time now. Let me know if you'd like anything else from me 👍

**Comment by spaghetticode** [comment]
@jacquesporveau yes that's expected, the Rails master build is red due to an external dependency [issue](https://github.com/activerecord-hackery/ransack/issues/1127). Thanks for rebasing 🙏

**Pull request merged**
