### PR TITLE
Avoid changing method visibility when deprecating a method

### PR DESCRIPTION
**Pull request by jordan-brough**
`ActiveSupport::Deprecation::MethodWrapper#deprecate_methods` changes method
visibility to `public`.  This seems unintentional and I will submit a PR to
Rails to see if that can be updated.

For the meanwhile, this update changes method visibility back to the original
visibility. It's a bit more convoluted than might be expected because
ActiveSupport uses `Module.prepend` to override the original method, so we can't
just write `private :some_method` because that only affects the original method,
whose visibility has not been changed.

If people think it's worth creating a helper for this let me know and I will do so.

### CODE REVIEW

**Comment by jordan-brough** [comment]
I've submitted a Rails PR here: https://github.com/rails/rails/pull/31433 to fix this in ActiveSupport.

**Comment by gmacdougall** [comment]
Thanks for finding this Jordan.

I prefer to leave this as is and update to a new rails version when this is fixed upstream.

**Comment by jordan-brough** [comment]
@gmacdougall I think it's worth going ahead and fixing this.  My fix was only merged into Rails master and Rails v5.2 is already in beta so I imagine it'll be a good while before that trickles back to Solidus.  It's good to have correct method visibility for the apps using Solidus imo, even for deprecated methods.

**Comment by jhawthorn** [comment]
Nice catch.

> My fix was only merged into Rails master and Rails v5.2 is already in beta so I imagine it'll be a good while before that trickles back to Solidus

I _think_ rails master is still tracking 5.2, so it shouldn't be too long.

Alternatively, we could use `Spree::Deprecation.warn` explicitly within the private method, which avoids the slight strangeness of `instance_method(...).owner.send(:private, ...)`. I am fine either way.

**Comment by jordan-brough** [comment]
> we could use `Spree::Deprecation.warn` explicitly within the private method

Great point, I'll update with that 👍

**Comment by jordan-brough** [comment]
@jhawthorn @gmacdougall I removed a broken deprecation no `Spree::PaymentMethod#provider_class` and updated the remaining ones to use `Spree::Deprecation.warn`.  Look good?

**Pull request merged**
