### PR TITLE
Chore/make admin more responsive

### PR DESCRIPTION
**Pull request by jacobherrington**
This PR adds Bootstrap breakpoints to most of the forms in the admin area. 

A good next step would be making the sidebar animated on mobile resolutions, but that's a more drastic change.

This probably needs to be squashed if everyone is okay with the change.

### CODE REVIEW

**Comment by jacobherrington** [comment]
@tvdeyen add a viewport tag. Should be useful if we want to make admin mobile friendly.

**Comment by kennyadsl** [comment]
@jacobherrington please take a look at [this issue](https://github.com/solidusio/solidus/issues/666) and [this closed PR](https://github.com/solidusio/solidus/pull/1718) also. We started some work for the collapsible menu but, the way it was required to be, it turned out to be a big change.

At the moment I think we need something more simple, like removing the ability to expand/reduce the menu in mobile/desktop.

**Comment by jacobherrington** [comment]
@kennyadsl Ah, well this PR isn't doing that quite yet. Instead this PR just makes some of the forms collapse on smaller window sizes. 

I will read through those threads if I get to a sidenav PR! Thanks for the info!

**Comment by tvdeyen** [comment]
@jacobeubanks sorry, my bad. Now with the meta tag the admin does not scale any more on small devices. This is an issue for all tablet users, as long as we don't collapse the sidebar as well. I think we should fix that sidebar problem before we take care of the rest.

**Comment by jacobherrington** [comment]
Sounds good @tvdeyen. I will look into that!

**Comment by jacobherrington** [comment]
Closing this until we have a resolved #2961, then I will revisit a more complete version of this.

**Pull request closed without merging**
