### PR TITLE
Remove select2 styling

### PR DESCRIPTION
**Pull request by jhawthorn**
I believe the default styling of select2 is superior.

Before:

After:

If we ever upgrade to select2 4.0, the default style should integrate even better

### CODE REVIEW

**Comment by mamhoff** [comment]
I disagree, for two (admittedly nitpicky) reasons: 
1. The typography is somehow strikingly different and worse-looking than in the existing styling (it's a different font, and it's positioned in an awkward three-pixels-off way). 
2. It's be the first instance of pseudo-3D-gradients in the interface. The 4.0 version is better in terms of the background, but still has the typography issues. 

The current style, however, is not great either. Do you think the default styles are a better starting point for someone to style this properly?

**Comment by tvdeyen** [comment]
:-1: on select2 3 default style (the rounded gray look does not fit the rest of the UI)
:+1: on select2 4 default style

**Comment by cbrunsdon** [comment]
I'm sad we'd be losing variables that would be easy for us to customize on a store-by-store-basis

e.g: ```$color-sel-disabled-bg``` and friends

**Comment by jhawthorn** [comment]
Fair enough. I prefer the slightly our of place style to the blue because IMO we've allocated that colour of blue to buttons, where these are form inputs.

I'll try this again after upgrading to select2.

**Pull request closed without merging**
