### PR TITLE
Move legacy guides to a separate repository

### PR DESCRIPTION
**Pull request by aldesantis**
**Description**

The legacy guides have been moved to https://github.com/solidusio/legacy-guides, because they are going to be replaced by the new guides hosted at https://github.com/solidusio/edgeguides pretty soon.

The https://guides.solidus.io site has been updated to point to the new repository.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by aldesantis** [comment]
Please note that Netlify checks are only failing because I've moved the build to Cloudflare Pages.

**Review by waiting-for-dev — COMMENTED** [review]
Lovely! :heart: 

We can use this PR to remove a couple of references to the old guides in `/guides`:

1. [Stoping CI for guides-only changes](https://github.com/solidusio/solidus/blob/master/.circleci/config.yml#L43).
2. [Ignoring `node_modules` directory within `guides` for rubocop](https://github.com/solidusio/solidus/blob/master/.rubocop.yml). 

For 1., we might want to keep it if the new guides will be also placed in `guides`, although it has some problems (like stopping a build for a multi-commit PR that modifies more than the guides but only the guides in the last commit).

**Comment by aldesantis** [comment]
@waiting-for-dev addressed your suggested changes, and I have also took the chance to update the PR template: it now points to the new guides repository, and I have updated a couple more items for coherence.

As for the CI, I have decided against keeping the documentation in this repo: because the new guides are versioned, and the content for all versions is in the same branch (just in different directories), it would lead to a very weird situation where we have the documentation for all Solidus versions in the `master` branch of `solidusio/solidus`, which would make it weird to navigate the documentation from GitHub and/or to update the documentation for older versions.

I have explored the possibility of using the `solidusio/edgeguides` repo just to host the Docusaurus app, and have it read the actual content of the guides from the different branches in `solidusio/solidus`. [It works](https://github.com/solidusio/edgeguides/commit/20f499170bb19efd255ea2cfd744ab1c37239b4d#diff-c1065842a616babf160e1ce43ea67102db0dc93c96781019add7216ec20596cc), but it creates a bunch of additional issues/gotchas with deployments and preview environments. I think it's just too big of a headache at this point, and we can explore alternative solutions in the future.

**Review by jarednorman — APPROVED** [review]

**Comment by aldesantis** [comment]
CI failure seems unrelated, merging.

**Pull request merged**
