### PR TITLE
CI: Skip install_solidus check on non-current version

### PR DESCRIPTION
**Pull request by tvdeyen**
## Summary

The installer always uses the current released minor version (4.2 time writing this), but the check runs on all pipeline runs, wasting CI time and precious resources. Also it fails anyway, because of conflicting dependencies.

So, we only run the check on main and latest minor now.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by tvdeyen** [comment]
Oh boy. Circle CI syntax is the most confusing ever. Maybe someone with a deeper knowledge can fix this? /c @waiting-for-dev @elia

**Comment by tvdeyen** [comment]
Ok, I figured it out, but we need to enable triggers in order to determine if the event send from github is a pull request event so we can trigger the solidus installer build for pull request to the `main` or `v4.2` branches.

**Comment by tvdeyen** [comment]
I know configured it such that it only runs on main and v4.2 branches, but this does not include pull requests to these branches. Boy, I would like us to use github actions instead of circle ci...

**Review by kennyadsl — APPROVED** [review]
It makes sense, this assumes that no one will install Solidus starting from older versions, and I think it's a safe assumptions.

**Comment by tvdeyen** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v3.4|[](https://github.com/solidusio/solidus/pull/5497)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
