### PR TITLE
(api) don't allow customers to update completed orders

### PR DESCRIPTION
**Pull request by carchrae**
don't allow customers to update a completed order (eg, line_item adjustments, etc)

see https://github.com/solidusio/solidus/issues/546

### CODE REVIEW

**Comment by athal7** [comment]
I think this is a great change, I'm wondering if there are other places we want to catch as well (e.g. line item creation)

**Comment by carchrae** [comment]
thanks @athal7 

that is a good point about other places this could happen via api endpoints.  certainly some more tests for these cases would be useful.  payments, for example.

i checked the failing tests; it seems that the checkouts controller does test for complete (but in the controller), and, somewhat strangely, returns 200 and the order, if the order is already complete (instead of unauthorized or some error) https://github.com/solidusio/solidus/blob/master/api/spec/controllers/spree/api/checkouts_controller_spec.rb#L390

note however, that the order controller does not do this check.

i wonder why can can was not used for the checkout controller check.  

the other failing test looks broken.  it updates the order to complete, then tries to transition: https://github.com/solidusio/solidus/blob/master/api/spec/controllers/spree/api/checkouts_controller_spec.rb#L383

**Comment by cbrunsdon** [comment]
I have been thinking about this one for the last few day and I don't think I like the idea of stopping :update's to orders by default at the cancan level.

There are a number of circumstances I think "updating" an order makes a lot sense: changing/fixing addresses, adding assets, some stores even allow changing shipping before a point in time (all of which I think are very clear use cases).

I'd rather block on a more fine-grained level, like stopping line item updates if its complete rather than all updates to an order, thoughts?

**Comment by carchrae** [comment]
@cbrunsdon - just's be clear;  you think it is a good idea for a customer to update their own shipping address?  what if you've shipped it?  

this is not stopping by default, it is stopping non-admins from updating a completed order.  sorry if that is not clear.

**Comment by cbrunsdon** [comment]
@carchrae Aye, I follow.

But `order.completed?` doesn't mean "hey this is shipped and shouldn't be edited", its really more of a "hey we got through the checkout flow". In many stores ```.completed?``` orders can still be changed by a user. In my experience the more we rely on it for behaviour the more trouble we end up in.

I would be more okay with this if we didn't use the ```.completed?``` check and instead added some different flag deciding if it was still user editable, rather than lumping yet more logic on that flag. Maybe ```user_editable?```

This would allow stores to implement the logic they wanted rather than having it tied to ```.completed?```.

**Comment by carchrae** [comment]
this is something that has always confused me; but perhaps it is fixed in solidus by now.

the order json returns 

`permissions: {   can_update: false  }`

but if you have the order_token you can update it no problem, and forever, it seems.

**Comment by cbrunsdon** [comment]
Okay, I follow why you want to lock that down on the cancan level as that gets generated from: 
```
solidus/api/app/views/spree/api/orders/show.v1.rabl
47:  { can_update: current_ability.can?(:update, root_object) }
```
Looks like it was added here: https://github.com/solidusio/solidus/commit/e6240a30e24627053b1eba1bfe4b1e1d32594da6

And doesn't look like its used anywhere inside of solidus anymore. I'd even say this is probably safe (and smart?) to kill, or shift it away from a cancan check.

**Comment by jhawthorn** [comment]
Closing this as there has been a year without activity. Feel free to file a new issue or pull request if appropriate. Thanks.

**Comment by carchrae** [comment]
i never replied to the last comment from @cbrunsdon :  the json `can_update`  was not my main concern.  it was allowing a non-admin user to modify an order after it has been checked out.  at the time i wrote this, a customer could adjust the quantity after they paid for something.  :/  

this became a non-issue for us because we stopped exposing the solidus api and added another layer of control around it.

**Pull request closed without merging**
