### PR TITLE
adds empty div with data-hook for extension

### PR DESCRIPTION
**Pull request by jasonfb**
for https://github.com/solidusio-contrib/solidus_shipping_labeler

### CODE REVIEW

**Comment by jhawthorn** [comment]
Instead of an empty `<div>` at the end, it might be better to wrap the entire form in a `div`. This still allows for the same customisation using deface (and more) and makes more semantic sense.

I'm not sure the test for the selector is providing any value.

**Comment by jasonfb** [comment]
@jhawthorn As you suggested, I wrapped the whole form in a div with a class ```.return-authorization-form-wrapper```

see associated commit in solidus_shipping_labeler https://github.com/solidusio-contrib/solidus_shipping_labeler/commit/b587cf3a5d7add0b06bbaa80d3d8d9ecca3e42c1

**Comment by gmacdougall** [comment]
This looks reasonable to me.

👍

**Comment by jhawthorn** [comment]
:+1: Looks good. Sorry for the delay

**Comment by jhawthorn** [comment]
Merged in #1373. Thank you

**Pull request closed without merging**
