### PR TITLE
[v4.3] Lock solidus_core.gemspec to ransack '< 4.2'

### PR DESCRIPTION
**Pull request by tvdeyen**
# Backport

This will backport the following commits from `main` to `v4.3`:
 - [Merge pull request #5812 from MadelineCollier/lock-ransack-version](https://github.com/solidusio/solidus/pull/5812)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

### CODE REVIEW

**Comment by tvdeyen** [comment]
Installer specs will be fixed by https://github.com/solidusio/solidus_starter_frontend/pull/371

**Review by MadelineCollier — APPROVED** [review]

**Comment by mamhoff** [comment]
This also needs a new backport https://github.com/solidusio/solidus/pull/6016

**Comment by MadelineCollier** [comment]
> This also needs a new backport #6016

Is the backport still required in light of this fix: https://github.com/solidusio/solidus/pull/5853 ?

**Comment by mamhoff** [comment]
Possibly not! I just collected all PRs that might've been affected by that bug in the GitHub actions config.

**Pull request merged**
