### PR TITLE
Replace --auto-accept with --interactive

### PR DESCRIPTION
**Pull request by elia**
**Description**

The current solidus install generator will ask for a number of things unless `--auto-accept` is provided. Since many of the things asked are not simple yes/no questions, and by default Rails doesn't require any interaction when generating a new app, we should move to an opt-in `--interactive` flag.

The current PR only switches to the new CLI option and cleans up the generator to make it more maintainable by solidus core and usable by end-users.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Hey, @elia :wave: Is this PR still valid?

**Comment by elia** [comment]
@waiting-for-dev I guess the fundamental issue wasn't solved in the meantime so I would say yes, we should still streamline the generator and allow it to run both interactively and unattended.

**Comment by waiting-for-dev** [comment]
Thanks, @elia! If I get it well, it's more of a semantic renaming than a behavior change, right? I'm ok with that; I think it makes sense. When you have a second, could you rebase it from master, please? :pray: Also, I'm not sure if it can be already marked as ready for review.

**Comment by waiting-for-dev** [comment]
Hey @elia, I'll close it for now, but if you find the time to keep working on it I'll be more than happy to reopen :slightly_smiling_face:

**Pull request closed without merging**
