### PR TITLE
Add dependent: :destroy to Spree::Order#order_promotions

### PR DESCRIPTION
**Pull request by mamhoff**
## Summary

We found a lot of orphaned records in our database due to this missing dependent: :destroy.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by adammathys — APPROVED** [review]

**Review by kennyadsl — APPROVED** [review]
👍

**Comment by mamhoff** [comment]
Should I provide a migration to clear out orphaned records and add a foreign key constraint as well?

**Comment by mamhoff** [comment]
Rebased, added foreign key constraint.

**Comment by tvdeyen** [comment]
@mamhoff canb we ask for a

```
bundle exec rubocop --fix
```
?

thanks

**Review by tvdeyen — APPROVED** [review]

**Pull request merged**
