### PR TITLE
[WIP] Fix icon link CSS

### PR DESCRIPTION
**Pull request by jhawthorn**
_PR in early stages to demonstrate the issue. Some of this was done as lazily as possible and needs more cleanup._

Currently in Solidus icons are used like this:
```html
<!-- Circle button -->
<a href="..." class="edit-tracking fa fa-edit icon_link with-tip no-text"></a>

<!-- Button with text -->
<a href="..." class="new-thingy button fa fa-plus icon_link with-tip">New Thingy</a>
```

This requires a number of hacks to make work, since the `fa`, `fa-*` classes were never intended to be used in this way. This makes it very difficult to center or space the icons properly, and makes it impossible to use the `:before` selector on these links. The correct use should be

```html
<a href="..." class="edit-tracking icon_link with-tip no-text">
  <i class="fa fa-edit"></i>
</a>

<a href="..." class="new-thingy button icon_link with-tip">
  <i class="fa fa-plus"></i> New thingy
</a>
```

Which exposes another problem: the colorization of the link on hover is based on the name of the icon used. This should probably be changed to something more semantic (maybe `icon-link-error/notice/success`).

### CODE REVIEW

**Comment by Dkendal** [comment]
:+1: yes please. Imo `icon_link` should be renamed as well to `icon-link`, if it falls under the scope of this pr. Also agree that the link colorizing classes should have a name like what was suggested - but it would probably be beneficial to change all classes that are specific to the structure and augmentation of 'icon links' to share a common prefix. Not sure if `with-tip` and `no-text` fall into that realm.

**Comment by BenMorganIO** [comment]
:+1:

@Dkendal agreed.

**Comment by jhawthorn** [comment]
> Not sure if with-tip and no-text fall into that realm.

`with-tip` is it's own thing and means we want a fancy tooltip. Outside this PR's scope.

`no-text` is icon-link specific and should probably be prefixed

**Comment by Dkendal** [comment]
My biggest want would just be having sane classes, that don't rely on the scope of other classes/selectors/whatever that have names that make it obvious that they are intended to be used together.

**Comment by cbrunsdon** [comment]
@jhawthorn do we want to shoot to fix this the same time we stretch out the admin layout? or should we shoot for 1.3?

**Comment by cbrunsdon** [comment]
I care about this because I am tired of hearing people around me complain about it. @Sinetheta what will it take to get this moved forward for 1.3ish?

**Comment by Sinetheta** [comment]
@cbrunsdon just a lot of changing things by hand and verifying the effect with my face. A lot of pixel-perfect nudges will fail, as @jhawthorn mentioned a lot of properties which are not being `inherit`ed will fail.

**Comment by cbrunsdon** [comment]
@Sinetheta my hands and face are busy gesturing wildly and not understanding most of what has to happen here, so I'm going to leave cleaning this up to you.

**Comment by jhawthorn** [comment]
Closing because I haven't spent any more time on this and it is too large a task to tackle at the moment.

This will likely come up again as we improve individual sections of the admin.

**Pull request closed without merging**
