### PR TITLE
[4.1] Use ActiveRecord's `.find_each` instead of `.each` whenever possible

### PR DESCRIPTION
**Pull request by tvdeyen**
## Summary

Backport of https://github.com/solidusio/solidus/pull/5380/ for v4.1

### CODE REVIEW

**Review by elia — APPROVED** [review]
👍👍👍 
pending the installer specs, tbh I'm not sure why the rackup executable is causing trouble, maybe there's a `-y` or `-f` that we can add to overcome the problem.

**Comment by tvdeyen** [comment]
> pending the installer specs

@elia we would need to backport https://github.com/solidusio/solidus/pull/5477 to v4.1 (and 4.1, 4.2 and 3.4 tbh), because all those branches test the installation of latest solidus, what does not make any sense

**Comment by elia** [comment]
@tvdeyen I'm down with backporting it, I think the backport labels will trigger the gh action even after merge 👍

**Comment by tvdeyen** [comment]
That's good to know. @kennyadsl agree?

**Comment by kennyadsl** [comment]
Works for me!

**Pull request merged**
