### PR TITLE
Make promotion selection configurable

### PR DESCRIPTION
**Pull request by richardnuno**
Allow each store to define which promotion gets applied by implementing (or selecting) a promotion chooser. The default is to select the best possible promotion (which is the current behavior).

### CODE REVIEW

**Comment by magnusvk** [comment]
If you look at `BestPromotion` and `LastPromotion`, they are almost identical. That's a lot of common code and we should refactor those classes to share that code. Really, if you look at it, the only difference is in the `best_promotion_adjustment` / `last_promotion_adjustment` method, so it looks like a base class that has a method to override for that might be the way to go.

**Comment by magnusvk** [comment]
Also would be great to provide some documentation for this.

**Comment by magnusvk** [comment]
Another question: The logic in `ItemAdjustments` operates on an item-by-item level. So if you have an order with three line items and a shipment, it may apply different promotions to each of those. For example, if one promo code only generated an adjustment on the order and another one only generated an adjustment on the line items, those would stay active at the same time, right?

**Comment by richardnuno** [comment]
@magnusvk agreed on the code duplication and documentation. To avoid overriding methods how about a base class that calls a defined class that chooses the correct adjustment? As far as the last question, that's correct, they would both be active. Would the intended behavior be to only have one promotion active regardless of item type or does that seem like another customization to you?

**Comment by magnusvk** [comment]
As far as Bonobos goes, yes, our intended behavior is for only one promotion to be active at a time. So that's really another level of customization here.

**Comment by richardnuno** [comment]
@magnusvk ok, closing this PR for now seeing as how that'll involve some more changes. Will reopen once I've got it all sorted out.

**Pull request closed without merging**
