### PR TITLE
Issue 2868: Products at mulitple Stock Locations appear as unique variants.

### PR DESCRIPTION
**Pull request by mayanktap**
Please review the change and suggest if this requires some more work.

Fix for Issue: https://github.com/solidusio/solidus/issues/2868

### CODE REVIEW

**Comment by ericsaupe** [comment]
I think this addresses it nicely. 

A couple of notes, I would redo your commit message to better describe what is actually being changed and, if possible, write a regression test that fails for current versions of Solidus but is resolved with your fix.

Thanks!

**Comment by jacobherrington** [comment]
Great first PR! 🎉 

Regarding Eric's suggestion on the commit messages, we have some great resources for good commit messages in [contributing.md](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines), if you're interested. 

Thanks for fixing this bug!

**Comment by mayanktap** [comment]
@ericsaupe , @jacobherrington Thanks for your review comments. 

Actually, I am familiar in using GIT from terminal instead from UI and because of that I was not able to figure out where GIT commit message is to be changed. I will make the necessary changes in the commit message. 

Regarding the failing test, I check the test case and tried to run the test with and without my code which leads to the failing of same test. So as per my understanding, the failing of test case is not because of the this change. 
@ericsaupe , Can you please specify what kind of regression test are you talking about?

**Comment by ericsaupe** [comment]
@mayanktap sure! Basically, a test that would do something like this:

```
it "returns unique products" do
  Spree::Variant.suppliable.count == variants.count
end
```

That's a very simple test that is obviously mostly pseudocode but the idea is that you're going to call the `suppliable` method and see how many variants come back and compare it with the distinct number of variants we expect. Without your fix this should fail since the `suppliable` method will return duplicated variants but after your fix the test should pass.

Does that make sense?

**Comment by mayanktap** [comment]
@ericsaupe , @jacobherrington

I have improved my commit history with proper commit message. Can you please review this PR? I am not sure how to add reviewers in this PR.

**Comment by spaghetticode** [comment]
@mayanktap after the `push --force` I see there are some spurious changes in the commits for `CHANGELOG.md` file. Can you rework your commits and remove these changes?

**Comment by mayanktap** [comment]
Hi @spaghetticode ,
I guess you are talking about [this](https://github.com/solidusio/solidus/commit/014feb3ddce2fc8cbf8a3777a8bb3196d4ab4b14) change 
I removed those CHANGELOG.md changes because that change was not available in solidus/master and I don't want to merge any changes to solidus/master which are not in the scope of this PR. 

To avoid more confusion, I am closing this PR and creating the new one. The new PR is: https://github.com/solidusio/solidus/pull/3063

**Pull request closed without merging**
