### PR TITLE
Fix "custome" typo

### PR DESCRIPTION
**Pull request by jarednorman**

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1: Do you just spend all day spellchecking this repo?

**Comment by jarednorman** [comment]
@jhawthorn All the typos would have been caught by now if I did!

**Comment by adammathys** [comment]
:flushed: :boom: :dizzy_face:

Amazing! :+1:

**Comment by BenMorganIO** [comment]
lol :+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
