### PR TITLE
Move reports from backend into an extension

### PR DESCRIPTION
**Pull request by jtapia**
#### Issue
Based on https://github.com/solidusio/solidus/issues/1262

#### What it does?
- Move Reports admin section into an extension - https://github.com/jtapia/solidus_reports

### CODE REVIEW

**Comment by kennyadsl** [comment]
Thanks, I think we should also move the extension into solidusio-contrib organization before merging. What do you think?

**Comment by jtapia** [comment]
@kennyadsl sure, what is the process to move the exension into the `solidus-contrib` organization?

**Comment by kennyadsl** [comment]
I think you just need to give me admin access to that repo and I can transfer it. Let's talk in Slack for details if you want!

**Comment by jtapia** [comment]
@kennyadsl I just sent to you the invite, thanks

**Comment by kennyadsl** [comment]
@jtapia I think I have to be admin to make the transfer

**Comment by jtapia** [comment]
@kennyadsl right, my bad, I just did it

**Pull request merged**
