### PR TITLE
Improve Customizing Attributes documentation

### PR DESCRIPTION
**Pull request by dhughesbc**
The documentation about how to add custom attributes to a model in not accurate. This PR updates the documentation

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks! Which is the model you are not seeing in the list?

**Comment by dhughesbc** [comment]
Spree::Role

**Comment by kennyadsl** [comment]
Thanks, just to be clear about why it is missing, `Spree::Role` doesn't have a UI in the admin currently, so there's no admin controller for that resource. I think the guide covers adding attributes to the existing UI provided by Solidus. If you are adding your own views/controllers you already have access to the new controller added and you can simply set the permitted attributes in that controller. Or maybe you are trying to do something else and I am missing something?

Anyway, I think this change is still an improvement and we should add it to the documentation.

**Comment by dhughesbc** [comment]
Thanks, we are using the solidus_user_roles extension, which provides a controller and views for roles management. It was a less experienced (with Solidus) colleague of mine that got tripped up by this Solidus documentation. He added a custom attribute to the Spree::Role model and was following this documentation on how to it, but he did not realize the solidus_user_roles extension does not use the core Spree::PermittedAttributes module.

**Pull request merged**
