### PR TITLE
skip layout on admin json controller

### PR DESCRIPTION
**Pull request by alepore**
Looks like we are loading the layout on the json-only controller Admin::SearchController.
Should be ~50% faster now

### CODE REVIEW

**Comment by cbrunsdon** [comment]
looks right to me. big :+1:, thanks again.

**Comment by jhawthorn** [comment]
I can't reproduce this (but I might be missing something). Both `/admin/search/users` and `/admin/search/products` take the same amount of time with or without this change in a fresh sandbox.

**Comment by jhawthorn** [comment]
Update: I was totally missing something. This took `/admin/search/users` from 200ms to 27ms (on my not particularly fast laptop)

Thanks :+1:

**Comment by alepore** [comment]
@cbrunsdon thanks to you for solidus ;)

**Pull request merged**
