### PR TITLE
Cleanup the database configuration

### PR DESCRIPTION
**Pull request by elia**
## Summary

Refactor the ERB-pestered YAML in order to make it more readable, now using a classic `default` key and official rails adapter names. 

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by adammathys — APPROVED** [review]

**Comment by forkata** [comment]
It looks like this change is causing failures when running specs on extensions against `main` https://app.circleci.com/pipelines/github/solidusio/solidus/5759/workflows/7a3da21a-d96a-41d6-bec5-cb4c1a144401 👀 I am not sure how `solidus` tests are still passing, but I guess we no longer generate a dummy app to run the gems tests.

**Comment by elia** [comment]
@forkata I think I skipped a `&default` at this line https://github.com/solidusio/solidus/pull/5545/files#diff-06fe29b7aa56dcb8df94625d091064d3d8b3c6b24e03de7415646bd39762ca9dR20, thanks for the ping, fixing right away 👍

**Comment by elia** [comment]
@forkata this is weird, the solidus_installer job only performs some steps and then stops in the run that's used for checks 🤔

**Comment by elia** [comment]
This PR seems to be the culprit at which the installer specs stopped running before merges https://github.com/solidusio/solidus/pull/5477, need to find a way to check the target branch instead of the source one.

**Pull request merged**
