### PR TITLE
Update in memory line items in CreateItemAdjustments

### PR DESCRIPTION
**Pull request by jordan-brough**
Update in-memory line items in CreateItemAdjustments

Previously this:
```
Spree::PromotionHandler::Coupon.new(order).apply
```
would not update `adjustment_total` on any already-loaded
`order.line_items` because CreateItemAdjustments didn't operate on the
possibly-cached line items, nor did it reload/reset them.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Removes stubs, reduces a query, fixes a bug

Awesome :+1:

**Comment by cbrunsdon** [comment]
Yea, this is great. Actually fantastic. I can't imagine how many dev hours this is going to save people in the future.

:+1:

**Comment by mtomov** [comment]
:+1:  

Don't know where the bad rep of stubs is coming from, as especially in Rspec - they are verified.

Change is great indeed! Thanks!

**Comment by cbrunsdon** [comment]
@mtomov iirc receive_messages doesn't use a verifying double unless you configure it to, which will be default in future versions of rspec but not with what we're currently running in core.

**Comment by mtomov** [comment]
:+1:

**Pull request merged**
