### PR TITLE
Task and task spec fixes

### PR DESCRIPTION
**Pull request by jordan-brough**
See individual commits:

- Fix rake task specs - only run rake tasks once
- Fix bug in rake task "assure_store_on_orders"
- Change `abort` to `raise` in "assure_store_on_orders"

### CODE REVIEW

**Comment by jhawthorn** [comment]
This looks good to me :+1:

A few additional thoughts:
* We should probably rename `assure_store_on_orders` to `ensure_store_on_orders`
* Does ensuring there's a store_id belong in this rake task? It seems like it could be a migration.

**Comment by jordan-brough** [comment]
I think a migration could make sense here.  Our store needs this rake task because in Solidus < 1.3 a store is only added if the Solidus-provided controllers are used to generate orders.  Our app doesn't use those controller so we have lots of orders without store ids.

**Comment by jordan-brough** [comment]
Added a commit to rename assure -> ensure.

**Comment by jordan-brough** [comment]
@mamhoff any thoughts on moving this to a migration?

**Comment by jhawthorn** [comment]
Thanks Jordan :+1:

**Pull request merged**
