### PR TITLE
Add a "Reviewed by Hound" badge

### PR DESCRIPTION
**Pull request by salbertson**
screenshot 2018-08-07 18 32 44

### CODE REVIEW

**Comment by BenMorganIO** [comment]
@tvdeyen I think it's because it's cool 😎:p

**Comment by BenMorganIO** [comment]
@salbertson Are you able to rebase this from master? Seems like the CI is having problems.

**Comment by salbertson** [comment]
@BenMorganIO rebased and tests are passing. Thanks!

**Comment by tvdeyen** [comment]
@jacobherrington @salbertson

I agree. I appreciate their free service they provide for Open Source and promoting their service it’s the least we can do to to show this appreciation. 

But I also see the list of badges growing into something very random. 

What about splitting the badges into two groups? As we are about to add the Open Collective soon, it may make sense to have a second badges row for "Supported by"? Hound would be a great fit for that badges group, no?

**Comment by salbertson** [comment]
@tvdeyen @jacobherrington sounds good, whatever y'all think makes the most sense.

Would this work?

screenshot 2018-11-17 07 46 30

Or this, without the badge, to support services or companies without badges?

screenshot 2018-11-17 07 47 33

**Comment by jacobherrington** [comment]
I am a fan of the first screenshot (be sure it only lists Hound once though), but it's up to @tvdeyen

**Comment by salbertson** [comment]
Done!

screenshot 2018-11-17 16 50 05

**Comment by tvdeyen** [comment]
Thanks. It seems that we need a rebase with master in order to fix the build errors.

**Comment by jacobherrington** [comment]
@salbertson Do you mind rebasing this, so it can be merged?

**Comment by salbertson** [comment]
@jacobherrington done!

**Pull request merged**
