### PR TITLE
Use heavier selector for select2

### PR DESCRIPTION
**Pull request by oeN**
See Issue https://github.com/solidusio/solidus/issues/1996

### CODE REVIEW

**Comment by gmacdougall** [comment]
Looks like a reasonable change. We have a test failure here that looks related.

I'd also like to see a better commit description.

Thanks for looking in to this!

**Comment by oeN** [comment]
Thank you! I'm looking to the failure right now.

**Comment by oeN** [comment]
@gmacdougall I've tried but I was unable to replicate the error, it seems that the failure spec fails randomly (at least in my environment). Is it possible? Do you know if someone has a problem like this?

With ruby 2.4.0 I was unable to even run the spec because of `poltergeist`.
With ruby 2.3.0 I'm able to run the spec but it fails randomly most of times because of `poltergeist` with errors like:
- `Request to 'http://127.0.0.1:62594/admin' failed to reach server, check DNS and/or server status`
- `Timed out with the following resources still waiting data:image/png;base64,iVBOR.....`

And sometimes the spec pass without problems. Do you have any advice to solve this and get the PR merged?

Thank you!!

**Comment by graygilmore** [comment]
Should we be using an ID or `name`? That's what https://github.com/select2/select2/issues/2750#issuecomment-59634990 suggests.

Should allow us to clean up these selectors even more.

**Comment by oeN** [comment]
Yes, I have opted for the `name` selector `select` instead of the ID to solve this problem quickly and with the minimum amount of code.

**Comment by frankie-loves-jesus** [comment]
Wouldn't it be better if we switched to https://github.com/selectize/selectize.js altogether?

**Comment by jhawthorn** [comment]
There are some good suggestions here, but I think they're all outside the scope of fixing this immediate issue. Many extensions use `<select class="select2">`, so we'll need that to continue working for the time-being.

I'd love to see us move away from that, to bootstrap's `custom-select` or similar, but this is a good fix to an immediate issue.

**Comment by graygilmore** [comment]
> There are some good suggestions here, but I think they're all outside the scope of fixing this immediate issue. Many extensions use <select class="select2">, so we'll need that to continue working for the time-being.

👍 It wasn't fully clear to me why this was necessary so I pulled stuff down and tested things out. I think improving the commit message here will go a long way in clarifying things for future-us.

**Comment by oeN** [comment]
@tvdeyen I've tried to add the information on the commit, let me know if is fine. I thought I had to stay in the character limit 😄

**Comment by tvdeyen** [comment]
> I thought I had to stay in the character limit

This character only applies to the first sentence. The description body (separated by a new line) can and should be as long as you need to explain the rational behind our changes. 

A very good read on this topic is: https://chris.beams.io/posts/git-commit/

**Pull request merged**
