### PR TITLE
fixing the promotion categories error message

### PR DESCRIPTION
**Pull request by mgharbik**

### CODE REVIEW

**Comment by mamhoff** [comment]
Would you mind squashing the two commits into one and adding a meaningful commit message explaining this change? You'll have to rebase onto the current master anyways, and it'd be really nice if this not-so-obvious change would be somewhat more well-documented. 

Otherwise, this looks good. I'm especially happy you added specs for the fixed behaviour. Thank you!

**Comment by simo163** [comment]
@mamhoff I just sent you another PR. Thank you too for the tips!

**Comment by tvdeyen** [comment]
Could you please rebase on current master? Thanks

**Comment by mgharbik** [comment]
@tvdeyen sorry for the late replay! Please check it now!

**Comment by tvdeyen** [comment]
Sorry that this took so long

**Pull request merged**
