### PR TITLE
Fix UserManagement permissions to allow saving and removing from address book

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by athal7** [comment]
this should fix the failing specs

**Comment by gvaughn** [comment]
Gee, permissions are based upon the specific model methods? I'm glad you found a quick fix for the problem, but that's going to limit refactoring/renaming things.
:+1:

**Comment by jhawthorn** [comment]
> Gee, permissions are based upon the specific model methods? I'm glad you found a quick fix for the problem, but that's going to limit refactoring/renaming things.

This is what was already done here https://github.com/solidusio/solidus/blob/master/core/lib/spree/permission_sets/default_customer.rb#L26

**Comment by athal7** [comment]
@gvaughn no not the specific model methods, those authorization checks were called out specifically in the controller: https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/address_books_controller.rb#L25

**Comment by gvaughn** [comment]
Thanks. I'm trying to learn my way around these codebases one PR at a time.

@athal7 That addresses my concern nicely.

**Pull request merged**
