### PR TITLE
Rails 5.1

### PR DESCRIPTION
**Pull request by jhawthorn**

### CODE REVIEW

**Comment by jhawthorn** [comment]
We're now ready for Rails 5.1. All deps we need have releases compatible with rails 5.1 :tada:

I'll update this PR to also be compatible with rails 5.0

**Comment by jarednorman** [comment]
This all looks quite sensible. :100:

**Comment by ericsaupe** [comment]
Is it worth updating all form tags to use the new `form_with`? http://edgeguides.rubyonrails.org/5_1_release_notes.html#unification-of-form-for-and-form-tag-into-form-with. I know the Rails core team haven't said anything about deprecating current form tags but this is the unification of the two.

**Comment by jarednorman** [comment]
I can't imagine it's worth the effort of doing that up front if the existing helpers aren't being deprecated.

**Comment by ericsaupe** [comment]
@jarednorman that's what I thought as well. Just thought I'd bring it up!

**Comment by peterberkenbosch** [comment]
👍

**Pull request merged**
