### PR TITLE
Fix issue with user breadcrumbs

### PR DESCRIPTION
**Pull request by jtapia**
### Issue
- https://github.com/solidusio/solidus/issues/3149

### Preview
Screen Shot 2019-03-21 at 4 35 12 PM 1

### CODE REVIEW

**Comment by kennyadsl** [comment]
This could be a solution (I'm wondering if using only `@user.email_was` without any if fixes the issue as well since I think it always returns the right email) anyway I think this issue could be present in several other admin pages and we should come up with a more robust long-term solution.

I'm taking a look at https://github.com/weppos/breadcrumbs_on_rails which is old and unmaintend but it's very few lines of code that we could add to solidus easily maybe. It provides an interface in the controller to set breadcrumbs, this way we could maybe define breadcrumbs before calling the `update_attributes` that makes the instance dirty? How does it play with ResourceController? Maybe worth exploring a little bit more.

**Comment by aldesantis** [comment]
@jtapia would like to get this in. Could you rebase?

**Comment by jtapia** [comment]
@aldesantis done

**Comment by aldesantis** [comment]
@jtapia thanks!

**Pull request merged**
