### PR TITLE
[Admin][Users]Add new admin store_credits show page

### PR DESCRIPTION
**Pull request by MadelineCollier**
## Summary
This PR is for issue: https://github.com/solidusio/solidus/issues/5824

The store credits flow is in the process of being significantly refactored so this will eventually be a page which both displays the store credit info and allows editing (when appropriate). It will match the flow of the new user addresses page. For now this just replaces the legacy show page and migrates the `users/:user_id/store_credits/:id` page from the legacy `soldius_backend` to the new `solidus_admin`. Again there were no designs so I just tried my best to match to the existing components and layouts.

## Screenshots
New page
Screenshot 2024-12-02 at 5 40 30 PM

Old page
Screenshot 2024-12-02 at 4 37 54 PM

## Bonus
New badge scheme
Screenshot 2024-12-02 at 4 46 49 PM

Old badge scheme
Screenshot 2024-12-02 at 4 47 05 PM

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by MadelineCollier** [comment]
This PR is waiting for https://github.com/solidusio/solidus/pull/5998 which should fix the two failing flaky specs. Thanks @tvdeyen for your work on making the other specs less flaky!

**Review by tvdeyen — COMMENTED** [review]
Thanks. Can we please continue the work on semantics we started in #5950 (6bd7f5e14d460687420208ec96ccfde98da29f38) and use links instead of divs for the store credits components. I would like us to establish as much semantics as possible going forward with the new admin. Reducing the amount of work we have to do in the future.

**Comment by MadelineCollier** [comment]
@tvdeyen For sure, apologies I had some of this stashed work already done prior to that change. I'll update!

**Comment by MadelineCollier** [comment]
> Thanks. Can we please continue the work on semantics we started in #5950 ([6bd7f5e](https://github.com/solidusio/solidus/commit/6bd7f5e14d460687420208ec96ccfde98da29f38)) and use links instead of divs for the store credits components. I would like us to establish as much semantics as possible going forward with the new admin. Reducing the amount of work we have to do in the future.

The links don't work with the specs as they blow away the query params, something which the specs expect to be present after clicking through. Since we still haven't solved that I think we'll need to keep it as is until we have a solution to preserve those params.

**Comment by MadelineCollier** [comment]
@tvdeyen more context [here.](https://github.com/solidusio/solidus/pull/5950#issuecomment-2506153413)

**Review by tvdeyen — APPROVED** [review]
I tabled https://github.com/solidusio/solidus/pull/6014#issuecomment-2522738468

so this is ready to be merged. Thanks for the patience 🙏🏻

**Comment by MadelineCollier** [comment]
> I tabled [#6014 (comment)](https://github.com/solidusio/solidus/pull/6014#issuecomment-2522738468)
> 
> so this is ready to be merged. Thanks for the patience 🙏🏻

No worries, thank you so much for investing the time to look into it!

**Pull request merged**
