### PR TITLE
Shipping method stock locations timestamps

### PR DESCRIPTION
**Pull request by jhawthorn**
Fixes an error on migration

### CODE REVIEW

**Comment by cbrunsdon** [comment]
Modifying migrations on an already-released version scares me. Should we not be doing this as a new migration?

**Comment by jhawthorn** [comment]
```
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manua
lly specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /home/jhawthorn/src/solidus/core/sp
ec/dummy/db/migrate/20160201232080_create_spree_shipping_method_stock_locations.spree.rb:8)
```

This adds `null: true`, which preserves the the existing rails 4.2 behaviour, removing the warning.

**Comment by jhawthorn** [comment]
We spoke IRL to approve this.

**Comment by tvdeyen** [comment]
:+1:  No need to add a new migration.

**Pull request merged**
