### PR TITLE
Use more appropriate language for woman's t-shirt in sample data

### PR DESCRIPTION
**Pull request by Noah-Silvera**
**Description**

In the sample data, a woman's t-shirt exists with the product name "Solidus Girly" 

Using the word "girly" to describe a woman's t-shirt is infantilizing, so we should update the product in the sample database to use "woman's " instead.

**Manual Tests**

1. Create a Sandbox app
    * [x] Ensure it successfully seeds
    * [x] Ensure the "Solidus Girly" product has been updated to "Solidus Woman's T-Shirt" 

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
~~- [ ] I have updated Guides and README accordingly to this change (if needed)~~
~~- [ ] I have added tests to cover this change (if needed)~~
- [x] I have attached screenshots to this PR for visual changes (if needed)

Screen Shot 2021-04-20 at 12 32 18PDT

### CODE REVIEW

**Review by peterberkenbosch — APPROVED** [review]
Thanks for pointing that out and fix it as well. LGTM! 👍 :shipit:

**Review by kennyadsl — APPROVED** [review]
👍 Thanks!

**Review by jarednorman — APPROVED** [review]

**Review by jarednorman — DISMISSED** [review]
I just approved but upon further consideration, do you think it should be "Women's" rather than "Woman's", since you wouldn't say "Man's T-Shirt", you'd say "Men's T-Shirt"?

**Comment by Noah-Silvera** [comment]
> I just approved but upon further consideration, do you think it should be "Women's" rather than "Woman's", since you wouldn't say "Man's T-Shirt", you'd say "Men's T-Shirt"?

Always coming in hot with the grammar catches! Thanks, updated :)

**Review by jarednorman — APPROVED** [review]

**Pull request merged**
