### PR TITLE
Silence deprecation warnings in specs

### PR DESCRIPTION
**Pull request by jhawthorn**

### CODE REVIEW

**Comment by cbrunsdon** [comment]
The deprecation warning on by_number is good by me, and moving to use the helper for deprecate is fine too.

What was the reasoning behind silencing during the spec runs? So we can still use our own deprecated methods for a few commits? Or I guess we still have specs that test their behaviour that we want silenced?

**Comment by jhawthorn** [comment]
> What was the reasoning behind silencing during the spec runs? So we can still use our own deprecated methods for a few commits? Or I guess we still have specs that test their behaviour that we want silenced?

The specs are testing the deprecated method.

**Comment by cbrunsdon** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
