### PR TITLE
Use deliver_later instead of deliver_now

### PR DESCRIPTION
**Pull request by jhawthorn**
We're on rails 4.2 let's start leveraging active_job.

This is providing limited set of performance enhancements AND new Rails functionality :wink:.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Very :+1:. I remember doing this in Spree and happy to see it Solidus!!!

**Comment by gmacdougall** [comment]
:+1: as well.

**Comment by BenMorganIO** [comment]
I think this is ready for merging. The only thing I can think of is making sure the specs run the job inline. Since Spree doesn't set a different option anyways, I'm guessing this will be the case.

**Comment by Senjai** [comment]
:+1:

**Comment by hhff** [comment]
yeyah

**Comment by athal7** [comment]
:+1:

**Pull request merged**
