### PR TITLE
Replace skeleton grid with bootstrap grid

### PR DESCRIPTION
**Pull request by jacobherrington**
Refs #2758 

**The issue**
Solidus frontend currently relies on [_skeleton.scss](https://github.com/solidusio/solidus/blob/master/frontend/app/assets/stylesheets/spree/frontend/_skeleton.scss), which is a grid system using fixed widths. It is  outdated (last updated in 2011). It might confuse or deter newcomers because it is not mobile friendly and difficult to iterate on.

**What this PR changes**
We added _only_ the grid system from Bootstrap 4.1.1 [(bootstrap-grid.css)](https://github.com/jacobherrington/solidus/blob/chore/replace-skeleton-css/frontend/app/assets/stylesheets/spree/frontend/bootstrap-grid.css), which should feel familiar to most newcomers and makes it very easy to drop in the full Bootstrap framework if someone wants to extend the existing frontend. On the other hand, it is almost as easy to extract [bootstrap-grid.css](https://github.com/jacobherrington/solidus/blob/chore/replace-skeleton-css/frontend/app/assets/stylesheets/spree/frontend/bootstrap-grid.css) if someone wants to use another solution for styling. This makes the frontend easier to iterate on.

**Caveats**
There are cases in which we could have made slight design changes, but we left those choices out of this PR and may revisit them in the future. Instead, we chose to make as few design changes as possible. The goal of this PR was to move from a fixed-width CSS grid to a flex-based CSS grid, not redesign the look and feel of the frontend.

### CODE REVIEW

**Comment by gmacdougall** [comment]
Thanks for your work on this. We've been talking about making major changes to the front end for some time, but looking at this change, I think it can provide a decent quality of development life for people who are using the front end as is right now.

I think the big thing we're concerned about is breaking people's existing customization which they have made using skeleton CSS and markup.

For people just starting their stores now, I do think this is a better options for them.

**Comment by jacobeubanks** [comment]
Thanks for your response!

I agree with @gmacdougall and @jacobherrington. Though I think this is an improvement, I'm not sure if this small change is worth breaking frontends.

**Comment by tvdeyen** [comment]
We should be able to keep the skeleton grid until the next version if Solidus and remove it later. Stores using it (very unlikely they actually do) have the chance to migrate to a grid system of their liking (even keep using skeleton by copy it into their app). 

We should even be able to print out a deprecation warning with Sass if people are still using our skeleton file.

**Comment by ericsaupe** [comment]
I like the idea of deprecating it with an eye to a future release. Solidus 3.0 would have the new styles for example since a full point release usually means things are going to break. Out of the box Solidus should look good and look good on mobile.

**Comment by jacobherrington** [comment]
Going to close this until I can revisit removing Skeleton in a better way.

**Pull request closed without merging**
