### PR TITLE
Remove PreferenceRescue

### PR DESCRIPTION
**Pull request by jhawthorn**
This code is not used and would no longer work.

### CODE REVIEW

**Comment by jordan-brough** [comment]
:100:

**Comment by Senjai** [comment]
:+1:

**Comment by gmacdougall** [comment]
Conflicts... That's weird.

:+1: otherwise

**Comment by jhawthorn** [comment]
> Conflicts... That's weird.

I noticed this because of #354, but forgot to make sure I was on top of that merge

**Pull request merged**
