### PR TITLE
Remove ancient unneeded initializers

### PR DESCRIPTION
**Pull request by jhawthorn**
Came across these when meaning to open an initializer in the sandbox. Most should have been removed ages ago.

### CODE REVIEW

**Comment by adammathys** [comment]
:+1:

**Comment by magnusvk** [comment]
I have zero context on these but given that we don't use frontend here I'm just going to give you a blanked :+1: for the Bonobos side :)

**Comment by gmacdougall** [comment]
They're really old. Mostly from pre 1.0 Spree.

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
