### PR TITLE
Remove map_nested_attributes_keys

### PR DESCRIPTION
**Pull request by jhawthorn**
This was weird code which we barely used.

### CODE REVIEW

**Comment by Senjai** [comment]
:+1:

**Comment by jordan-brough** [comment]
:+1:

**Comment by BenMorganIO** [comment]
Slightly concerned mainly because I might have used `#map_nested_attributes_keys` out of pure frustration in the past... (But, anywho, that's my problem, not Solidus's)

I'm :+1:

**Comment by jhawthorn** [comment]
One reason I'm eager to remove it is that it would be easy to accidentally use it to bypass strong params

**Comment by cbrunsdon** [comment]
As this was technically public we should make a note in the changelog that we removed it and let people know they can add it back into their controllers that used it if they need it still.

**Pull request merged**
