### PR TITLE
Fix taxons page with new Spree.ajax calls (and cleanup)

### PR DESCRIPTION
**Pull request by jhawthorn**
This was missing a necessary {"X-Spree-Token": Spree.api_key }, which was causing the API call to error. Also cleaned up the rest of the ajax calls in the file.

### CODE REVIEW

**Comment by gmacdougall** [comment]
Looking good so far.

**Comment by adammathys** [comment]
:+1:

**Comment by jhawthorn** [comment]
Just rebased and added the small feature spec

**Comment by Sinetheta** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
