### PR TITLE
Update pinned chrome version

### PR DESCRIPTION
**Pull request by tvdeyen**
## Summary

The current version does not exist anymore. We need to update it.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by tvdeyen** [comment]
Not sure why it is not working. The circle ci orb maintainers [recommend to pin a version](https://github.com/CircleCI-Public/browser-tools-orb/issues/75#issuecomment-1698115898) and the version used in this PR exists according to the official chrome for testing json API https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json

It should work™️ 🤷🏻

**Comment by tvdeyen** [comment]
Ah, I needed to update the orb version as well. Working now

**Review by elia — APPROVED** [review]
📍

**Comment by tvdeyen** [comment]
@solidusio/core-team can we get another approval to make CI work again? 🙏🏻

**Pull request merged**
