### PR TITLE
allow optional checkout steps numbers

### PR DESCRIPTION
**Pull request by alepore**
clients asked this to me me a few times...

### CODE REVIEW

**Comment by tvdeyen** [comment]
Although this is a step into the right direction, this really should be partials. Putting together templates in helpers is something we should avoid in the future.

**Comment by gmacdougall** [comment]
I agree. I think that deprecating this method is probably for the best. I'd like to move this functionality from `core` to `frontend` as well.

**Comment by cbrunsdon** [comment]
What if we do it with i18n? Pass the state "number" into the string and let the locale decide to show it or not? (or is this too large an abuse?)

It would just be a smaller change than moving it out of helpers...

I'm 100% behind moving it to frontend though.

**Comment by gmacdougall** [comment]
This is probably the wrong solution after looking at this closer. It uses an `<ol>` tag, so the number should already be there, it's probably being disabled by CSS list style or something like that.

**Comment by cbrunsdon** [comment]
whoops, thanks, nice catch @gmacdougall.

@alepore would overriding the css work for you?

**Comment by alepore** [comment]
i also don't like HTML helpers... except when they have 5+ lines of code :)

about helpers, spree 3.0 moved some stuff on the frontend, this could be a good start: https://github.com/spree/spree/tree/master/frontend/app/helpers/spree

**Comment by alepore** [comment]
totally right about `ol`, number are actually there, i tested the wrong frontend :disappointed:

**Pull request closed without merging**
