### PR TITLE
Actually fix that pesky address spec

### PR DESCRIPTION
**Pull request by jhawthorn**
Even after improving the spec this was still failing. Turns out there was a race condition in the JS for fetching the states.

This should fix that spec for good this time.

Thanks @Sinetheta for discussion.

### CODE REVIEW

**Comment by Sinetheta** [comment]
https://youtu.be/B8IfCSnYPYo?t=54s

**Comment by adammathys** [comment]
:+1:

**Comment by athal7** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1: :green_heart:

**Pull request merged**
