### PR TITLE
make payment methods sortable

### PR DESCRIPTION
**Pull request by alepore**
so users can decide payment methods display order

### CODE REVIEW

**Comment by jhawthorn** [comment]
This is failing because `remove_environment_from_payment_method.rb` has the line `Spree::PaymentMethod.where('environment != ?', Rails.env).update_all(active: false)`

We'll have to replace that with raw SQL

**Comment by alepore** [comment]
@jhawthorn right, i solved adding `.unscoped`

**Comment by jhawthorn** [comment]
:+1:

**Comment by cbrunsdon** [comment]
I'm very supportive of the plan to make sortable payment methods, I think its a good move for us as a project, but I don't like the default_scope on payment methods. 
I know we do this in other places, but as a developer using the platform I'm always tripped up by us using default_scopes and would like to stop using them.

My main problem comes from being a developer using spree as a project, default_scope's on models leads to behavior I would not expect and is tough to hunt down. I'd rather us explicitly sort it everywhere we know it needs to be sorted rather than have other developers run into potential surprises on our default scopes.

**Comment by tvdeyen** [comment]
I think `default_scope` is not per se evil. There are places where it helps the developer to prevent unexpected behavior, like soft deleted products, not yet available products, etc. 

But here the default scope is kind of optional. Not having the payment methods sorted is not harmful and therefore not mandatory. Displaying discontinued products is. 

So, here we should remove the `default_scope`

Otherwise 👍

**Comment by alepore** [comment]
agree!
i just copied that from the other models, but would be a good thing to remove all those non-critical `default_scope`, add a small `Sortable` module and keep coherence.
i can take that!

**Comment by alepore** [comment]
so.. back on this.
i forgot about that @Senjai PR and messed up with a force push :)
recreated lost commits, this is not now complete and rebased.

**Comment by jhawthorn** [comment]
:+1: Thank you for updating

**Pull request merged**
