### PR TITLE
Make PromotionChooser extensible

### PR DESCRIPTION
**Pull request by richardnuno**
Provides an extension point for stores to define their own promotion chooser.

### CODE REVIEW

**Comment by athal7** [comment]
do you mind adding a spec?

otherwise this is :+1:

**Comment by richardnuno** [comment]
@athal7 added a test to ensure custom promotion choosers are instantiated.

**Comment by athal7** [comment]
:+1:

**Comment by jhawthorn** [comment]
:+1: love it.

I'm not sure this is the best place for the `promotion_chooser_class` configuration (code reloading issues, and I'm not sure it's the responsibility of ItemAdjustments) but I don't have a better suggestion right now.

**Comment by magnusvk** [comment]
@jhawthorn I was chatting with @jordan-brough earlier today about potentially having a central place for checkout-specific extension points like this. In his case, we were talking about an extension point for "after credit card added to order" and "after new ship address added to order". Perhaps now is the point to make a `Spree::CheckoutCustomizations` or `Spree::Order::CheckoutCustomizations` class, where all it has are these extension points? Would make it nice and easy for somebody new to Solidus to find all the things they can safely customize, also. Curious what other people's take is on that.

**Comment by jordan-brough** [comment]
@magnusvk - I just got through talking with @jhawthorn and he pointed to app_configuration which is where `searcher_class` is currently configured: https://github.com/solidusio/solidus/blob/287b118/core/app/models/spree/app_configuration.rb#L235-L239

Using app_configuration seems like it lines up really well with what you were saying and seems like a good option to me. What do you all think?

**Comment by magnusvk** [comment]
@jordan-brough that looks good to me. Let's put it there.

@richardnuno Can you just move the configuration over to live in the `AppConfiguration`? Then we can hit merge here.

**Comment by athal7** [comment]
do we want to do another round to move other configurations (e.g. returns) over similarly?

**Comment by jordan-brough** [comment]
@athal7 :+1: You mean as a separate task/PR right?

**Comment by athal7** [comment]
yep, issue here: https://github.com/solidusio/solidus/issues/282

**Comment by richardnuno** [comment]
Moved the code over to `app_configuration.rb` if anyone has a couple of minutes to take a look

**Comment by magnusvk** [comment]
Great. Let's :ship: :it:

**Comment by jordan-brough** [comment]
cool, that looks really nice.

**Pull request merged**
