### PR TITLE
Use backbone for admin product sorting, fix admin stock item UI

### PR DESCRIPTION
**Pull request by aaronlifton**
- Moved taxon js into a folder
- converted product sorting coffeescript to js and made it use a backbone view
- fixed stock item table UI

**Before**
image

**After**
image

**Before**
image

**After**
image

### CODE REVIEW

**Comment by tvdeyen** [comment]
### Firefox and multiple stock locations

stock 2 locations firefox

Looks the same on chrome. Using `rowspan` like this is not how we can solve this issue. The table needs to have a nested table for the stock locations. I already invested lots of time into trying to solve this issue and this is the only solution I came up with.

### Firefox with one stock location 

stock firefox

**Comment by aaronlifton2** [comment]
Ahh ok, thanks. Will do.

**Comment by aaronlifton2** [comment]
I thought about this, perhaps using css columns would work better than nested tables here? Unless you already got it working.

**Comment by aldesantis** [comment]
@aaronlifton I noticed you opened #2438 which doesn't contain the stock location UI change. Do you want to close this PR or keep it to continue work on stock locations once #2438 is merged?

**Pull request closed without merging**
