### PR TITLE
Style store link from the admin sidebar

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Summary

A few decisions are made here when it comes to following the provided Figma design. TL;DR: Figma, from which we have less control, wins over Tailwind, which we can change at any time:

- We start configuring Tailwind to avoid using hardcoded `[style]` attributes. We'll continue this whenever we find the need to add new styles.
- Even when both Tailwind and Figma use the same style name and value, we still explicitly configure it in Tailwind. This is to avoid future discrepancies and to make it easier to change. Example: `fontSize/sm`.
- When Tailwind and Figma use the same style value but with different names, we add the Figma name to Tailwind. Ideally, we should try to change Figma to use the same name as Tailwind, but, for now, it'll be easy to compare styles in this way, and a rename from the code part will be straightforward. Example: `fontSize/tiny`.
- When Tailwind and Figma use different style values for the same style name, we change Tailwind to use the Figma value. Example: `fontWeight/bold`, which is `600` for the Figma style and `700` for Tailwind.
- For spacing, we didn't find the need to configure anything different from the default Tailwind spacing scale, so we use it as is. That keeps things much simpler in something that could be cumbersome to think about.

Another rule we followed is that when needing to separate different blocks, we use the top margin from the element below.

We also followed a loose rule where we stack the CSS classes in different lines, from top to bottom:

- Spacing in relation to other elements: display, flex, etc...
- Spacing in relation to the element itself: padding, margin, etc...
- Border styles: color, width, radius...
- Text styles: font size, color...
- Font styles: familiy, weight...
- Background styles: color, image...

screenshot-localhost_3000-2023 06 22-17_14_35

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Review by elia — APPROVED** [review]
Awesome!

About the rules followed for this PR I would comment that:

> We also followed a loose rule where we stack the CSS classes in
> different lines, from top to bottom:
> 
> - Spacing in relation to other elements: display, flex, etc...
> - Spacing in relation to the element itself: padding, margin, etc...
> - Border styles: color, width, radius...
> - Text styles: font size, color...
> - Font styles: familiy, weight...
> - Background styles: color, image...

is great, as long as we automate it in some way, as maintaining it manually is super time-consuming.

I'm sure we could add some TW specific rule to erb-formatter and have it handled automatically. But any other suggestions is as good.

**Review by rainerdema — APPROVED** [review]
Thanks @waiting-for-dev, LGTM!

**Comment by waiting-for-dev** [comment]
Ref. #5106

**Comment by waiting-for-dev** [comment]
> is great, as long as we automate it in some way, as maintaining it manually is super time-consuming.
>
> I'm sure we could add some TW specific rule to erb-formatter and have it handled automatically. But any other suggestions is as good.

Yeah, I agree. Because of that I set the rule as to be loosely followed... but I think it helps at least when related styles are in the same line. Let's talk more about it. Having a cop for erb-formatter would be super cool.

**Pull request merged**
