### PR TITLE
Make store factory name a sequence

### PR DESCRIPTION
**Pull request by philbirt**
* Allows for stores to have a uniqueness validation on name

### CODE REVIEW

**Comment by athal7** [comment]
:+1:, maybe just check that some of the extensions work with this. i remember auth_devise and multi_domain failing from the url sequence

**Comment by jhawthorn** [comment]
:+1: but agree with andrew's concerns

**Comment by jhawthorn** [comment]
It looks like this had two legit test failures. (one 1 spurious looking failure :()

**Comment by philbirt** [comment]
@jhawthorn fixed the specs and tested this out with auth_devise and multi_domain with no issues!

**Pull request merged**
