### PR TITLE
Clean request specs

### PR DESCRIPTION
**Pull request by biximilien**
Hi,

As my first contribution to solidus, I have attempted this beginner friendly issue Ref #4001 

I was inspired by discussions and comments from #4122 

I have :
- Renamed all requests specs to remove `controller` from the filename
- Renamed the describe constant as per the example in https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec
- Renamed the modules under `solidus/api/spec/requests/spree/api` to `Spree::Api`
- Fixed all core constants used to have the `Spree::` namespace prefix

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Looks great, thanks!

**Review by jarednorman — APPROVED** [review]
Looks like there's a conflict, but this also seems reasonable to me.

**Comment by kennyadsl** [comment]
@biximilien can you please rebase against master to fix the conflict, please?

**Comment by biximilien** [comment]
@kennyadsl Certainly, I will rebase tonight against master.

**Pull request merged**
