### PR TITLE
Upgrade rake task fixes

### PR DESCRIPTION
**Pull request by jordan-brough**
Fixes for #1245. See individual commits.

### CODE REVIEW

**Comment by jordan-brough** [comment]
It'd be great to get more specs around these tasks and also to address the "TODO".  If anyone has the time or inclination to do so that would be great!  I think this at least gets us to a starting point though.

**Comment by jhawthorn** [comment]
:+1:

**Comment by jhawthorn** [comment]
I've sent you a PR to address the TODO https://github.com/jordan-brough/solidus/pull/3

**Comment by mamhoff** [comment]
👍  Thank you!

**Pull request merged**
