### PR TITLE
Lookup current_store by request headers HTTP_SPREE_STORE

### PR DESCRIPTION
**Pull request by philbirt**
This originally comes from https://github.com/bonobos/spree-multi-domain/commit/28eb89f76ac16a6e6cb87619618976f00029825a#diff-19b421a80e5cfd93e62d9f9465bb3cd3R30

The alternative approach would be to put this in solidus-multi-domain, but there are significant load-order problems, and it would be kind of hacky. Since our ultimate goal is to move multi-domain into core one day, I think it should live here.

### CODE REVIEW

**Comment by jhawthorn** [comment]
I like this. :+1:

Maybe a little mention in the docs of the ControllerHelpers::Store module would be nice

**Comment by magnusvk** [comment]
:+1: Let's add a mention in the docs and then this is ready to go.

**Comment by philbirt** [comment]
At the risk of sounding foolish, is there a good example of how this should be done? Like, where the docs should be, in what format, what sort of information?

**Comment by gmacdougall** [comment]
My only suggestion would be to extract the current store logic to its own class, document it, and allow people to specify their own class to use if they'd prefer different logic.

Quick demo:

Example:

```Ruby
module Spree
  module Core
    module ControllerHelpers
      module Store
        extend ActiveSupport::Concern

        included do

          # docs
          class_attribute :current_store_class
          self.current_store_class = Spree::Core::CurrentStore

          def current_store
            @current_store ||= current_store_class.new(request).store
          end
          helper_method :current_store

        end

      end
    end
  end
end
```

```Ruby
# Full description about these responsibilities
module Spree
  module Core
    class CurrentStore

      # docs
      def initialize(request)
        @request = request
      end

      # docs
      def store
        store = Spree::Store.find_by(key: store_key)
        raise StoreNotFoundError unless store
        store
      end

      private

      def store_key
        @request.headers['HTTP_SPREE_STORE'] || @request.env['SERVER_NAME']
      end
    end
  end
end
```

The CurrentStore class can now be tested in isolation with a mocked request, and if you want to do something else, you can override that logic for your own store.

**Comment by adammathys** [comment]
:+1: I agree with @gmacdougall, making this extensible would be nice. 

I should point out that if you want to document the class attribute you'll need to do something like [this](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/auth.rb#L7-L22). Because the documentation tools we use won't read anything in the `included` block.

**Comment by philbirt** [comment]
Updated it, allowing it to be extended (great idea @gmacdougall) and some documentation. If the docs could be any better or should include anything, please let me know

**Comment by adammathys** [comment]
:+1: Outside the one minor documentation tweak, this looks good to me.

**Comment by magnusvk** [comment]
:+1: 
@gmacdougall @cbrunsdon @jhawthorn Does this look good?

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
