### PR TITLE
Fix class-level private declaration

### PR DESCRIPTION
**Pull request by jhawthorn**
Private only affects instance methods being defined, not class level methods. To fix this we define instance methods on the singleton class.

### CODE REVIEW

**Comment by jarednorman** [comment]
:sparkles: The Singleton Wizard approves! :sparkles:

**Comment by jordan-brough** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Comment by dkubb** [comment]
There is also `private_class_method` which imho is cleaner than private methods in a singleton class, and also easier for some tooling to work with.

**Pull request merged**
