### PR TITLE
Remove Spree::ViewContext from Spree.t

### PR DESCRIPTION
**Pull request by jhawthorn**
This removes some bizarre hacks:
* `Spree.content_tag(:div) #=> "<div></div>"`
* `Spree.context` stored the last ActionView context from the last controller action :fearful:.
* `Spree.t(".foo")` would try and scope the translation by the currently partial (broken, dangerous, not threadsafe)

### CODE REVIEW

**Comment by BenMorganIO** [comment]
kill it :+1:

**Comment by gmacdougall** [comment]
Should we mark these as deprecated for now?

I do want to see them go away.

**Comment by magnusvk** [comment]
Either way works for me. We don't use any of this anyhow.

**Comment by jhawthorn** [comment]
@gmacdougall 
> Should we mark these as deprecated for now?

I don't think we need to deprecate `Spree.content_tag`, which was created by accident and I'm sure nobody knew existed.

I could see wanting deprecations for `Spree.t(".translation")`, but this functionality was never used in core/backend/frontend and none of the translation keys were structured for using this. IMO these can be removed without deprecations.

**Comment by gmacdougall** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
