### PR TITLE
Fix some broken factories

### PR DESCRIPTION
**Pull request by Dkendal**
Makes it so that adjustment_factory, payment_factory, shipping_method_factory, and stock_factory pass lint.

Partially addresses #568

### CODE REVIEW

**Comment by mamhoff** [comment]
Is this still work in progress? Because it really addresses some annoying ones in the factories. I'd love to see this merged.

**Comment by Dkendal** [comment]
It works as is, however it does not address *all* broken factories.

**Comment by mamhoff** [comment]
I'm working on #623, and running into some factories that can't be built. Some of my fixes are the same as the ones you're proposing here, and in order not to make your work redundant or get merge conflicts, I'd love to build on it. 

I understand it'd be nicer to address all issues, but the nice things about this is that all the fixes are atomic in the sense that they don't depend on each other and just make things better :)

**Comment by gmacdougall** [comment]
I agree with @mamhoff  Lets get this in as is and do more PR's to fix the other stuff.

**Comment by Dkendal** [comment]
Sounds good to me!

**Comment by Dkendal** [comment]
Updated description.

**Comment by Dkendal** [comment]
Feedback from https://github.com/Dkendal/solidus/commit/6cb4728a0c3f77f126755ac4957e48a2b69bbc71 addressed in https://github.com/Dkendal/solidus/commit/a5840ad1f677a29d712cfc7e4fa206b8acf40a29

**Comment by jhawthorn** [comment]
Looks good to me :+1:. Thank you!

**Comment by cbrunsdon** [comment]
Yea, good by me too, thanks @Dkendal.

**Comment by jordan-brough** [comment]
:+1: Thanks!

**Pull request merged**
