### PR TITLE
Allow customizing the carton mailer class

### PR DESCRIPTION
**Pull request by jordan-brough**
So that stores can customize these emails in a more fine-tuned way
without having to monkey patch Spree::CartonMailer.

We were monkey patching Spree::CartonMailer and #310 ended up
breaking our monkey patch. Things we are customizing:

- add a bcc
- customize the subject
- set a custom instance variable that we use in our templates
- dynamically set the template path depending on the order's store

Instead of this PR we could alternatively provide hooks for
each of those things (and for some of them we could use
ActionMailer's `before_action` hooks).  Thoughts?

I'm guessing that emails are a frequently customized aspect of
Solidus.

If we do want to go the route of this PR then we should probably
add preferences like this for the order and reimbursement mailers
as well.  And possibly split out the OrderMailer into separate
classes for each type of Order email, so that we can
add/remove/deprecate different emails individually.

### CODE REVIEW

**Comment by magnusvk** [comment]
@jordan-brough How would we use this in spree-backend? Would we write our own custom `CartonMailer` from scratch, or try to reuse the code from `Spree::CartonMailer` somehow?

**Comment by jordan-brough** [comment]
@magnusvk yeah I'm thinking write it from scratch.  We end up changing just about everything that this Spree::CartonMailer does -- we don't use the template (and instead share a template with order completion), we don't use the @manifest variable, we have our own subject line, we add a bcc, we add a custom instance variable.  Though again we could instead add ways to customize all that stuff.

**Comment by magnusvk** [comment]
Well yeah, but that seems a little crazy. I'm :+1: for this and writing our own from scratch.

**Comment by gmacdougall** [comment]
Good idea here for allowing this to be customized.

I think the only thing that I would want to see is some documentation to the existing CartonMailer so that if I wanted to implement my own CartonMailer I would know what options I should design my class to handle.

**Comment by jordan-brough** [comment]
@gmacdougall hm, I kind of already wrote that sort of thing in app_configuration.rb on the setting. (There's not much to it). How about I just add a note in CartonMailer pointing people there? Unless there's something more you're talking about?

**Comment by gmacdougall** [comment]
Sorry for the confusion @jordan-brough 

I was just thinking that I'd like to see the documentation also exist on `core/app/mailers/spree/carton_mailer.rb` in the form of some better YARD there.

**Comment by jordan-brough** [comment]
@gmacdougall sure, that makes sense. That class could use better docs anyway.  I'd rather not repeat the same docs twice, so I'll move the docs to CartonMailer and remove them from AppConfiguration (and just point to CartonMailer instead).

**Comment by gmacdougall** [comment]
Sounds like a great plan. Thanks @jordan-brough!

**Comment by jordan-brough** [comment]
@gmacdougall updated. Look OK?

**Comment by gmacdougall** [comment]
Looks great. Thanks for the change.

:+1:

**Pull request merged**
