### PR TITLE
Move guides to new docs site

### PR DESCRIPTION
**Pull request by jgayfer**
**This PR depends on #2739**

This PR moves all of the existing documentation to the new docs site.

There are a few changes that had to be made to the docs in order to have them play nice with Middleman.

- Change the extension of each document from `.md` to `.html.md`
- Change relative links in each document from `.md` to `.html`

Other than what is mentioned above, there are no changes made to the docs themselves. The goal was to keep the docs as pure markdown to ensure they remain platform agnostic should they be used in a different capacity in the future.

### CODE REVIEW

**Comment by kennyadsl** [comment]
I merged a PR on guides (#2742) 😬 . Can you please rebase against master?

**Comment by jgayfer** [comment]
@kennyadsl Done!

**Comment by tvdeyen** [comment]
@jgayfer #2739 has been merged.

**Comment by tvdeyen** [comment]
@jgayfer thanks. This needs another rebase after we merged #2747

**Comment by jgayfer** [comment]
@tvdeyen Rebased

**Comment by tvdeyen** [comment]
Thanks!

**Pull request merged**
