### PR TITLE
More auth tweaks

### PR DESCRIPTION
**Pull request by Senjai**
This PR contains a number of further tweaks around permissions. Specifically the intentions for the restricted stock transfer permission set where modified around what stock transfers can be shown. 

Additionally there was a desire to have users with read only permissions on promotions be able to visit promotions#edit on the backend.

### CODE REVIEW

**Comment by athal7** [comment]
just curious if you considered making a promotions#show route instead to be more consistent with the approach we've taken for other items here.

**Comment by athal7** [comment]
:+1:

**Comment by Senjai** [comment]
We discussed this in slack and opted to stick with the edit action changes for simplicity, given that the majority of the backend currently uses edit actions for both "show" and "edit" purposes (e.g. orders#edit).

**Comment by jhawthorn** [comment]
I would love for us to use "show" for actions which are "show + edit", but there's no reason for that to be in this PR's scope.

:+1:

**Comment by magnusvk** [comment]
:+1:

**Pull request merged**
