### PR TITLE
Feature/address geo points

### PR DESCRIPTION
**Pull request by skukx**
Adds latitude and longitude columns to Spree::Address table.
These columns are auto-populated by the geocoder gem.

See https://github.com/alexreisner/geocoder

### CODE REVIEW

**Comment by tvdeyen** [comment]
Hi. Thanks for your interest in Solidus and your contribution. It's very much appreciated. 

This feature is better as an extension and is not something we want to have in core. It brings privacy issues, that not every store wants to deal with. 

So, as core feature I :-1: this. But as extension this feature would be great, as this is good work.

**Comment by tvdeyen** [comment]
If you have interest in maintaining the extension I can create a repo under https://github.com/solidusio-contrib for you.

**Comment by jhawthorn** [comment]
This is very cool, but I also don't think this belongs in Solidus core.

Adding extra API calls to the checkout process is not something that can be taken lightly.

This would make an excellent extension

**Comment by skukx** [comment]
@tvdeyen That would be great to get a repo under solidusio-contrib.  My employer would find it very valuable to perform analytics using these geo-points.

**Comment by tvdeyen** [comment]
@skukx done

https://github.com/solidusio-contrib/solidus_geocoding

**Pull request closed without merging**
