### PR TITLE
Backport #4228 to V2.11

### PR DESCRIPTION
**Pull request by jcsanti**
Many thanks to @waiting-for-dev & @kennyadsl for the quick review of #4228 🙂🚀 

**Description**

This PR backports #4228 to Solidus 2.11.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- ~[ ] I have updated Guides and README accordingly to this change (if needed)~
- [x] I have added tests to cover this change
- [x] I have attached screenshots to this PR for visual changes (present in original PR)

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks, but if we want to backport I think we also need to do it on 3.0.

**Comment by jcsanti** [comment]
> Thanks, but if we want to backport I think we also need to do it on 3.0.

My bad, I forgot there already was a new minor version for solidus 3. I'll open another PR right away!

**Review by waiting-for-dev — APPROVED** [review]
Thanks!

**Comment by waiting-for-dev** [comment]
We're forgetting the most recent minor version: v3.1. We need to backport there :slightly_smiling_face:

**Comment by jcsanti** [comment]
> We're forgetting the most recent minor version: v3.1. We need to backport there 🙂

Hello @waiting-for-dev, happy New Year!

Here is the PR for 3.1 => https://github.com/solidusio/solidus/pull/4237 🙂

**Review by jarednorman — APPROVED** [review]

**Review by waiting-for-dev — APPROVED** [review]
Thanks! And Happy New Year @jcsanti! :partying_face:

**Pull request merged**
