### PR TITLE
[v3.1] Remove Trailing Zeroes in Tax Amount

### PR DESCRIPTION
**Pull request by Naokimi**
Opening https://github.com/solidusio/solidus/pull/4758 towards v3.1 due to merge conflicts

### CODE REVIEW

**Comment by Naokimi** [comment]
Running locally I got this error on 22 specs:
```
Psych::DisallowedClass:
       Tried to load unspecified class: BigDecimal
```

**Comment by Naokimi** [comment]
tried adding 
```ruby
config.active_record.yaml_column_permitted_classes = [BigDecimal, Symbol, ActiveSupport::HashWithIndifferentAccess, 
      ActiveMerchant::Billing::Response]
```
to `core/lib/spree/testing_support/dummy_app.rb` and now number of failing specs have been reduced to 3 with the following error:
```
ActionView::Template::Error:
       Tried to load unspecified class: ActiveMerchant::Billing::Response
```
Will investigate more later on

**Comment by kennyadsl** [comment]
@Naokimi maybe because it's already set here: https://github.com/solidusio/solidus/blob/a22723079f88387f53f72b503db875b9d97aa3f5/core/lib/spree/core/engine.rb#L21?

**Comment by tvdeyen** [comment]
Superseded by https://github.com/solidusio/solidus/pull/4827

**Pull request closed without merging**
