### PR TITLE
Fix the media queries used for our grid

### PR DESCRIPTION
**Pull request by graygilmore**
This fixes a bug where content would be cut off. This is a simple stop-gap before we rewrite this properly.

Before:
screen shot 2016-02-02 at 8 27 12 pm

After:
screen shot 2016-02-02 at 8 25 59 pm

### CODE REVIEW

**Comment by jhawthorn** [comment]
:+1: Looks good to me

In your opinion should we backport this to the 1.2 branch?

**Comment by graygilmore** [comment]
Good question. Yes, this should have been a part of the left navigation introduction.

**Comment by Sinetheta** [comment]
Good fix for an unfortunate problem. It's too bad we don't have element queries for this. Maybe a comment? `// old width + sidebar width`

**Comment by jhawthorn** [comment]
@graygilmore pointed out to me that this is used by both frontend and backend. We probably want to make this change only on the backend.

**Comment by graygilmore** [comment]
Yes, I will pull this out of core and put a file in each of the backend/frontend. Then I'll be able to use `skeleton.css.scss` and use the `$width-sidebar` in the file.

**Comment by graygilmore** [comment]
@Sinetheta moved the file into Sass-land so I can do `768px + $width-sidebar` which should be clear enough.

@jhawthorn added a new commit which addresses the admin/front-end issue: https://github.com/graygilmore/solidus/commit/a30a920113bd611a98b59a636483e7af0d9f9696

**Comment by jhawthorn** [comment]
:+1: again from me

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
