### PR TITLE
Allow item_adjustments form to specify calculator-specific fields

### PR DESCRIPTION
**Pull request by philbirt**
Given a promotion action with complex fields, when creating it with and order-level
action it will allow you to specify the template that you want to render for the
promotion action. If no template is available, it uses the default fields.

If the promotion action is for the item-level, it will always use the default fields, not allowing for any custom templating.

This allows stores to have the same logic for both order and line-item level promotion actions.

The code is a little hairy, but is lifted directly from the `_create_adjustment` partial. Consistency is good.

### CODE REVIEW

**Comment by jhawthorn** [comment]
Thanks Phillip

Since we're using these same 8 lines in two places now can we extract it to a helper or other template?

**Comment by philbirt** [comment]
The two partials were actually identical at this point, sans one variable, so i pushed the whole file into one common partial, and passed the calculators as a local. Not 100% on the naming of the new partial or its location, so any opinions on that would be welcome

**Comment by cbrunsdon** [comment]
:+1:  by me.

Huzzah for removing code! Thanks @philbirt

**Comment by jhawthorn** [comment]
Awesome :+1:

**Comment by magnusvk** [comment]
:+1: @philbirt do you want to squash or should I hit the big green button?

**Pull request merged**
