### PR TITLE
Update underscore.js and backbone.js

### PR DESCRIPTION
**Pull request by jhawthorn**
We were running somewhat old versions, it was time for an upgrade.

This also moves them into our `solidus_admin` vendor asset namespace.

### CODE REVIEW

**Comment by stewart** [comment]
:+!

**Comment by stewart** [comment]
:+1: for namespacing, :100: for updating JS dependencies.

**Comment by tvdeyen** [comment]
:+1:

**Comment by mamhoff** [comment]
:+1:

**Pull request merged**
