### PR TITLE
Pass current user to OrderContents#update_cart

### PR DESCRIPTION
**Pull request by jordan-brough**
This will allow stores and extensions to perform logging & auditing
and to customize #update_cart based on the user performing the update.

### CODE REVIEW

**Comment by athal7** [comment]
i'd be interested in putting an even more explicit hook into update_cart so that we don't need to override the method.

**Comment by jordan-brough** [comment]
@athal7 agreed, that would be a great followup as well.  We could tackle that separately though yeah?

**Comment by athal7** [comment]
if you'd like...

**Comment by jhawthorn** [comment]
I don't understand why this is desirable. Orders have a user associated with them. If this is to log admin actions, I feel that would be better handled in the admin.

**Comment by jordan-brough** [comment]
I chatted w/ John and we seem to be in agreement that passing in the user will be a good thing, but it sounds like it'll be best to do that in the context of providing a real extension point like Andrew suggested so that the benefit is more obvious.  I'm going to close this PR and work up something larger that solves this issue and some others for us.

**Pull request closed without merging**
