### PR TITLE
Expose ...OrderAdjustmentsRecalculator#calculate_eligibility bug

### PR DESCRIPTION
**Pull request by julienanne**
## Summary

Spec to expose the inaccurate adjustment eligibility with shipping promotion action during Spree::Promotion::OrderAdjustmentsRecalculator call
The issue #2387 expose many different way to have the trouble and to correct them temporary but not definitively ;)
Sorry but can't, at the moment, propose a correction PR just a failing spec to expose the trouble for inspiration.
I make it draft for the moment.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Thanks, @julienanne. Marking it as a draft for now.

**Comment by fthobe** [comment]
@mamhoff this is solved with the new promotion system, right?

**Comment by mamhoff** [comment]
Yes, this shouldn't happen with the new promo system. If you want to be super-sure, you can port the test to `solidus_promotions` and see for yourself.

**Comment by fthobe** [comment]
@jarednorman can in fact be closed as resolved

**Pull request closed without merging**
