### PR TITLE
Sticky admin header

### LINKED ISSUE #630: Move page title and action buttons into a sticky header
Currently the page title and action buttons are scrollable with the rest of the page content. I’d like to place these items in a sticky area of the page so that the user can always see what page they’re on and have easy access to functions like adding new items to lists. 

The page title would be left aligned and the action buttons would be right aligned to the screen. The content in the page would remain fixed and centered. The page title would truncate if it was exceptionally long and the screen was too small for it to fit on one line, although if the user hovered over it they could see the full page title in a browser styled tooltip.

See the mockup for details. (ignore the left nav visual design for now)

Please let me know your thoughts in the comments below.

6-sticky-header

### PR DESCRIPTION
**Pull request by tvdeyen**
Closes #630

localhost-3000-admin-stock_items

localhost-3000-admin-products 1

### CODE REVIEW

**Comment by tvdeyen** [comment]
@Mandily @graygilmore FYI

**Comment by kennyadsl** [comment]
@tvdeyen Great! We don't need to take into account smaller screen versions for now right?

**Comment by kennyadsl** [comment]
I actually just found an issue with elements inside the `.content-wrapper` that has a z-index applied, like datepicker:

schermata 2017-10-05 alle 16 16 18

If I got it correctly, even if we respect the stacking order and give more priority to an element pushing it at the end of the list there could be other child elements inside previous elements with z-index (new stacking context) that would take precedence in display order.

I made a little codepen to simplify the situation: https://codepen.io/kennyadsl/pen/vepxwO

**Comment by jhawthorn** [comment]
Code seems fine, but I'm not a fan of having a sticky header. I don't think users benefit from having the information in the header visible at all times. That information is less important than that on the rest of the page, and it eats quite a bit of screen real estate.

I also see some z-index issues.

**Comment by Mandily** [comment]
For a little more context - the idea here was that the action buttons would always be in view and accessible by putting them in the header. Create actions like "new product" would live there as well as save and cancel buttons once a user was in those new or edit views.

As for small/mobile screens, we could do the fancy thing of scrolling down the header goes away but scrolling up brings it back into view.

**Comment by mtomov** [comment]
I'm also of the opinion that screen estate for content is more important than saving a _scroll up_ to do a button press. The buttons, which sit at the top right, in my view, are actually not as often used, as the actions related to the general peruse of the data.

**Comment by tvdeyen** [comment]
> I don't think users benefit from having the information in the header visible at all times. That information is less important than that on the rest of the page, and it eats quite a bit of screen real estate.

The header mostly contains breadcrumbs and is therefore a navigation bar, not an information bar. I do believe that users will benefit from having the header navigation sticking at the top, like we have the main navigation on the left side sticking. 

The actual change necessary is not that intrusive. If you are concerned about the change DOM position I could leave it as is and use a very high `z-index` value instead. but using the DOM positioning is strongly recommended, though.

> Create actions like "new product" would live there 

👍 on having navigable buttons ("New product" is actually a navigation action) inside the header is good UX IMO and that's why I consider a fixed header a good thing.

> as well as save and cancel buttons once a user was in those new or edit views.

I would strongly argue against putting "save" and "cancel" buttons into the header, but this is another discussion actually. 

> I also see some z-index issues.

Besides the aforementioned date picker I did not found any more z-index issues. Could you please mention them, so I can investigate?

**Comment by jhawthorn** [comment]
> Besides the aforementioned date picker I did not found any more z-index issues. Could you please mention them, so I can investigate?

Price inputs seem to float above the header.

**Comment by tvdeyen** [comment]
Thanks. Just saw, that this happens even in non sticky header branches:

z-index price fields

Will take a look

**Comment by tvdeyen** [comment]
We decided to not have a sticky header

**Pull request closed without merging**
