### PR TITLE
Add exchange translation

### PR DESCRIPTION
**Pull request by Murph33**
This had been a missing translation I'd added in #795 but it didn't fit in with that PR so I took it out to add it separately.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
should things be using this and not the model name of ```Spree::Exchange```?

**Comment by Murph33** [comment]
No.  Making that change and adding that model to the dictionary seems like a better fix.

**Comment by tvdeyen** [comment]
`Spree::Exchange` could extend `ActiveModel::Naming`. 

Then we could also remove [this little fella](https://github.com/spree/spree/blob/master/core/app/models/spree/exchange.rb#L41)

**Comment by Murph33** [comment]
That sounds best, thanks.

**Pull request closed without merging**
