### PR TITLE
Simplify Coupon PromotionHandler

### PR DESCRIPTION
**Pull request by jhawthorn**
The controversial commit should be the last one where I remove some functionality. Hopefully I explained my reasoning well in the commit message.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
As discussed IRL hawth is going to throw some test cases about what didn't work before and how the new behaviour should be.

**Comment by jhawthorn** [comment]
> This removes a fair chunk of messaging we gave to clients that was (usually) right, doesn't it? Like the fact the coupon might be inelligible because a better one exists? I'm not sure I'm comfortable removing that.



> Wait, how and when do coupons get applied? was the update_totals and persist_totals ever ran? It seems like this changes quite a bit of behaviour....

`update_totals` and `persist_totals` are still run they've been moved to the other method. This raises a good point: with the existing behaviour, it was possible that applying the coupon could put the order in an inconsistent state. If the first adjustment was marked ineligible (there was a better coupon) but was applied to a different adjustment in the order, the order would not have the correct totals until another order.update was called.

**Comment by jhawthorn** [comment]
@cbrunsdon Added a test for the previously broken behaviour. It fails on versions before 02ed14f and passes now.

**Comment by cbrunsdon** [comment]
To be clear: there were no tests testing the :coupon_code_not_found and :coupon_code_better_exists logic that was previously being returned and we are changing that behaviour.

Yes, those happen under pretty dubious circumstances, but that is the existing behaviour.

Does anyone want to chip in on if they rely on those being returned or not? Maybe @alepore or @tvdeyen?

**Comment by peterberkenbosch** [comment]
@jhawthorn do we need to revisit this one?

**Pull request merged**
