### PR TITLE
Add i18n-tasks and normalize translations

### PR DESCRIPTION
**Pull request by afdev82**
This PR adds the `i18n-tasks` gem to check the translations and reorders them like how is already done in the `solidus_i18n` project.

In this way it's easier to contribute, because the translations are in the same position.

### CODE REVIEW

**Comment by afdev82** [comment]
I just run `bundle exec i18n-tasks normalize` inside the `core` directory

**Comment by kennyadsl** [comment]
@afdev82 Hey can you please rebase on master since in the meantime some en key changed? I think it could be easier to revert changes and re-run the script at this point since there are a lot of conflicts. Thanks!

**Comment by afdev82** [comment]
@kennyadsl yes, I will do it soon ;)

**Comment by afdev82** [comment]
maybe we could add `bundle exec i18n-tasks health` to the ci, we do the same for our projects and it's useful

**Comment by tvdeyen** [comment]
> maybe you could add bundle exec i18n-tasks health to the ci, we do the same for our projects and it's useful

This is probably a good idea, but I don't know how this will impact the current state of translations. We might want to check the health first, fix all issues and than enable it.

**Comment by kennyadsl** [comment]
Thanks!

**Pull request merged**
