### PR TITLE
Use DbMaximumLengthValidator on product_properties.value

### PR DESCRIPTION
**Pull request by jordan-brough**
This was reverted in 31352dae44d1db7ce09cf195e2f8ce2168bce1ca but it
seems to actually work.  Currently only MySQL seems to have a length
restriction on the "value" field here.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
@jordan-brough can you expand? I'm wondering how this compares to PG and SQLite.

**Comment by jordan-brough** [comment]
@BenMorganIO see my updated code comment. As of Rails 4.2 `t.string` columns do not have a limit in PostgreSQL and SQLite.  So PostgreSQL, SQLite, and MySQL Solidus stores created before Solidus was updated to Rails 4.2 will have a 255 limit, and _MySQL_ stores created after the Rails 4.2 update will have a 255 limit.

**Comment by jordan-brough** [comment]
cc @solidusio/owners

**Comment by magnusvk** [comment]
:+1:

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
