### PR TITLE
loosen paperclip dep to allow minor version upgrades

### PR DESCRIPTION
**Pull request by jrochkind**
paperclip 4.3.6 is latest as of this writing.

### CODE REVIEW

**Comment by cbrunsdon** [comment]
I'm good on this one, thanks :+1:

**Comment by jhawthorn** [comment]
Seems reasonable to me :+1:
It looks like they have version 5.0 just around the corner too.

**Comment by cbrunsdon** [comment]
@jrochkind would you be kind enough to rebase, please.

**Comment by jrochkind** [comment]
That was harder than expected, just redid it from scratch for this one-line change.

**Pull request merged**
