### PR TITLE
Fix double highlight on admin menu when Product Stock tab is active

### PR DESCRIPTION
**Pull request by aitbw**
Refs: #2950

Here's a screenshot to demonstrate how the menu looks after the proposed patch

screenshot_2018-11-22 store stock - apache baseball jersey - products

Open to suggestions! :raised_hands:

### CODE REVIEW

**Comment by jacobherrington** [comment]
@tvdeyen I agree, if it seems like there are more examples of this problem, but if it is only on the product stock page this solves that issue.

**Comment by jacobherrington** [comment]
@aitbw let's try to approach the problem from another perspective. Instead of removing the class from the incorrect element, we should make sure it never gets applied. Does that make sense?

**Comment by tvdeyen** [comment]
This is my alternative approach https://github.com/solidusio/solidus/pull/2969 to this issue. 

@aitbw thanks for working on this and sorry for the rejection, but we would like to fix the issue at the root cause. Having to deal with issue like this in a helper is not ideal. That's why I made this alternative approach. Thanks for the contribution. That's very much appreciated.

**Comment by aitbw** [comment]
Don't worry @jacobherrington @tvdeyen, I completely understand and I'm more fond of a solution like #2969 :relaxed:

**Pull request closed without merging**
