### PR TITLE
make customer email field required when an admin is making a new order

### PR DESCRIPTION
**Pull request by jacobherrington**
This adds simple HTML validation for the email field. 

I personally think that is enough to solve the problem.

refs #2008

### CODE REVIEW

**Comment by BenMorganIO** [comment]
I think you should also add a validation in the model as well. If the order is a guest order, then it should require the customer email.

**Comment by jacobherrington** [comment]
Hey @BenMorganIO! Thanks for weighing in.

Inside the Order model line 127 is `validates :email, presence: true, if: :require_email` which makes sure that you can't have a guest checkout without an email. 

The issue is that the frontend doesn't stop you from progressing though several long screens before the validation fails, causing the user to lose significant time if they have to remake the order. This change will just keep the user from progressing to the next screen without inputting an email - ultimately saving time for an admin user.

**Comment by BenMorganIO** [comment]
Ah, I see. :+1: good sir.

**Comment by jacobherrington** [comment]
@tvdeyen anything else I need to do on this PR. Seems pretty trivial to me, but happy to do some fixups if needed.

**Comment by tvdeyen** [comment]
@jacobherrington no, all fine. We need a second review of a core team, then we are ready to go.

**Pull request merged**
