### PR TITLE
Added prefix Spree:: to OrderMutex

### PR DESCRIPTION
**Pull request by sanchojaf**

### CODE REVIEW

**Comment by jhawthorn** [comment]
Thanks for the PR @sanchojaf. Could you comment on why you made this change? Is there an issue this is solving for you?

**Comment by eduardopino** [comment]
Hi @jhawthorn, in general is good practice have the prefix Spree::, for example the line bellow included that, and yes I have an issue when I try to override this method.

Thanks.

**Comment by sanchojaf** [comment]
Sorry the last comment was mine, using other user

**Comment by bcrunsdon** [comment]
Seems reasonable to me :+1:

**Comment by jordan-brough** [comment]
> yes I have an issue when I try to override this method

@sanchojaf when you copy-paste this code into _your_ controller it doesn't work because it's missing the `Spree::` prefix.  Is that correct?  So the original code isn't a problem, it's just a bit harder to copy-paste?

I do not have a strong opinion on this.  But it might be nice to standardize how we do this.  We switch between including/omitting the prefix a lot.

**Comment by mamhoff** [comment]
I think it's good practice to include prefixes always. We had a funny one with a PromotionAction called `User` at one point - it was really irritating to track down and it wouldn't have happened with good namespacing. If you use multiple large engines (say Solidus and Alchemy) in the same project, you do sometimes end up with conflicting names. `OrderMutex` is a particularly improbably candidate, but as a general rule of thumb, I'm very +1 on using prefixes, and even `::Spree::OrderMutex` style prefixes. It also helps with some weird autoloading issues.

**Comment by BenMorganIO** [comment]
I'm :+1: on namespacing. It adds clarity and the pros of namespacing to the code.

**Comment by cbrunsdon** [comment]
Ah, @jordan-brough's explanation of events makes a lot of sense. I'd agree that we should make a decision. Or even make a decision on not accepting PR's that just add/remove prefixes.

I myself don't have an opinion, but would maybe lean towards always including it inside of core? @jhawthorn thoughts?

**Comment by jhawthorn** [comment]
This is tricky.

There are definitely times where we need to add prefixes to get around rails autoloading issues. These occur whenever a store has the same class at the root level that we do under the `Spree::` namespace.

However, it's pretty ugly to need to use the full prefix every time we reference a class. If we are going to include the full class we should use the "absolute" version (with leading `::`).

A third option would be to eager load all of our classes, which I'm unsure is viable or even desirable.

**Comment by mamhoff** [comment]
Can we go on a case-by-case basis here? I know it's not as systematic as "always prefix all the things" or "never prefix anything", but in this case it clearly helped one user, and it does not *really* make a big difference. I'm :+1: for merging this, even if we don't have a super clear rule to go by.

**Comment by tvdeyen** [comment]
I'm with Martin here. :+1:

**Comment by jhawthorn** [comment]
> Can we go on a case-by-case basis here

I can agree with this

**Pull request merged**
